### ISSUE TITLE
Enable the "save" button when editing an organization

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes-frontend#10]
Currently, saving an organization when editing doesn't work on staging.

Our new backend api is: https://api.people-test.sphinx.chat/

**Comment by Vayras** [comment]
@ecurrencyhodler I wish to contribute towards this . Can I work on this , Let me know

**Comment by ColdMice** [comment]
Hey! came across this on Github, I would like  to work on this issue, can you assign me to this

**Comment by ecurrencyhodler** [comment]
Hey @ColdMice! I'm glad you're checking out this project. Are you on sphinx yet by any chance?

**Comment by ColdMice** [comment]
@ecurrencyhodler Not yet. I did read the Readme and discovered the site

**Comment by ecurrencyhodler** [comment]
Great! Read this [FAQ](https://docs.google.com/document/d/16NQ4SM4ptP4Lz5JKERAagdNw3GFRVv9eshMZ_oU-MVw/edit?usp=sharing) to get onboarded. I still need to sync with the team about the scope of this issue but I will find you a bounty to work if not this one.

Here's the code to sign up:
connect::relay.swarm4.sphinx.chat::02d14e01adcf94dbf2a0ca8d511b83923d97abe2472da04976a765b080db32e56e


Reply back with your username when you're done.

**Comment by ColdMice** [comment]
@ecurrencyhodler I'm getting an error "generate token failed"

**Comment by ecurrencyhodler** [comment]
my apologies. try this one: 
connect::relay.swarm4.sphinx.chat::03dddeb7f40005de6228a6f38b4ceda79d564ed8a1996e1e09c294afefaaae5c48

**Comment by ColdMice** [comment]
@ecurrencyhodler no problem signed into the app, my username is Coldmice on sphinx

**Comment by ecurrencyhodler** [comment]
Awesome! I will follow up with you tomorrow on if this will work as a bounty.

**Comment by ColdMice** [comment]
yeah okay I will wait for your update

**Comment by ecurrencyhodler** [comment]
This was a cache issue on my end. Closing it. @ColdMice you can find more bounties here: https://community.sphinx.chat/bounties

Ping me if you see anything you like.

**Comment by ColdMice** [comment]
@ecurrencyhodler okay I will look out for any open issue that I can fix and let you know. Thanks for the update

**Comment by ecurrencyhodler** [comment]
@ColdMice check your sphinx chat.
