### ISSUE TITLE
Enable Error Handling when update profile api is throwing error

### ISSUE THREAD

**Issue by Nightrider0098** [stakwork/sphinx-tribes-frontend#101]
### Bug
There is no error message when a profile fails to save:

https://github.com/stakwork/sphinx-tribes-frontend/assets/39752890/bad314c5-7621-49a3-81d7-380c1999dfa1

### Expected Behavior
Let's keep the edit bounty modal open until we get a response back that the save has been successful. If it successful, we close the modal. If it is unsuccessful, the edit bounty modal should remain open and we should display a toast message that says: "Update failed. Please try again."

### Acceptance Criteria

- [ ] I've tested on Chrome
- [ ] I've posted a video in my pr

**Comment by ecurrencyhodler** [comment]
Thanks Nightrider for submitting this issue. Let's keep the edit bounty modal open until we get a response back that the save has been successful. If it successful, we close the modal. If it is unsuccessful, the edit bounty modal should remain open and we should display a toast message that says: "Update failed. Please try again."

Let's include a test that a toast is triggered if save is failed.

**Comment by Nightrider0098** [comment]
@kevkevinpal Test cases would required me to wrap `AboutFocusView` That would require me to mock entire store. Should i a separate PR to create that first. Cause it seems a little irrelevant to this pr.

**Comment by kevkevinpal** [comment]
> @kevkevinpal Test cases would required me to wrap `AboutFocusView` That would require me to mock entire store. Should i a separate PR to create that first. Cause it seems a little irrelevant to this pr. 

Yes if you could create another pr to fix that it would be great!

**Comment by Nightrider0098** [comment]
Should i attach that to a seperate issue?

**Comment by ecurrencyhodler** [comment]
Created a separate issue and bounty for it at #140
