### ISSUE TITLE
Block Icon 🚫 Not Displayed in Some User-Side Fields

### ISSUE THREAD

**Issue by aliraza556** [stakwork/sphinx-tribes-frontend#103]
**Describe the bug**
The issue is not with the organization's user permissions but rather on the user's side, where the block icon is not displayed in some fields.

**Bug Demo**: [Link](https://www.loom.com/share/331b4fd8b882436695eb478f32f455e8)

**To Reproduce**
1. Go to 'https://community.sphinx.chat/p/{org_uuid}/organizations'
2. Click on 'own organizations' and add a user, then view the user side.
4. Observe the error.

**Expected behavior**
I expected that when I added a user to my organization and viewed their user side on the 'https://community.sphinx.chat/p/{org_uuid}/organizations' page, the block icon would be displayed in relevant fields to indicate that the user has been blocked or restricted in some way.

**Desktop (please complete the following information):**
 - Browser [e.g. chrome ]

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a video in my PR
- [ ] I've created a test that shows the 🚫 appears over disabled buttons

**Comment by aliraza556** [comment]
@ecurrencyhodler Could you look at this issue and assign it to me?

**Comment by ecurrencyhodler** [comment]
Good job. I included a test. Here is the bounty: https://community.sphinx.chat/bounty/1345

**Comment by aliraza556** [comment]
Hi @ecurrencyhodler @elraphty 
Please review this PR #114
