### ISSUE TITLE
Labels Not Hiding on Scroll in Edit Bounty Modal Pop-Up

### ISSUE THREAD

**Issue by aliraza556** [stakwork/sphinx-tribes-frontend#106]
**Describe the bug**
When editing a bounty, some labels in the edit modal do not hide as they should while scrolling through the pop-up card.

https://www.loom.com/share/0a31f170e5d449e68cba03a778aad028

The problem is the current implementation (elastic UI) of the the dropdown on the site is too abstracted, is not very efficient, and does not behave how a dropdown should actually behave. 

**Expected behavior**
When scrolling in the Edit Bounty Modal, all labels and elements should appropriately respond by moving or hiding, ensuring a smooth and user-friendly interface.

To solve a lot of UI problems as discussed with the core team [@ecurrencyhodler @kevkevinpal @elraphty] we are now slowly moving towards our **own custom components**. This issue will cover dropdowns specifically.

**Desktop (please complete the following information):**
 - Browser [e.g. chrome]

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a video in my PR
- [ ] Include a test that states the dropdown menu persists on scroll if it's open.

**Comment by aliraza556** [comment]
@ecurrencyhodler Could you look at this issue and assign it to me?

**Comment by ecurrencyhodler** [comment]
Good find. I'll turn this into a bounty. Let's include a test that states the dropdown menu persists on scroll if it's open.

**Comment by ecurrencyhodler** [comment]
https://community.sphinx.chat/bounty/1350

**Comment by ecurrencyhodler** [comment]
@aliraza556 did you address this in #111?

**Comment by aliraza556** [comment]
Hi @ecurrencyhodler,
No, I didn't address this in issue #111.

**Comment by ecurrencyhodler** [comment]
Okay do you think you can submit a PR for this ASAP?

**Comment by aliraza556** [comment]
Ok, Sure.

**Comment by MahtabBukhari** [comment]
@ecurrencyhodler I have checked that here we are using elastic eui library and the drop-down is not handled by us it is default handled by library.
I will try to solve it if possible otherwise i will inform you.

**Comment by MahtabBukhari** [comment]
@ecurrencyhodler I have try to solve this but there is no css working to resolve this issue and may be there is an issue with elastic eui library

**Comment by ecurrencyhodler** [comment]
okay let me chat with the team. Thanks for reporting.

**Comment by Vayras** [comment]
@ecurrencyhodler is this available to work on, This does look like a css positioning issue

**Comment by ecurrencyhodler** [comment]
This is your vayras

**Comment by ecurrencyhodler** [comment]
Paid! https://community.sphinx.chat/bounty/1350
