### ISSUE TITLE
Resize "manage role" window

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes-frontend#107]
**Describe the bug**
Right now the "manage roles" window for org permissions is not correctly sized.

After adding a user to an org, click on the "gear" icon to manage their roles. 
<img width="1148" alt="Screenshot 2024-01-31 at 11 44 20 AM" src="https://github.com/stakwork/sphinx-tribes-frontend/assets/32662508/f2724f9b-fcaa-4ad4-beb3-920b938344d6">

**Expected behavior**
Follow the design requirements in [figma](https://www.figma.com/file/1aL3lgG5Rpkti4b0j42fwf/Bounties---FINAL-DESIGNS?type=design&node-id=7776%3A6788&mode=design&t=X6XzrgrSW7pv1Lo4-1).

**Desktop (please complete the following information):**
 - Browser: Chrome

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a screenshot in my PR

**Comment by AbdulWahab3181** [comment]
@ecurrencyhodler could you please assign me

**Comment by MahtabBukhari** [comment]
@ecurrencyhodler Could you assign me this one?

**Comment by VividhPandey003** [comment]
@ecurrencyhodler Could you please assign this to me?
