### ISSUE TITLE
Make people profile space consistent

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes-frontend#108]
**Describe the bug**
The space for the profile is inconsistent.
<img width="1147" alt="Screenshot 2024-01-31 at 11 49 44 AM" src="https://github.com/stakwork/sphinx-tribes-frontend/assets/32662508/c28b435b-2dc9-4b6f-a0e5-b9e17a19fd80">

**Expected behavior**
The line should be the same across all the profiles. When there is a lot of text, only the first two lines are displayed and the rest of the description trails off with "...".

Therefore make all profiles match the same length as when there are profiles with lots of text. It should basically be the same length as Raph's profile.

**Desktop (please complete the following information):**
 - Browser: Chrome

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a screenshot in my PR

**Comment by MirzaHanan** [comment]
@ecurrencyhodler Assign me?

**Comment by adeel-ahmad-sh** [comment]
@ecurrencyhodler kindly assign me this one.

**Comment by adeel-ahmad-sh** [comment]
I have submitted my first task

**Comment by ColdMice** [comment]
@ecurrencyhodler I wish to contribute towards this.

**Comment by vishnu552** [comment]
Hello @ecurrencyhodler ,can you assign me this issue.
