### ISSUE TITLE
Re-align edit bounty modal

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes-frontend#111]
**Describe the bug**
Right now various boxes inside our edit bounty modal are misaligned:
<img width="554" alt="Screenshot 2024-01-31 at 2 55 16 PM" src="https://github.com/stakwork/sphinx-tribes-frontend/assets/32662508/bbbf699b-f8ef-481b-ad70-7763651156c4">
<img width="590" alt="Screenshot 2024-01-31 at 2 55 22 PM" src="https://github.com/stakwork/sphinx-tribes-frontend/assets/32662508/a8514ee0-f710-499a-9ce0-16b7e07c9050">

**Expected behavior**
Match the design to this image where all the boxes are more evenly spaced throughout the whole modal:
![209680997-a785702f-beb7-4a8d-a365-9695bc53da47](https://github.com/stakwork/sphinx-tribes-frontend/assets/32662508/30835672-f428-4d81-8a31-c105bb02aa65)

**Desktop (please complete the following information):**
 - Browser: Chrome

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted video in my PR

**Comment by aliraza556** [comment]
@ecurrencyhodler assign me?

**Comment by aliraza556** [comment]
I complete both issue https://github.com/stakwork/sphinx-tribes-frontend/issues/106

**Comment by ecurrencyhodler** [comment]
I'd like for a different hunter to complete this ali.

**Comment by Zoe-AE-ND** [comment]
I can help with this.

**Comment by vishnu552** [comment]
@ecurrencyhodler,can you assign me ?

**Comment by ecurrencyhodler** [comment]
Hi @Zoe-AE-ND ! Are you on sphinx chat yet? It has a bitcoin bounty tied to this issue. Also how did you hear about our project?

**Comment by ecurrencyhodler** [comment]
Amazing! Here is our [FAQ](https://docs.google.com/document/d/16NQ4SM4ptP4Lz5JKERAagdNw3GFRVv9eshMZ_oU-MVw/edit?usp=sharing). Follow the instructions there to download our sphinx chat app.

You can use this sphinx code: 
connect::relay.swarm4.sphinx.chat::03f0274aefc91df7c66bdf15576f8b715951e69df0ddbe7eee1c6c4f1fd83ca41d

Then login here: https://community.sphinx.chat/bounties

And reply back with your sphinx alias. I'll assign the bounty to you.

**Comment by ecurrencyhodler** [comment]
Just be a thoughtful contributor. Try to run tests locally on your computer before submitting a PR the best you can. We typically want quick turnaround on bounties (1-3 days). If I don't hear from you within a week, I'll unassign you from the issue + bounty.

We have two maintainers: Kev / Raph who will be reviewing PR's.

**Comment by ecurrencyhodler** [comment]
I need you to sign into here so I can assign the bounty to you: https://community.sphinx.chat/bounties

**Comment by okhot** [comment]
Done 👍

**Comment by ecurrencyhodler** [comment]
Great. Oh and also pay attention to the acceptance criteria. This one doesn't have a lot but other issues will including a unit or component test.

**Comment by ColdMice** [comment]
@ecurrencyhodler I want to work on this, can you assign this one to me

**Comment by bilalshaikh292** [comment]
@ecurrencyhodler if there is Any changes In this Issue (i.e if others are not working on this issue) You can assign it to me.I am willing on work on this issue

**Comment by ecurrencyhodler** [comment]
@Zoe-AE-ND do you have an update on this issue?

**Comment by bilalshaikh292** [comment]
here's a video of what i have tried and waht are the output result

Uploading testModel.mp4…

**Comment by ecurrencyhodler** [comment]
@bilalshaikh292 looks like the video finish uploading. I'm going to assign this to you as well.

**Comment by bilalshaikh292** [comment]
https://github.com/stakwork/sphinx-tribes-frontend/assets/110531971/4a1b7d21-acf9-4b5c-a637-6cd4802e349b

**Comment by bilalshaikh292** [comment]
@ecurrencyhodler you can have a look and let me khow what to be done about the Assign Developer section .

**Comment by ecurrencyhodler** [comment]
Okay yeah we don't need to touch the "assign developer" portion. Just the sections above it.

**Comment by bilalshaikh292** [comment]
Ok @ecurrencyhodler that much is done.
I will create a PR soon
