### ISSUE TITLE
Change text to "custom" when a custom date range is selected on superadmin

### ISSUE THREAD

**Issue by ChetanKarwa** [stakwork/sphinx-tribes-frontend#113]
**Describe the bug**
When changing the date range to custom, the text doesn't change to custom

https://www.loom.com/share/8a2ceba3e8ee45a7ad7b7dc60f6fd650

**Expected behavior**
Text should change to custom

**Desktop (please complete the following information):**
 - Browser: Chrome

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a video in my PR
- [ ] I've created a test that asserts that "custom" gets displayed when dates are selected

**Comment by ecurrencyhodler** [comment]
Okay this is in a private repo. So I'm going to cancel the bounty. Sorry.

**Comment by ecurrencyhodler** [comment]
@ChetanKarwa Woops wrong issue. Do you have an update on this issue?

**Comment by saithsab877** [comment]
@ecurrencyhodler assign me

**Comment by saithsab877** [comment]
Thanks

**Comment by saithsab877** [comment]
Hi @ecurrencyhodler,
Please check and give your suggestion regarding the options shown in the image:
![image](https://github.com/stakwork/sphinx-tribes-frontend/assets/156602406/7f7cce86-88cd-445e-a374-a90605fbee51)
1. Custom Date
2. Custom
Which option do you think is best?

**Comment by ecurrencyhodler** [comment]
Let's just stick with custom. It'll be shorter. Thanks!

**Comment by saithsab877** [comment]
Hi @ecurrencyhodler,
Please check the demo:
https://www.loom.com/share/16209d2719684450a81606faafdff1fa
Should I choose fixed width or auto?

**Comment by ecurrencyhodler** [comment]
Just center custom on fixed width for now. Thanks!
