### ISSUE TITLE
Ability to Self-Delete for Users

### ISSUE THREAD

**Issue by aliraza556** [stakwork/sphinx-tribes-frontend#115]
**Describe the bug**
The `user` Would be able to Delete Itself

**Bug Demo:** [Link](https://www.loom.com/share/a12f3334b0e0406b9918104741ae2f8f)

**To Reproduce**
1. Go to 'https://community.sphinx.chat/p/{org_uuid}/organizations'
2. Click on `own organizations` and add a user, granting the `Update members` permission role, then view the user side.
3. The user attempts to `delete itself`.
4. Observe the error.

**Expected behavior**
When an administrator removes a user from the organization, the user should not have the ability to self-delete.

**Fixed Demo:** [Link
](https://www.loom.com/share/4cd92b1636874ce2b992b23fd7bb4c74)
**Desktop (please complete the following information):**
 - Browser [e.g. chrome]

### Acceptance Criteria
- [x] I have tested on Chrome desktop
- [x] I have posted a screenshot or video in my PR

**Comment by aliraza556** [comment]
@ecurrencyhodler Could you look at this issue and assign it to me?

**Comment by ecurrencyhodler** [comment]
If mirza was the person who created the org, they won't be able to remove themselves from the org.
