### ISSUE TITLE
Update color of tags to be visible

### ISSUE THREAD

**Issue by Fog3211** [stakwork/sphinx-tribes-frontend#116]
**Describe the bug**
The colors of certain tags are not prominent enough, making the text difficult to read.

**To Reproduce**
1. Click `Post a Bounty` Button
2. Go to Step2
3. Select `Elastic search` Tag 

![image](https://github.com/stakwork/sphinx-tribes-frontend/assets/23151576/9fe75d62-b1e1-4b8d-b191-4dd5ba6d4fc1)
![image](https://github.com/stakwork/sphinx-tribes-frontend/assets/23151576/4731be21-73e9-4211-97cc-bb2e44d44c18)

**Expected behavior**
The color of this tag should have a contrast with the background color.

**Desktop (please complete the following information):**
 - Browser Chrome 120

### Acceptance Criteria
- [x] I have tested on Chrome desktop
- [x] I have posted a screenshot or video in my PR

The configuration of tagStyle is in this file 
https://github.com/stakwork/sphinx-tribes-frontend/blob/master/src/people/utils/languageLabelStyle.ts#L105

**Comment by bilalshaikh292** [comment]
assign

**Comment by ecurrencyhodler** [comment]
Okay can you also search for all colors and include that into the scope of this ticket? I'll create a bounty for you.

**Comment by ecurrencyhodler** [comment]
Here you go: https://community.sphinx.chat/bounty/1370

**Comment by Fog3211** [comment]
> Okay can you also search for all colors and include that into the scope of this ticket? I'll create a bounty for you.
 of course, this is the list of those tag colors
![image](https://github.com/stakwork/sphinx-tribes-frontend/assets/23151576/6e64a143-80b9-427d-977f-65dbe5e12aae)

**Comment by Fog3211** [comment]
@ecurrencyhodler Do you have a specific color preference, or should I let GPT generate a similar one? How about this?

![image](https://github.com/stakwork/sphinx-tribes-frontend/assets/23151576/cfd60dcd-65e9-422b-89b6-28a1fa89e130)

```
{
    label: 'Elastic search',
    border: '1px solid rgba(255, 204, 0, 0.1)',
    background: 'rgba(255, 204, 0, 0.1)',
    color: '#FFCC00'
  }
```

**Comment by ecurrencyhodler** [comment]
LGTM!
