### ISSUE TITLE
Fix Mobile adaptation of the People page for filters and long names

### ISSUE THREAD

**Issue by Fog3211** [stakwork/sphinx-tribes-frontend#120]
**Describe the bug**
There are two issues with mobile:

1. Unable to display the Filter button on mobile devices
2. When a user's name has excessively long text, horizontal scroll bars will appear.

**To Reproduce**
Here is the screenshot of the filter not being available on mobile:
![image](https://github.com/stakwork/sphinx-tribes-frontend/assets/23151576/30bad760-2d00-4515-a7f4-e586d9be4e22)

Here is a video of the excessive user name:
https://github.com/stakwork/sphinx-tribes-frontend/assets/23151576/38b23b72-a696-487b-8d66-9fadce7232c3

**Expected behavior**
1. On mobile devices, the Filter function can be displayed and used properly. 
2. The interface will occupy the entire screen without any horizontal scroll bars.

**Desktop (please complete the following information):**
 - Browser: Chrome 120

**Smartphone (please complete the following information):**
 - Device: iPhone13 PM safari

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a screenshot or video in my PR
- [ ] I have rebased before submitting my PR
- [ ] I have created a component test that the filter is visible

**Comment by Fog3211** [comment]
@ecurrencyhodler，could you please assign it to me?

**Comment by ecurrencyhodler** [comment]
@Fog3211 think you can get a PR up in 2 days?

**Comment by aliraza556** [comment]
assign me

**Comment by Fog3211** [comment]
> @Fog3211 think you can get a PR up in 2 days?

yes，i can do it
