### ISSUE TITLE
[Tests][Component] Add tests to frontend/app/src/pages/tickets/TicketModalPage.tsx

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes-frontend#121]
### Context

TicketModalPage.tsx Displays a single bounty in a modal. Add component test coverage.

File to be tested
`src/pages/tickets/__tests__/TicketModalPage.spec.tsx`

Create file
` src/pages/tickets/__tests__/TicketModalPage.spec.tsx`

Make a mock bounty and return the mock bounty when  `TicketModalPage.tsx`  makes a `getBounty()` call, also mock the `main.getBountyIndexById()` call to return your mock bounty index.

Check ```frontend/app/src/people/main/__tests__/MainHeader.spec.tsx``` for example

We want to test that the TicketModalPage displays the right data, and performs the right actions

### Acceptance Criteria

- [ ] Test that the TicketModalPage is rendered when the URL `{host}/bounty/{bountyId}` is hit.
- [ ] Test that the bounty description is pulled from GitHub if a github_link is present
- [ ] Test that the bounty bounty description displays the database description if the github_link is not present.
- [ ] Test that when the Delete Button is clicked, a bounty delete action is performed and the bounty gets deleted
- [ ] Test that when I click on edit, it takes me to the edit modal

You can use this PR as an example `https://github.com/stakwork/sphinx-tribes/pull/1185`

**Comment by ColdMice** [comment]
@ecurrencyhodler, @elraphty I can work on this assign me to this.

**Comment by ecurrencyhodler** [comment]
Here you go: https://community.sphinx.chat/bounty/1366

**Comment by ColdMice** [comment]
@ecurrencyhodler I have removed my assignment as I cannot complete this now

**Comment by ecurrencyhodler** [comment]
Okay thanks for the heads up.

**Comment by Fog3211** [comment]
@ecurrencyhodler  I can do this , please assign it to me

**Comment by ecurrencyhodler** [comment]
Paid 200k sats. GJ! https://community.sphinx.chat/bounty/1371

**Comment by Fog3211** [comment]
> Paid 200k sats. GJ! https://community.sphinx.chat/bounty/1371

sorry, You might have confused the ticket. The one that should actually be closed and paid for is this one -> https://community.sphinx.chat/bounty/1366

**Comment by ecurrencyhodler** [comment]
sorry about that thanks! https://community.sphinx.chat/bounty/1366
