### ISSUE TITLE
[Tests][Component] Add tests to frontend/app/src/pages/tickets/TicketModalPage.tsx For Paid State

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes-frontend#122]
### Context

TicketModalPage.tsx Displays a single bounty in a modal. Add component test coverage.

File to add test
`src/pages/tickets/__tests__/TicketModalPage.spec.tsx`

Update file
` src/pages/tickets/__tests__/TicketModalPage.spec.tsx`

Make a mock bounty and return the mock bounty when  `TicketModalPage.tsx`  makes a `getBounty()` call, also mock the `main.getBountyIndexById()` call to return your mock bounty index.

Check ```frontend/app/src/people/main/__tests__/MainHeader.spec.tsx``` for example

We want to test that the TicketModalPage performs the right actions when a bounty is paid

### Acceptance Criteria

- [ ] Test that the TicketModalPage is rendered when the URL `{host}/bounty/{bountyId}` is hit.
- [ ] Test that the Delete button is disabled when a bounty is paid
- [ ] Test that I can be able to mark a bounty as `unpaid` if I am the creator of the bounty
- [ ] Test that I can delete an unpaid bounty

You can use this PR as an example `https://github.com/stakwork/sphinx-tribes/pull/1185`

**Comment by KumarNayan** [comment]
Assign

**Comment by ecurrencyhodler** [comment]
@adeel-ahmad-sh do you want to try this?

**Comment by adeel-ahmad-sh** [comment]
@ecurrencyhodler sure

**Comment by wright-eric** [comment]
Assign
