### ISSUE TITLE
[Tests][Component] Add tests to src/people/widgetViews/OrganizationView.tsx

### ISSUE THREAD

**Issue by Vayras** [stakwork/sphinx-tribes-frontend#124]
### Context

The `OrganizationView.tsx` is responsible for displaying all user-created and enrolled organizations. Add component test coverage to this page.

### File to be tested
`src/people/widgetViews/OrganizationView.spec.tsx`

### File to create
` src/pages/tickets/__tests__/TicketModalPage.spec.tsx`

Make a mock organization and return the mock organization when Organization tab makes a getUserOrganization() call, also mock the main.getOrganizationBounties() call to return your mock bounty from the created mock organization.

Acceptance Criteria

- [ ] Test that I can view all the organizations I am a part of.
- [ ] Test that clicking on "manage" takes me to the organization admin page in the same window.
- [ ] Test that clicking on "View bounties" takes me to the organization overview page with a list of bounties if there are bounties.
- [ ] Test that if there are no bounties associated, the "View bounties" button should be greyed and unclickable.
- [ ] Test that I can click on "add organization" and a pop-up appears to guide through the add organization flow.
- [ ] Test that if there are no organizations, the "No organization yet" image is displayed.

### References
Jest Playlist:https://www.youtube.com/watch?v=Budumtq35Ls&list=PLC3y8-rFHvwirqe1KHFCHJ0RqNuN61SJd&index=2

**Comment by kevkevinpal** [comment]
I think the file to be tested isn't a spec file but the component file if you can change that

**Comment by Vayras** [comment]
> I think the file to be tested isn't a spec file but the component file if you can change that

Sure

**Comment by Vayras** [comment]
@kevkevinpal done

**Comment by arimusdev** [comment]
@ecurrencyhodler @Vayras  Is this one available? I want to take it

**Comment by ecurrencyhodler** [comment]
Okay give this one a shot!

**Comment by ecurrencyhodler** [comment]
Bounty has been assigned: https://community.sphinx.chat/bounty/1408

**Comment by arimusdev** [comment]
Thanks @ecurrencyhodler

**Comment by ecurrencyhodler** [comment]
Thanks for tracking this @Vayras!! But I like to close issues when I pay out bounties!
