### ISSUE TITLE
Display "mark as unpaid" immediately after a bounty is marked as paid

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes-frontend#127]
**Describe the bug**
After someone marks a bounty as paid, the button doesn't update:

https://www.loom.com/share/7463e0e578534c77b689c48d42b451b7

**Expected behavior**
The button should immediately update to "mark as unpaid".

**Desktop (please complete the following information):**
 - Browser: Chrome

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted vide in my PR
- [ ] I've created a test that asserts "mark as unpaid" is displayed when a bounty is marked as paid.

**Comment by ecurrencyhodler** [comment]
hello welcome! I have a few issues that are about to be posted. I'll get one of them for you.

**Comment by chiragDork** [comment]
Okay, thanks.

**Comment by ecurrencyhodler** [comment]
@chiragDork how about this one? https://community.sphinx.chat/bounty/1376

**Comment by chiragDork** [comment]
@ecurrencyhodler I can help with this, Please assign this to me

**Comment by chiragDork** [comment]
Hi @ecurrencyhodler my Sphinx connect code which I got in mail is not working, can you please assist me with that?

**Comment by ecurrencyhodler** [comment]
Hey @ChiragDork. Sorry about that. Try this one: 
connect::relay.swarm4.sphinx.chat::02cd45d2ec3a7196fc903619ab74a6237790e241e8de562e264d411556d9f15391

**Comment by chiragDork** [comment]
Hi @ecurrencyhodler it is working now, thanks

**Comment by ecurrencyhodler** [comment]
@ChetanKarwa do you have an update on this issue?

**Comment by ecurrencyhodler** [comment]
@ChetanKarwa can you get a PR up on this issue sometime today?

**Comment by MirzaHanan** [comment]
assign me

**Comment by ecurrencyhodler** [comment]
Let's get a PR up in 1-2 days.

**Comment by ecurrencyhodler** [comment]
@MirzaHanan do you have an update?

**Comment by MirzaHanan** [comment]
Hi @ecurrencyhodler,
I create a PR today.
