### ISSUE TITLE
[Tests][Component] Add tests to src/pages/people/tabs/Wanted.tsx

### ISSUE THREAD

**Issue by Vayras** [stakwork/sphinx-tribes-frontend#128]
### Context
`Wanted.tsx` Displays bounties created by the user

### File to be tested 
`src/pages/people/tabs/Wanted.tsx`

### File to be created
`src/pages/people/tabs/Wanted.Spec.tsx`

Make mock bounty data and return the mock bounties when Wanted.tsx makes a `main.getPersonCreatedBounties` call

### Acceptance Criteria
- [ ] Test that the page loads the correct number of user created bounties
- [ ] Test that each Individual bounty is visible
- [ ] Test that upon clicking on a bounty, the URL of the bounty should be in the 
        format :`https://community.sphinx.chat/bounty/###`.
- [ ] Test that correct bounty status is visible on each bounty such as 'unassigned', 'assigned', and 'paid'.
- [ ] Test that you are able to scroll down and view more bounties.
- [ ] Test that clicking on "post a bounty" button takes you through the bounty creation flow.
- [ ] Test that if no bounties have been posted, a message is displayed that says "No posted bounties yet".

### References
Jest Playlist:https://www.youtube.com/watch?v=T2sv8jXoP4s&list=PLC3y8-rFHvwirqe1KHFCHJ0RqNuN61SJd

**Comment by Fog3211** [comment]
@Vayras please assign me to this.

**Comment by vishnu552** [comment]
Assign

**Comment by ecurrencyhodler** [comment]
@vishnu552 do you have an update on this issue?

**Comment by vishnu552** [comment]
Hey @ecurrencyhodler , I had a very hard time setting up testing environment, after that I have been trying my level best to get this done give me this weekend to successfully complete both of my tickets.

**Comment by ecurrencyhodler** [comment]
Okay thanks for the update. Check out the playlist vayras provided. If you need help, reach out to the hunters tribe. People there will help you!

**Comment by vishnu552** [comment]
yes, @Fog3211 helped  me in testing setup.

**Comment by ecurrencyhodler** [comment]
Good news is that we will have lots more testing bounties. So if you get this set up for this one, you'll be well positioned to earn more testing bounties.

**Comment by MahtabBukhari** [comment]
@ecurrencyhodler Could you assigne me this one?

**Comment by ecurrencyhodler** [comment]
Here you go. Can you submit a PR in 1-2 days? https://community.sphinx.chat/bounty/1476
