### ISSUE TITLE
[Tests][Component] Add tests to src/people/widgetViews/UserTicketsView.tsx

### ISSUE THREAD

**Issue by Vayras** [stakwork/sphinx-tribes-frontend#129]
### Context
`UserTicketsView.tsx` Displays  bounties assigned to an user  

### File to be tested 
`src/people/widgetViews/UserTicketsView.tsx`

### File to create
`src/people/widgetViews/UserTicketsView.Spec.tsx`

create a mock user with mock bounties assigned to them and call `main.getPersonAssignedBounties` upon rendering `UserTicketsView.tsx` handle this from both signed in and signed out perspective

### Acceptance Criteria
- [ ] Test that the page loads the correct number of bounties assigned to the user 
- [ ] Test that each Individual bounty is visible
- [ ] Test that upon clicking on a bounty, the URL of the bounty should be in the 
        format :`https://community.sphinx.chat/bounty/###`.
- [ ] Test that correct bounty status is visible on each bounty such as 'assigned', and 'paid'.
- [ ] Test that you are able to scroll down and view more bounties.
- [ ] Test that if no bounties have been assigned, a message is displayed that says "No Assigned Tickets Yet".

### References
Jest Playlist: https://www.youtube.com/watch?v=T2sv8jXoP4s&list=PLC3y8-rFHvwirqe1KHFCHJ0RqNuN61SJd

**Comment by Fog3211** [comment]
@Vayras please assign me to this.

**Comment by MahtabBukhari** [comment]
@ecurrencyhodler @Vayras is this one available?

**Comment by ecurrencyhodler** [comment]
Yes. It's yours.

**Comment by ecurrencyhodler** [comment]
@MahtabBukhari do you have an update on this issue?

**Comment by Nightrider0098** [comment]
@ecurrencyhodler Can you assign me this?

**Comment by Nightrider0098** [comment]
https://github.com/stakwork/sphinx-tribes-frontend/pull/228
pr for the same
