### ISSUE TITLE
Clicking Estimate Session Length (text) doesnt open up dropdown

### ISSUE THREAD

**Issue by ChetanKarwa** [stakwork/sphinx-tribes-frontend#131]
**Describe the bug**
When clicking on Estimate Session Length (text) the dropdown doesn't open up (have to click on white space for it to work). The same is true with tribes.

https://www.loom.com/share/025756808504415faeef1bc5ed5e5eba

**Expected behavior**

When clicking on text, dropdown should appear

**Desktop (please complete the following information):**
 - Browser: Chrome

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a screenshot or video in my PR
- [ ] I have written a test that asserts that clicking Estimate Session Length (text) correctly opens the respective dropdown.
- [ ] I have written a test that asserts that clicking Tribes (text) correctly opens the respective dropdown.

**Comment by chiragDork** [comment]
@ecurrencyhodler assign this to me please

**Comment by ecurrencyhodler** [comment]
Hey Chirag. since you are a new contributor, I'm going to assign you one bounty to start. Will assign you more after that.

**Comment by ecurrencyhodler** [comment]
Woops sorry. Actually this one is yours.

**Comment by chiragDork** [comment]
Hi @ecurrencyhodler I have investigated the issue, working on the fix will open a PR soon.
