### ISSUE TITLE
When clicking on Deliverables (text) the input selected is of Price (Sats)*

### ISSUE THREAD

**Issue by ChetanKarwa** [stakwork/sphinx-tribes-frontend#132]
**Describe the bug**
When clicking on Deliverables (text) the input selected is of Price (Sats)*

https://www.loom.com/share/025756808504415faeef1bc5ed5e5eba

**Expected Behavior**
Input of deliverables is selected

**Desktop (please complete the following information):**
 - Browser: Chrome

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a screenshot or video in my PR
- [ ] I have written a test that asserts clicking Deliverables (text) selects the input for Deliverables.

**Comment by bilalshaikh292** [comment]
heyy @ChetanKarwa I have tested it on my end and it works properly.

**Comment by bilalshaikh292** [comment]
https://github.com/stakwork/sphinx-tribes-frontend/assets/110531971/096903fd-c674-4923-b304-7be9c1ba7232

**Comment by Abdul-rahman33** [comment]
Abdulrahman 👋, can you please assign ?

**Comment by ecurrencyhodler** [comment]
This is yours! 

Also just to set expectations: we want pr's within 1-3 days. Make sure to follow the acceptance criteria which includes a test. If I don't hear back within 7 days, we will unassign you. 

Let us know if you need anything else!

Also can you sign in here so I can assign the bounty to you? https://community.sphinx.chat/bounties

**Comment by Abdul-rahman33** [comment]
Alright thanks, I'll let you know if there's anything else. For now, I'm taking my time to understand the code base

**Comment by Abdul-rahman33** [comment]
Hi, I created a PR for this already https://github.com/stakwork/sphinx-tribes-frontend/pull/161
