### ISSUE TITLE
Incorrect check for enabling Next button

### ISSUE THREAD

**Issue by ChetanKarwa** [stakwork/sphinx-tribes-frontend#133]
**Describe the bug**
Next is blocked when Price (Sats)* is 0 initially, but if we write 0 intentionally the next is enabled (which should not be)

https://www.loom.com/share/025756808504415faeef1bc5ed5e5eba

**Expected Behavior**
Enable next when a value greater than 0 is entered

**Desktop (please complete the following information):**
 - Browser: Chrome

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a screenshot or video in my PR
- [ ] I have written a test that asserts Next is blocked even when input is 0

**Comment by Gaurav-Gaikwad-1** [comment]
@ecurrencyhodler Can you assign this to me?

**Comment by ecurrencyhodler** [comment]
@Gaurav-Gaikwad-1 do you have an update on this issue?

**Comment by ecurrencyhodler** [comment]
@Gaurav-Gaikwad-1 I will have to unassign if I don't hear back.

**Comment by Gaurav-Gaikwad-1** [comment]
@ecurrencyhodler I will submit PR by EOD 
Thanks!

**Comment by Gaurav-Gaikwad-1** [comment]
@ecurrencyhodler I have solved the bug but the test is quite complicated so I am trying so need time

**Comment by ecurrencyhodler** [comment]
okay thanks. I'll bump this to 100k sats.

**Comment by ecurrencyhodler** [comment]
Let's get a PR in ASAP thought.

**Comment by saithsab877** [comment]
assign me

**Comment by ecurrencyhodler** [comment]
Assigned! let's get a pr up in 1-2 days. Thanks.

**Comment by saithsab877** [comment]
Hi @ecurrencyhodler,
Please check the demo:
https://www.loom.com/share/4a672b24e4dd49d28e91fccd67da5938
I have resolved this issue, but writing unit tests is more complicated. If you don't mind, I will write a unit test for a function that only accepts numbers (=>1) and does not accept symbols, text, or any other values.

**Comment by ecurrencyhodler** [comment]
I'm okay with that test.

**Comment by ecurrencyhodler** [comment]
Paid 100k sats! https://community.sphinx.chat/bounty/1378
