### ISSUE TITLE
Fix the issue where the 'Send Tip Modal' `Close Button` is not visible to the user

### ISSUE THREAD

**Issue by aliraza556** [stakwork/sphinx-tribes-frontend#134]
**Describe the bug**

The 'Send Tip Modal' has a bug where its Close Button is not visible, hindering users from closing the modal easily.

https://www.loom.com/share/279937498daa410e9d77ac39f7c94250

**To Reproduce**
1. Go to 'People page'
2. Click on 'select any profile means people card'
3. Then click on 'Send Tip button'
4. Observe the error.

**Expected behavior**
When the 'Send Tip Modal' is triggered by clicking the 'Send Tip' button, the `Close Button` should be clearly visible and easily accessible to users. Users should be able to close the modal without any difficulty, ensuring a smooth and user-friendly experience.

**Desktop (please complete the following information):**
 - Browser [e.g. chrome]

### Acceptance Criteria
- [x] I have tested on Chrome desktop
- [x] I have posted a screenshot or video in my PR

**Comment by aliraza556** [comment]
@ecurrencyhodler could you look at this issue and assign to me?

**Comment by ecurrencyhodler** [comment]
Hey Ali! thanks for reporting. Closing the modal is easy enough by simply clicking out of it. I don't think we need this right now. Thanks.
