### ISSUE TITLE
Search is reset on people page when mouse is clicked outside of search box

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes-frontend#137]
**Describe the bug**
After a search term is typed and someone clicks outside of the search box, the search is reset.

https://jam.dev/c/6ef85216-a451-4e6d-a096-929d885c1c4d

**To Reproduce**

1. Open https://community.sphinx.chat/p
2. Focus search input
3. Type `ecu`
4. Can see search result
5. Blur focus from search input by clicking somewhere else
6. Search results are reset

**Expected behavior**
Search term and results should be preserved.

**Desktop (please complete the following information):**
 - Browser: Chrome

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a video in my PR
- [ ] I've created a test that clicking outside the search box doesn't reset search results

**Comment by YLeight** [comment]
Ping

**Comment by YLeight** [comment]
@elraphty @ecurrencyhodler [This](https://github.com/YLeight/sphinx-tribes-frontend/commit/cf9997ce319343af86e2e1cf902b844e78ce66b2#diff-035c66227ff9c0b4b1c690e921c7bb816eb92dbaca565f81ab7ba906bed613a8R55) code brokes the functionality

This reason, this one doen't work https://github.com/stakwork/sphinx-tribes-frontend/pull/7/files

**Comment by YLeight** [comment]
Can suggest to keep this functionality in `useEffect` on mount in `SearchTextInput` component
But it will reopen this one https://github.com/stakwork/sphinx-tribes/issues/1437
As search result from local storage based on search string from local storege, will be inconsistent

**Comment by YLeight** [comment]
Can suggest to fix previous one with phisical request on mount of people `Body` component
But seems to store search string in local storage is redundant, as this one can be fixed with suggestion above

**Comment by YLeight** [comment]
@elraphty @ecurrencyhodler Also this [test case](https://github.com/stakwork/sphinx-tribes-frontend/blob/master/src/people/main/__tests__/Body.spec.tsx#L12) looks fictional, as it relies on [container of loading state](https://github.com/stakwork/sphinx-tribes-frontend/blob/master/src/people/main/Body.tsx#L127)
If anybody style somehow [real container](https://github.com/stakwork/sphinx-tribes-frontend/blob/master/src/people/main/Body.tsx#L134) the test will pass, but the layout will broken

**Comment by YLeight** [comment]
Resetting searchText in ui store, trigger [this useEffect](https://github.com/stakwork/sphinx-tribes-frontend/blob/master/src/people/main/Body.tsx#L116), which request new data [with empty searchText](https://github.com/stakwork/sphinx-tribes-frontend/blob/master/src/store/main.ts#L729)

@ecurrencyhodler @elraphty If one from suggested refactor solutions are ok, I can contribute

**Comment by ecurrencyhodler** [comment]
@kevkevinpal can you take a look at these comments in the issue for search? Yegor is trying to figure out the best way to move forward and he is suggesting a refactor.
