### ISSUE TITLE
Mock user details to test edit profile

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes-frontend#140]
"Test cases would required me to wrap `AboutFocusView` That would require me to mock entire store."

This will enable the ability to test edit profile functionality.

_Originally posted by @Nightrider0098 in https://github.com/stakwork/sphinx-tribes-frontend/issues/101#issuecomment-1923998883_

**Comment by ecurrencyhodler** [comment]
@nightrider0098 can you comment here so I can assign it to you?

**Comment by Nightrider0098** [comment]
@ecurrencyhodler Sure thing.

**Comment by Nightrider0098** [comment]
#144 Should close this issue

**Comment by ecurrencyhodler** [comment]
Paid 200k sats! https://community.sphinx.chat/bounty/1381
