### ISSUE TITLE
Enable ability to edit org if website or github isn't provided

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes-frontend#143]
**Describe the bug**
I'm unable to edit and save an org if it doesn't have a website or github.

https://github.com/stakwork/sphinx-tribes-frontend/assets/32662508/3e079710-37f4-4b2b-a7af-66d0d608f110

**Expected behavior**
I should only be restricted from saving an org if the name is empty, org name is too long, or description is too long.

**Desktop (please complete the following information):**
 - Browser:Chrome

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a video in my PR
- [ ] I have created a test stating that the save button is enabled if name has a value and website, github, logo, and description are empty.

**Comment by VividhPandey003** [comment]
May I work on this?
