### ISSUE TITLE
Loading Wheel is displayed at the top-left corner

### ISSUE THREAD

**Issue by VividhPandey003** [stakwork/sphinx-tribes-frontend#145]
**Describe the bug**

https://github.com/stakwork/sphinx-tribes-frontend/assets/91251535/510ac828-6009-43a1-908e-0f73c6c69d98

**Expected behavior**

Loading wheel should appear in the middle like all other pages

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a video in my PR
- [ ] I've included a test to say that wheel is centered on the page

**Comment by VividhPandey003** [comment]
I would like to fix this

**Comment by aliraza556** [comment]
Hi @VividhPandey003,
Thank you for creating the issue, but it has already been reported and assigned:
#https://github.com/stakwork/sphinx-tribes-frontend/pull/109#issuecomment-1925150080

**Comment by VividhPandey003** [comment]
Yeah, Actually I'm coderturtle😅

**Comment by Ekep-Obasi** [comment]
@ecurrencyhodler Please assign me
