### ISSUE TITLE
Unnecessary Page Reload When Switching Users in React-Router Single-Page Application

### ISSUE THREAD

**Issue by Fog3211** [stakwork/sphinx-tribes-frontend#146]
**Describe the bug**
When switching users, the browser page will be reloaded, which means that HTML, js and other resources will be reloaded (which will reduce page render speed). In addition, the user list on the left will also be reloaded (unnecessary server requests). 

Also when clicking the "connect" button on the user list page, it would display the QR code modal but also navigate to the user details page.

https://github.com/stakwork/sphinx-tribes-frontend/assets/23151576/a191ba95-7291-49e3-91a3-b1aa25d0180f

**To Reproduce**
1.  Switch user in people page
2. Observe the loading status of the browser

https://github.com/stakwork/sphinx-tribes-frontend/assets/23151576/9be6285a-e387-4727-b8d3-d6bd6ba9c907

**Expected behavior**
Switching user pages should not trigger a browser reload

https://github.com/stakwork/sphinx-tribes-frontend/assets/23151576/f0f1604f-639c-4da7-ac3c-9bffeb7dd01a

**Desktop (please complete the following information):**
 - Browser Chrome 120

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted video in my PR
- [ ] I've created a test that asserts the page doesn't reload when switching profiles

**Comment by Fog3211** [comment]
@ecurrencyhodler I can fix it，could you please assign it to me？

**Comment by ecurrencyhodler** [comment]
This is a really nice fix and great for UX. thanks for reporting it. You can definitely take this.

**Comment by ecurrencyhodler** [comment]
https://community.sphinx.chat/bounty/1386

**Comment by ecurrencyhodler** [comment]
Added a test to the acceptance criteria.

**Comment by Fog3211** [comment]
sure , i will add a unit test :)

**Comment by Fog3211** [comment]
@ecurrencyhodler 
While fixing this issue, I discovered another bug. When clicking the "connect" button on the user list page, it would display the QR code modal but also navigate to the user details page. I have fixed both issues together.

https://github.com/stakwork/sphinx-tribes-frontend/assets/23151576/a191ba95-7291-49e3-91a3-b1aa25d0180f

**Comment by ecurrencyhodler** [comment]
okay thanks. I'll add an extra 100k sats
