### ISSUE TITLE
[Research] Close issue when bounty is paid

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes-frontend#147]
### Context
Let's close an issue that a bounty is tied to if it gets paid.

Here is the API doc's:
https://docs.github.com/en/rest/issues/issues?apiVersion=2022-11-28#update-an-issue

This will free up reviewers and the PM from manually closing issues after a PR gets merged and tested on staging. 

We need to include this call in the 2 ways a bounty can get paid:
1. Paid button through org
2. Mark as paid button

This is a feature that we will enable just for bounties platform, sphinx chat, and Secondbrain as v1. But we should architect this in such a way that any org can use it by enabling it from the org admin page:
<img width="1180" alt="Screenshot 2024-02-06 at 10 17 45 AM" src="https://github.com/stakwork/sphinx-tribes-frontend/assets/32662508/45d57140-4781-4810-b61e-96773ad0522d">

Two ways we've considered implementing this is:
1. Github api keys
2. [Authorizing github apps](https://docs.github.com/en/apps/using-github-apps/authorizing-github-apps)

### Acceptance Criteria
In the issue below:
- [ ] I've provided a list of pros and cons of both approach
- [ ] I've provided alternative solutions if relevant
- [ ] I've provided example projects who have implemented all explored solutions
- [ ] I've provided documentation for all explored solutions
- [ ] I've provided a recommended solution and why

**Comment by Ekep-Obasi** [comment]
@ecurrencyhodler I'll like to work on this when it is posted

**Comment by ecurrencyhodler** [comment]
@Ekep-Obasi go ahead. This is yours. Provide your research below on this issue. Lets get a response sometime today. Tomorrow at the latest.

**Comment by Ekep-Obasi** [comment]
# Implementing automated closing of issues tied to bounties upon payment.

@ecurrencyhodler This is what I compiled regarding the implementation of automated issue closure tied to bounties upon payment.

### Pros and Cons of Approaches:

| **Approach**            | **Pros**                                                | **Cons**                                                                  | **Costs**                                                                  |
|-------------------------|---------------------------------------------------------|---------------------------------------------------------------------------|----------------------------------------------------------------------------|
| **1. GitHub API Keys**  | -Simpler to implement              | - Requires handling sensitive information (API keys).                    | Generally, there are no direct costs associated with using GitHub API keys. |
|                         | - Straightforward authentication process.               | - Not scalable,  managing keys for multiple users can be cumbersome                  |                                                                            |
|                         | - Easy to manage access and permissions.               | - Limited to the capabilities of the GitHub REST                   |                                                                            |
|                         | - Well-documented API with extensive support.          |                                                                           |                                                                            |
|                         |                                                                                       |                                                                           |         |
| **2. Authorizing GitHub Apps** | - Better control over permissions and access with GitHub Apps. | - More complex setup and configuration compared to API keys.            | While there might not be direct costs for basic usage, depending on the scale and features required, there could be costs associated with hosting the GitHub App, particularly if additional infrastructure or services are needed. |
|                         | - More scalable - easier to manage access for multiple users. | - Requires understanding of OAuth and GitHub Apps infrastructure.        |                                                                            |
|                         | - Allows for granular permissions, enhancing security. |       |                                                                            |



### Documentation

| **Solution**                | **Documentation**                                                  |
|-----------------------------|--------------------------------------------------------------------|
| **GitHub API Keys**         |  [GitHub REST API Documentation](https://docs.github.com/en/rest) |
| **Authorizing GitHub Apps** |  [GitHub Apps Documentation](https://docs.github.com/en/developers/apps) |

### Example Projects:

| **Solution**                | **Project**                                                        |
|-----------------------------|--------------------------------------------------------------------|
| **GitHub API Keys**         | Auto-Close GitHub Action ([GitHub](https://github.com/actions/github-script)) |
| **GitHub Apps** | [Expensify](https://github.com/Expensify/App) |

### Recommendation:

Based on the trade-offs, I recommend using Github Apps. While it requires more upfront effort and is potentially more costly, it offers better security, scalability, and control in the long run. With GitHub Apps, we could also automate things like welcoming first-time users and a lot more capabilities. There are a couple of free open-source GitHub Apps that automate project management tasks on [GitHub Marketplace](https://github.com/marketplace/category/free). If we decide to build our own GithubApp we could use [Probot](https://github.com/probot/probot) which is a framework for building GitHub apps with Node.js. Here is a [tutorial](https://www.youtube.com/watch?v=23I7pzkSfyw) to build a deploy your GitHub app and host on [Platform.sh](https://platform.sh)

**Comment by ecurrencyhodler** [comment]
@Ekep-Obasi are you suggesting we create our own github app? Is there a free and open-source one we could use and simply integrate?

**Comment by Ekep-Obasi** [comment]
@ecurrencyhodler, I searched through the GitHub marketplace, I couldn't lay hands on an app that matches our specific requirements in terms of functionality, pricing, documentation, or webhook support.

**Comment by ecurrencyhodler** [comment]
Paid!

**Comment by Fog3211** [comment]
I found a competitor that we can emulate. Their bot can automatically sync an issue to the bounty platform when it is raised, and after the pull request is merged, it automatically closes the issue. 
Unfortunately, it is not open source.

<img width="1141" alt="image" src="https://github.com/stakwork/sphinx-tribes-frontend/assets/23151576/33f7543d-27bb-47c7-89b0-9a6e777fac0d">
<img width="1312" alt="image" src="https://github.com/stakwork/sphinx-tribes-frontend/assets/23151576/3ae27355-4c69-48d9-b877-b6e4a270d2c1">
<img width="1324" alt="image" src="https://github.com/stakwork/sphinx-tribes-frontend/assets/23151576/13537e1b-df19-4c86-8a12-6de9b518508f">


see here: https://github.com/dittofeed/dittofeed/issues/641
Their platform : https://console.algora.io/
