### ISSUE TITLE
Direct "# of developers" button to people page

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes-frontend#153]
### Context
Currently when you click on # of Developers on the home page, nothing happens. let's have it link to the people page.

https://www.loom.com/share/14d4a534aeac454caaa491d90618f070

### Acceptance Criteria
- [ ] I've tested on Chrome
- [ ] I've submitted a recording in my pr
- [ ] I've created a component test that asserts that if the # of developer button is clicked that it directs to the people page.

Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

**Comment by gouravmpk** [comment]
Assign

**Comment by Vayras** [comment]
@ecurrencyhodler can you assign this to me

**Comment by ecurrencyhodler** [comment]
Sorry @gouravmpk vayras reported this issue and asked to work on it.

**Comment by gouravmpk** [comment]
> Sorry @gouravmpk vayras reported this issue and asked to work on it.

No issues
