### ISSUE TITLE
Remove character restriction when editing a bounty

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes-frontend#156]
**Describe the bug**
Currently, I am restricted when editing a bounty by a character limit. This most likely due to abstraction issues between edit bounty and edit org modals.

https://github.com/stakwork/sphinx-tribes-frontend/assets/32662508/b0be0ff8-5309-41bd-8e09-4125e1f26288

**Expected behavior**
I should not have a restriction when editing a bounty.

**Desktop (please complete the following information):**
 - Browser: Chrome

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a video in my PR

**Comment by ecurrencyhodler** [comment]
Gourav you have several bounties open. Let's leave this for another hunter.

**Comment by vishnu552** [comment]
Can you  assign me?

**Comment by saithsab877** [comment]
assign me?

**Comment by Ekep-Obasi** [comment]
@ecurrencyhodler Can I work on this? 
I've only one open. The other 02 awaiting code reviews

**Comment by MahtabBukhari** [comment]
@ecurrencyhodler  could you assign me?

**Comment by ecurrencyhodler** [comment]
@saithsab877 welcome! How did you hear about our platform? Also are you on sphinx chat?

**Comment by saithsab877** [comment]
I was referred to this platform by @aliraza556.

**Comment by ecurrencyhodler** [comment]
Are you on sphinx chat? If not, follow our [FAQ](https://docs.google.com/document/d/16NQ4SM4ptP4Lz5JKERAagdNw3GFRVv9eshMZ_oU-MVw/edit?usp=sharing) to DL the app. Let me know if you need a sphinx code.

**Comment by saithsab877** [comment]
Hi @ecurrencyhodler,
I am currently not on Sphinx Chat.

**Comment by ecurrencyhodler** [comment]
Okay use this sphinx code to join:
connect::relay.swarm4.sphinx.chat::02c269aa8ac194ed66b92b5563c9f6d1b62decdad00c031a245d22fd30a29d6c4d

Then log-in here so I can assign the bounty to you: https://community.sphinx.chat/bounties

Then reply back with your sphinx alias

**Comment by saithsab877** [comment]
Hi @ecurrencyhodler,
this code worked and my sphinx name is Abubakar.

**Comment by saithsab877** [comment]
Thanks @ecurrencyhodler

**Comment by ecurrencyhodler** [comment]
Tested and paid out 50,000 sats. GJ! https://community.sphinx.chat/bounty/1409
