### ISSUE TITLE
Closing bounty on homepage redirects to org homepage

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes-frontend#158]
**Describe the bug**
Closing bounty on homepage redirects to org homepage. 

https://github.com/stakwork/sphinx-tribes-frontend/assets/32662508/976f6c60-9737-42c0-9126-9dabc4dde6e5

**Expected behavior**
When closing a bounty on the homepage, the homepage should appear. The same homepage state + location of where the person is viewing the bounty should also be preserved. 

**Desktop (please complete the following information):**
 - Browser: Chrome

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a video in my PR
- [ ] I have tested that the org homepage isn't affected
- [ ] I have created a test that states that when a bounty is closed, the previous state of the homepage is preserved and displayed.

Here is an [example unit test](https://github.com/stakwork/sphinx-tribes/blob/master/frontend/app/src/helpers/__test__/helpers.spec.ts)
Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

**Comment by HarshKalwani** [comment]
@ecurrencyhodler I wish to work on this, I was told about the bounties platform by @vayras

**Comment by ecurrencyhodler** [comment]
Hey Harsh! Are you on sphinx chat? That's how we pay the bitcoin bounties. Also how did you hear about our project?

**Comment by HarshKalwani** [comment]
> Hey Harsh! Are you on sphinx chat? That's how we pay the bitcoin bounties. Also how did you hear about our project?

@ecurrencyhodler not currently I'm not on sphinx chat, I was referred by @Vayras

**Comment by ecurrencyhodler** [comment]
Okay. Can you take this bounty?
https://community.sphinx.chat/bounty/1367

Follow our [FAQ](https://docs.google.com/document/d/16NQ4SM4ptP4Lz5JKERAagdNw3GFRVv9eshMZ_oU-MVw/edit?usp=sharing) to sign up. Here's a sphinx code to join:

Sign in [here](https://community.sphinx.chat/bounties) so I can assign the bounty to you then reply back with your sphinx alias.

**Comment by HarshKalwani** [comment]
hey @ecurrencyhodler , I have loggedin my username is harshkalwani on Sphinx and currently i would like to start with an easier issue as i am not familiar with testing as of now 
 thanks
