### ISSUE TITLE
[Tests][Component] Add tests to src/people/widgetViews/OrganizationDetails.tsx  Add Members Flow

### ISSUE THREAD

**Issue by Vayras** [stakwork/sphinx-tribes-frontend#163]
### Context
once a user successfully creates an organization it's details are provide by `OrganizationDetails.tsx`, test the add members flow 

### File to to test
`src/people/widgetViews/OrganizationDetails.tsx`

### File to create
`src/people/widgetViews/OrganizationDetails.spec.tsx`

### Acceptance Criteria
- [ ] Test that add user button shows add user modal
- [ ] Test that typing in a name filters people according to the search term
- [ ] Test that selecting a profile enables "add user" button
- [ ]  Test that add user button adds user as a member to org

### References
- Watch this [Jest Youtube playlist](https://www.youtube.com/watch?v=T2sv8jXoP4s&list=PLC3y8-rFHvwirqe1KHFCHJ0RqNuN61SJd) if you are new to testing
- Here is an [example unit test](https://github.com/stakwork/sphinx-tribes/blob/master/frontend/app/src/helpers/__test__/helpers.spec.ts)
- Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

**Comment by Fog3211** [comment]
@ecurrencyhodler  I want to work for this

**Comment by hritikmunde** [comment]
Assign

**Comment by ecurrencyhodler** [comment]
@hritikmunde do you have an update on this isue?

**Comment by hritikmunde** [comment]
working on it currently. Will update you once done

**Comment by Vayras** [comment]
@hritikmunde any updates for this one?

**Comment by hritikmunde** [comment]
One test is not working, finding a workaround.

**Comment by hritikmunde** [comment]
@ecurrencyhodler , can you give more time for this. This is taking a little bit longer.

**Comment by ecurrencyhodler** [comment]
Yes okay. I can thanks for the update. I'll give you 2 more days. I'll also increase the bounty 50K

**Comment by hritikmunde** [comment]
@Vayras , do you want me to add the tests to the existing file or create a new one? As the tests are lengthy I have created a new file but I can add to the existing one too. Your call

**Comment by Vayras** [comment]
@hritikmunde please add the test to `OrganizationDetails.spec.tsx` as it is the file concerned with testing the component

**Comment by hritikmunde** [comment]
Okay sure

**Comment by hritikmunde** [comment]
@Vayras , combining all the tests in one to ease the time spent. It'll work as expected but will take less time and avoid repeatative rendering

**Comment by Vayras** [comment]
@hritikmunde can you raise a PR and we can review that maybe?

**Comment by ecurrencyhodler** [comment]
Paid 250k sats! https://community.sphinx.chat/bounty/1423
