### ISSUE TITLE
[Tests][Component] Add tests to src/people/widgetViews/OrganizationDetails.tsx Deposit Button Flow

### ISSUE THREAD

**Issue by Vayras** [stakwork/sphinx-tribes-frontend#181]
### Context
once a user successfully creates an organization it's details are provide by `OrganizationDetails.tsx`, test the Deposit Button Flow

### File to to test
`src/people/widgetViews/OrganizationDetails.tsx`

### File to create
`src/people/widgetViews/OrganizationDetails.spec.tsx`

### Acceptance Criteria
- [ ] Test that Deposit modal is rendered
- [ ] Test that user can input an amount for sats
- [ ] Test that USD conversion are visible
- [ ] Test that generate invoice button creates an invoice
- [ ] Test that Invoice is displayed in a QR code 
- [ ] Test that copy button copies invoice

### References
- Watch this [Jest Youtube playlist](https://www.youtube.com/watch?v=T2sv8jXoP4s&list=PLC3y8-rFHvwirqe1KHFCHJ0RqNuN61SJd) if you are new to testing
- Here is an [example unit test](https://github.com/stakwork/sphinx-tribes/blob/master/frontend/app/src/helpers/__test__/helpers.spec.ts)
- Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

**Comment by okhot** [comment]
I'd love to work on this

**Comment by okhot** [comment]
3/6 test done.

**Comment by ecurrencyhodler** [comment]
Can we get a PR up sometime soon?

**Comment by okhot** [comment]
@ecurrencyhodler sorry for the delay I'm having a hard time getting some test to pass, but I'll get a PR up tomorrow evening. Sorry for the hold up

**Comment by ecurrencyhodler** [comment]
Thanks for the update. I'll increase this by 50k. Let's get it up Asap! Ty.

**Comment by okhot** [comment]
Yeah it's my first time writing test in production so it was a bit stressful at first but I'm getting a hold of it

**Comment by kevkevinpal** [comment]
closing as it seems the PR is merged
