### ISSUE TITLE
[Tests][Component] Add tests to src/people/widgetViews/OrganizationDetails.tsx Withdraw Button Flow

### ISSUE THREAD

**Issue by Vayras** [stakwork/sphinx-tribes-frontend#182]
### Context
once a user successfully creates an organization it's details are provide by `OrganizationDetails.tsx`, test the Withdraw Button Flow

### File to to test
`src/people/widgetViews/OrganizationDetails.tsx`

### File to create
`src/people/widgetViews/OrganizationDetails.spec.tsx`

### Acceptance Criteria
- [ ] Test that withdraw modal is rendered
- [ ] Test that user is able to post an invoice 
- [ ] Test invoice is correct
- [ ] Test that confirm pays the invoice
- [ ] Test that error message appears if insufficient funds to withdraw

### References
- Watch this [Jest Youtube playlist](https://www.youtube.com/watch?v=T2sv8jXoP4s&list=PLC3y8-rFHvwirqe1KHFCHJ0RqNuN61SJd) if you are new to testing
- Here is an [example unit test](https://github.com/stakwork/sphinx-tribes/blob/master/frontend/app/src/helpers/__test__/helpers.spec.ts)
- Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

**Comment by Abdul-rahman33** [comment]
I can help

**Comment by Vayras** [comment]
@Abdul-rahman33 have you got any updates for this?

**Comment by Abdul-rahman33** [comment]
I should have a PR by end of tomorrow

**Comment by VividhPandey003** [comment]
Can I work on this?

**Comment by MahtabBukhari** [comment]
@ecurrencyhodler could you assign me?

**Comment by olukade01** [comment]
Hi, can you assign this to me?

**Comment by ecurrencyhodler** [comment]
@olukade01 do you have an update on this issue?

**Comment by olukade01** [comment]
Just trying to wrap things up, I should raise a pr as soon as i do that

**Comment by ecurrencyhodler** [comment]
Okay if I don't see a PR by today I will have to unassign you.

**Comment by Fog3211** [comment]
I would like to help this If `olukade01` can't complete it.

**Comment by ecurrencyhodler** [comment]
@Fog3211 this is yours

**Comment by ecurrencyhodler** [comment]
Paid 200k sats! https://community.sphinx.chat/bounty/1433
