### ISSUE TITLE
[Metrics Status/Sort] Unit tests

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes-frontend#189]
Create a unit test for the bounties listed on the SuperAdmin page for the following areas listed below:

I should be able to view the bounties by the sort direction selected.
I should be able to view the bounties by the status selected.
I should be able to view the bounties by the default sort direction selection "newest" DESC

**Details** 

- Create a mock API call for ```metrics/bounties```, the mock data return should be sorted by descending order as default.
- When the sort order is changed the bounties should be sorted according to that either  by newest (DESC), or oldest (ASC) 
- When a status is selected Open/Paid/Assigned, only the tickets that match this status should be displayed

Use this PR as an example for testing [Unit Test PR](https://github.com/stakwork/sphinx-tribes/pull/940)

This is the second half for the issue: stakwork/sphinx-tribes#1012

### Acceptance criteria

- [ ] Unit test for getBountiesByRange in [main.ts](https://github.com/stakwork/sphinx-tribes/blob/38c8dd16d7ba6d3485f57db5dc60a4576ae03f92/frontend/app/src/store/main.ts)
- [ ] Run unit test with wrong data intentionally to see if it fails
- [ ] Run unit tests with right data to see if it passes

**Comment by Ekep-Obasi** [comment]
@ecurrencyhodler Could you please assign?

**Comment by ecurrencyhodler** [comment]
Hey @Ekep-Obasi you have 4 open bounties. Do you have PR's for them? Would be great to close some of those out before giving you another bounty.

**Comment by Ekep-Obasi** [comment]
@ecurrencyhodler, i have submitted PRs for 03 of them. Awaiting reviews

**Comment by ecurrencyhodler** [comment]
I took a look and am going to leave this one open. Let's get you another bounty when one of those closes.

**Comment by Ekep-Obasi** [comment]
@ecurrencyhodler alright, thank you

**Comment by AbdulWahab3181** [comment]
@ecurrencyhodler could you please assign me?

**Comment by ecurrencyhodler** [comment]
Ah good catch. Sorry for the duplicate ticket. This was an old one that I unblocked recently so didn't realize it.
