### ISSUE TITLE
[Tests][Component] Add tests to src/people/widgetViews/OrganizationDetails.tsx History Button Flow

### ISSUE THREAD

**Issue by Vayras** [stakwork/sphinx-tribes-frontend#193]
### Context
once a user successfully creates an organization it's details are provide by `OrganizationDetails.tsx`, test the history button flow 

### File to to test
`src/people/widgetViews/OrganizationDetails.tsx`

### File to create
`src/people/widgetViews/OrganizationDetails.spec.tsx`

### Acceptance Criteria
- [ ] Test that user is able to view payment history window including type, date, amount, sender, receiver, bounty, and three filters at the top: payment / deposit / withdrawals.
- [ ] Test that user is able to toggle payment / deposit / withdrawals
- [ ] Test that Click view bounty navigates to the correct bounty..

### References
- Watch this [Jest Youtube playlist](https://www.youtube.com/watch?v=T2sv8jXoP4s&list=PLC3y8-rFHvwirqe1KHFCHJ0RqNuN61SJd) if you are new to testing
- Here is an [example unit test](https://github.com/stakwork/sphinx-tribes/blob/master/frontend/app/src/helpers/__test__/helpers.spec.ts)
- Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

**Comment by turizspace** [comment]
assign me this one. :)

**Comment by ecurrencyhodler** [comment]
@turizspace do you have an update on this issue?

**Comment by turizspace** [comment]
yes . i am on this currently!

**Comment by ecurrencyhodler** [comment]
Can we get a pr in today?

**Comment by turizspace** [comment]
yes . Give me a few .

**Comment by NengakDakup** [comment]
@ecurrencyhodler any chance i take on this?
