### ISSUE TITLE
Disable bounty creation button upon initial click

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes-frontend#197]
**Describe the bug**
Tom S created a bounty and assigned a hunter during the bounty creation flow. This created duplicate bounties. I have tried duplicating but was not successful.

Here are the two bounties: 
https://community.sphinx.chat/bounty/1436
https://community.sphinx.chat/bounty/1437

**To Reproduce**
Create a bounty and assign fog321(in use) to it during bounty creation.

**Expected behavior**
Disable button once it's been clicked and wait for a response before it moves to a failure or success screen.

The success screen is the bounty page being opened and displayed.
Failure screen is being worked on here: https://github.com/stakwork/sphinx-tribes-frontend/pull/5
The button should also be re-enabled if failure state is achieved.

**Desktop (please complete the following information):**
 - Browser: Chrome

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a video in my pr
- [ ] I have created a test that the button becomes disabled on click
- [ ] I have rebased and tested locally before submitting my PR

Here is an [example unit test](https://github.com/stakwork/sphinx-tribes/blob/master/frontend/app/src/helpers/__test__/helpers.spec.ts)
Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

**Comment by gouravmpk** [comment]
assign

**Comment by Fog3211** [comment]
It seems that this issue occurs when the create button is rapidly clicked multiple times before the server returns a response.

https://github.com/stakwork/sphinx-tribes-frontend/assets/23151576/348ec4e7-2575-4b01-b31e-729bfb6ad3e6

**Comment by ecurrencyhodler** [comment]
Wow that's a really great find fog. I think then we need to restrict the finish button and wait for a return that the post has been successful. Let me chat with the team.

**Comment by ecurrencyhodler** [comment]
okay let's disable the button once it's been clicked once. Then wait for a response before moving to a success or failure screen. 

The success screen is the bounty page being opened and displayed. 
Failure screen is being worked on here: https://github.com/stakwork/sphinx-tribes-frontend/pull/5

I'm going to update this ticket to also include a test. Do you want this one @Fog3211 ?

**Comment by Fog3211** [comment]
> okay let's disable the button once it's been clicked once. Then wait for a response before moving to a success or failure screen.
> 
> The success screen is the bounty page being opened and displayed. Failure screen is being worked on here: #5
> 
> I'm going to update this ticket to also include a test. Do you want this one @Fog3211 ?

yes , i would like to do this

**Comment by ecurrencyhodler** [comment]
https://community.sphinx.chat/bounty/1457
