### ISSUE TITLE
Fix github text alignment when editing profile

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes-frontend#2]
<img width="442" alt="Screenshot 2024-01-23 at 1 25 28 PM" src="https://github.com/stakwork/sphinx-tribes-frontend/assets/32662508/58921ed8-f58f-4ffd-8e97-c660448ed8fd">

Alignment should match the text in lightning address

**Comment by AbdulWahab3181** [comment]
@ecurrencyhodler could you please assign me this task?

**Comment by ChetanKarwa** [comment]
I have fixed the issue and raised a PR please assign this to me

**Comment by ecurrencyhodler** [comment]
Hi @ChetanKarwa ! Thanks for contributing. Are you on sphinx? I can offer you a bitcoin bounty for this.

Also how did you hear about our project?

**Comment by ChetanKarwa** [comment]
Hey @ecurrencyhodler, I am not on sphinx as of now.
Would surely love to get Bitcoin bounty for this.
If that's the only source I would get on sphinx.

I came accross this project while I was looking for some bounties online.

**Comment by ecurrencyhodler** [comment]
Great! Was that on github? Or twitter?

Follow this [FAQ](https://docs.google.com/document/d/16NQ4SM4ptP4Lz5JKERAagdNw3GFRVv9eshMZ_oU-MVw/edit?usp=sharing) to sign up. Use this code to create an account and use this sphinx chat invitation code:
connect::relay.swarm4.sphinx.chat::02ce056494062ce991cc27b6a39b44d6b9f327b05c44f8b61b57318ea71fad0a33

And then reply back with your name.

**Comment by ChetanKarwa** [comment]
Hey @ecurrencyhodler , I have successfully created a profile and now I am on sphinx chat.
My name in that chat is: Chetan Karwa

**Comment by ecurrencyhodler** [comment]
Great. Can you sign into this website? https://community.sphinx.chat/bounties

**Comment by ecurrencyhodler** [comment]
Here is the bounty: https://community.sphinx.chat/bounty/1288
