### ISSUE TITLE
Show "0" value if % is too low instead of no value in superadmin

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes-frontend#208]
**Describe the bug**
On staging there is a really small (close to 0) value for % conversion of Sats paid to sats posted. This results in there a "0" value. However there is no 0 value being displayed next to "paid".
<img width="1205" alt="Screenshot 2024-02-08 at 2 51 31 PM" src="https://github.com/stakwork/sphinx-tribes-frontend/assets/32662508/4a28696b-2906-4a76-aa09-b203f5cb8a1a">

**Expected behavior**
Display a 0 value if the % is below 0.00% for "bounties -> completed" and "satoshis->paid"  section of the metrics dashboard.

**Desktop (please complete the following information):**
 - Browser: Chrome

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a screenshot in my PR
- [ ] I have created a test that shows a 0 value gets displayed when value is below 0.00%
- [ ] I have rebased and tested locally before submitting my PR

Here is an [example unit test](https://github.com/stakwork/sphinx-tribes/blob/master/frontend/app/src/helpers/__test__/helpers.spec.ts)
Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

**Comment by saithsab877** [comment]
Hi @ecurrencyhodler,
assign me

**Comment by saithsab877** [comment]
Thanks check it.
https://www.loom.com/share/0bdfe172b0aa473d976d75f0b6e26fc8

**Comment by ecurrencyhodler** [comment]
Can you show it on bounties section too?

**Comment by saithsab877** [comment]
If every thing is fine?

> Can you show it on bounties section too?

Bounties section mean this [section](https://i.imgur.com/RCZgSm7.png)

**Comment by ecurrencyhodler** [comment]
<img width="799" alt="Screenshot 2024-02-08 at 4 28 57 PM" src="https://github.com/stakwork/sphinx-tribes-frontend/assets/32662508/33d98305-8b9c-4be1-9d06-5fd5854e8947">

**Comment by saithsab877** [comment]
Hi @ecurrencyhodler,
Check https://www.loom.com/share/5887c6728c1242af9dc4c04304e5e7d5

**Comment by saithsab877** [comment]
> Nevermind. I see it in the video and missed it. Go ahead and submit a pr!

No problem, I'll get started on that pull request right away. Thanks for the clarification! I'll let you know once the PR is ready for review.
