### ISSUE TITLE
Align logo and org name horizontally if no website or github is provided

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes-frontend#209]
**Describe the bug**
Logo and org name are not aligned horizontally on the org homepage.

<img width="934" alt="Screenshot 2024-02-08 at 4 09 12 PM" src="https://github.com/stakwork/sphinx-tribes-frontend/assets/32662508/ad18ed89-be03-487e-9eee-166e1213ee6a">

**Expected behavior**
It should be aligned horizontally. Here is the design in [figma](https://www.figma.com/file/1aL3lgG5Rpkti4b0j42fwf/Bounties---FINAL-DESIGNS?type=design&node-id=10298%3A20431&mode=design&t=GONwSA2RekQz2CRG-1).

**Desktop (please complete the following information):**
 - Browser: Chrome

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a screnshot in my PR
- [ ] I have rebased and tested locally before submitting my PR

**Comment by saithsab877** [comment]
Hi @ecurrencyhodler,
assign me.

**Comment by MirzaHanan** [comment]
Hi @ecurrencyhodler,
assign me

**Comment by ecurrencyhodler** [comment]
This is yours mirza

**Comment by MirzaHanan** [comment]
Hi @ecurrencyhodler,
Could you please review this PR #222?

**Comment by ecurrencyhodler** [comment]
Paid 50000 sats! https://community.sphinx.chat/bounty/1449
