### ISSUE TITLE
Click resets search in people page

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes-frontend#217]
**Describe the bug**
When you type in a search on the people page and click anywhere on the site, the search resets.

https://github.com/stakwork/sphinx-tribes-frontend/assets/32662508/80bc6ab5-b9d2-4ac0-ad39-9d0afc812f24

**Expected behavior**
Click of a mouse should not reset the search.

**Desktop (please complete the following information):**
 - Browser: Chrome

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a video in my PR
- [ ] I have created a test that click does not reset search on people page
- [ ] I have rebased and tested locally before submitting my PR

Here is an [example unit test](https://github.com/stakwork/sphinx-tribes/blob/master/frontend/app/src/helpers/__test__/helpers.spec.ts)
Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

**Comment by ecurrencyhodler** [comment]
@YLeight do you want this bounty?

**Comment by HarshKalwani** [comment]
Please assign me this issue

**Comment by YLeight** [comment]
Duplicates https://github.com/stakwork/sphinx-tribes-frontend/issues/137

**Comment by YLeight** [comment]
Was fixed in https://github.com/stakwork/sphinx-tribes-frontend/pull/212
