### ISSUE TITLE
[Tests][Component] Add tests to src/people/widgetViews/summaries/wantedSummaries/CodingBounty.tsx 

### ISSUE THREAD

**Issue by Vayras** [stakwork/sphinx-tribes-frontend#219]
### Context
once a user successfully creates an bounty it's details are provide by `CodingBounty.tsx`

### File to to test
`src/people/widgetViews/summaries/wantedSummaries/CodingBounty`

### File to create
`src/people/widgetViews/summaries/wantedSummaries/__tests__/CodingBounty.spec.tsx`

### Acceptance Criteria
- [ ] Test that on clicking on "not assigned", a pop up should appear to invite a developer including "type to search" box, a"skills" box, and a recommendation of 5 hunters.
- [ ] Test that on clicking on the "type to search" box I should be able to type in any character and the list below should be filtered.
- [ ] Test that on clicking on the "skills" box I should be able to type in any character and the list below should be filtered.
- [ ] Test that on clicking on "invite" on a hunter, the pop up should clear and the hunter should be assigned to the bounty.
- [ ] I have rebased and tested locally before submitting my PR

### References
- Watch this [Jest Youtube playlist](https://www.youtube.com/watch?v=T2sv8jXoP4s&list=PLC3y8-rFHvwirqe1KHFCHJ0RqNuN61SJd) if you are new to testing
- Here is an [example unit test](https://github.com/stakwork/sphinx-tribes/blob/master/frontend/app/src/helpers/__test__/helpers.spec.ts)
- Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

**Comment by arimusdev** [comment]
@ecurrencyhodler  can you assign it to me?

**Comment by ecurrencyhodler** [comment]
Awesome. Let's try to get a pr in the next 1-2 days.

**Comment by arimusdev** [comment]
@Vayras I found that `"assign hunter"` button may not open the assign modal ,  Do you means "Not Assigned" button ?

![image](https://github.com/stakwork/sphinx-tribes-frontend/assets/143251520/b4d199cc-f904-4900-af01-4382c419908f)
<img width="1042" alt="image" src="https://github.com/stakwork/sphinx-tribes-frontend/assets/143251520/7bfd3c49-f761-4ebb-900c-a3ff602fcca9">

**Comment by Vayras** [comment]
@arimusdev yeah test for the not assigned , apologies for the typo

**Comment by arimusdev** [comment]
> @arimusdev yeah test for the not assigned , apologies for the typo

got it , thanks
