### ISSUE TITLE
Fix dropdowns when editing a profile so it fully cover the profile page.

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes-frontend#225]
**Describe the bug**
The dropdown when editing a profile doesn't fully cover the profile page.

https://www.loom.com/share/a99dc57dae2143aea750971cebde8b05?sid=65c4f4c1-43e8-41d4-a28e-b126da45ff78

**Expected behavior**
Dropdowns should fully cover text of areas of the profile it is covering. Resolve this issue by removing z-index from this modal and rendering attributes correctly.

**Desktop (please complete the following information):**
 - Browser: Chrome

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a video in my PR
- [ ] I have created a test to assert dropdowns cover the profile
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I have submitted a PR within 1 day of taking the bounty.

Here is an [example unit test](https://github.com/stakwork/sphinx-tribes/blob/master/frontend/app/src/helpers/__test__/helpers.spec.ts)
Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

**Comment by vishnu552** [comment]
Assign me

**Comment by Ekep-Obasi** [comment]
@ecurrencyhodler Could you please assign this to me?

**Comment by ecurrencyhodler** [comment]
Let's get a pr up in 2 days

**Comment by ecurrencyhodler** [comment]
Great job. Paid 200k sats! https://community.sphinx.chat/bounty/1597
