### ISSUE TITLE
Wrap text for bounty titles

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes-frontend#226]
**Describe the bug**
When there is a long string of text for the bounty title page with no space  breaks, it breaks the design. 
<img width="955" alt="Screenshot 2024-02-12 at 9 50 34 AM" src="https://github.com/stakwork/sphinx-tribes-frontend/assets/32662508/54e1e7df-1326-46b8-a440-4ab778b242ed">
<img width="924" alt="Screenshot 2024-02-12 at 9 50 29 AM" src="https://github.com/stakwork/sphinx-tribes-frontend/assets/32662508/c42dfa4f-bc3b-4de2-8fe9-8985ab7e9f65">

**Expected behavior**
Let's wrap the text. 

**Desktop (please complete the following information):**
 - Browser: Chrome

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a video in my PR
- [ ] I have created a test that asserts the text wraps
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I have submitted a pr within 2 days of taking the bounty

Here is an [example unit test](https://github.com/stakwork/sphinx-tribes/blob/master/frontend/app/src/helpers/__test__/helpers.spec.ts)
Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

**Comment by gouravmpk** [comment]
Assign

**Comment by MahtabBukhari** [comment]
@ecurrencyhodler could you assign me

**Comment by ecurrencyhodler** [comment]
@gouravmpk this is yours
