### ISSUE TITLE
[Tests][Component] Add tests to frontend/app/src/pages/tickets/TicketModalPage.tsx  View Bounty For Signed in Hunter

### ISSUE THREAD

**Issue by Vayras** [stakwork/sphinx-tribes-frontend#229]
### Context
TicketModalPage.tsx Displays a single bounty in a modal. Add component test coverage for viewing a bounty for a signed in Hunter.

### File to test
`src/pages/tickets/__tests__/TicketModalPage.tsx`

### File to create
`src/pages/tickets/__tests__/TicketModalPage.spec.tsx`

### Acceptance Criteria
- [ ] Test that the TicketModalPage is rendered when the URL {host}/bounty/{bountyId} is hit
- [ ] Test that user should be able to exit the bounty modal by clicking the "x" on the top right 
- [ ] Test that the bounty poster, title of bounty, Sat amount/usd conversion, est. hours, are all rendered and clickable.
- [ ] Test that if  a hunter is not assigned, there should be a clickable button "I can help" and an empty profile image.
- [ ] Test that on clicking on "I can help", a Discuss with Bounty Provider pop up should appear including a QR code, button to copy pub key, and connect with sphinx button.
- [ ] I have rebased and tested locally before submitting my PR

### References
- Watch this [Jest Youtube playlist](https://www.youtube.com/watch?v=T2sv8jXoP4s&list=PLC3y8-rFHvwirqe1KHFCHJ0RqNuN61SJd) if you are new to testing
- Here is an [example unit test](https://github.com/stakwork/sphinx-tribes/blob/master/frontend/app/src/helpers/__test__/helpers.spec.ts)
- Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

**Comment by NengakDakup** [comment]
@ecurrencyhodler can i try this?

**Comment by ecurrencyhodler** [comment]
@NengakDakup is this someting you can submit a PR for by tomorrow?

**Comment by NengakDakup** [comment]
> @NengakDakup is this someting you can submit a PR for by tomorrow?

Yeah man. Can get it done😁

**Comment by NengakDakup** [comment]
Hi @ecurrencyhodler so i noticed some issues.
When i'm in /org/bounties/xxxx and I click on a bounty and the modal pops up, then click on i can help, the modal doesn't come up, it just returns me to /org/bounties/xxx.
But it works when i am on /bounties, but when i click the i can help button, the bounty page does not persist, but the test says it should.

Please let me know if you can reproduce these errors.

**Comment by ecurrencyhodler** [comment]
Wow great find. Yes I am able to reproduce. I will create an issue and bounty for this. We can remove that from the acceptance criteria and add it as one to the bounty I'm going to create. So keep pushing forward.

**Comment by NengakDakup** [comment]
Okay then man. Great!
