### ISSUE TITLE
Enable homepage bounties search to include filters

### ISSUE THREAD

**Issue by AbdulWahab3181** [stakwork/sphinx-tribes-frontend#231]
**Describe the bug**
When we search for something on the bounties page while selecting a status, the search results show the results of other statuses, which is incorrect. It should show the search results of the selected status.

**Bug Demo**
https://www.loom.com/share/f40e0b0a7ac14415957e984119739752?sid=2339a0fd-cbc8-4838-870e-922e406ba030

**To Reproduce**
1. Go to https://community.sphinx.chat/bounties page.
2. Select the status as open.
3. In the search bar, write "graphic" and hit enter.
4. Observe that the response has assigned bounties, which is incorrect.

**Expected behavior**
1. Go to https://community.sphinx.chat/bounties page.
2. Select the status as open.
3. In the search bar, write "graphic" and hit enter.
4. The response should have open bounties.

**Desktop (please complete the following information):**
 - Browser: Chrome

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a screenshot or video in my PR
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I have created a test that asserts that the results of a search includes the chosen filters on the home page including status and skills

Here is an [example unit test](https://github.com/stakwork/sphinx-tribes/blob/master/frontend/app/src/helpers/__test__/helpers.spec.ts)
Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

**Comment by AbdulWahab3181** [comment]
@ecurrencyhodler could you please review and assign me the issue?

**Comment by NengakDakup** [comment]
Hi @ecurrencyhodler can i take this?

**Comment by ecurrencyhodler** [comment]
@AbdulWahab3181 created a bounty and assigned: https://community.sphinx.chat/bounty/1477

Can you submit a PR in 1-2 days?

**Comment by AbdulWahab3181** [comment]
> @AbdulWahab3181 created a bounty and assigned: https://community.sphinx.chat/bounty/1477
> 
> Can you submit a PR in 1-2 days?

Thanks, Yes I will submit a PR in 1-2 days
