### ISSUE TITLE
[Tests][Component] Add tests to src/pages/superadmin/tableComponent/index.tsx Table Component for Superadmin

### ISSUE THREAD

**Issue by Vayras** [stakwork/sphinx-tribes-frontend#232]
### Context
`index.tsx` loads the available bounties in a table format, enhance the test coverage

### File to to test
`src/pages/superadmin/tableComponent/index.tsx`

### File to create
`src/pages/superadmin/tableComponent/__tests__/TableComponent.spec.tsx`

### Acceptance Criteria
- [ ] Test That if user is admin he can see the admin page else show the access denied component
- [ ] Test that sort by filter, sorts the bounties according to admin selection
- [ ] Test that  bounties are filtered by status selected, `open` , `assigned` , `paid` .  
- [ ] I have rebased and tested locally before submitting my PR

### References
- Watch this [Jest Youtube playlist](https://www.youtube.com/watch?v=T2sv8jXoP4s&list=PLC3y8-rFHvwirqe1KHFCHJ0RqNuN61SJd) if you are new to testing
- Here is an [example unit test](https://github.com/stakwork/sphinx-tribes/blob/master/frontend/app/src/helpers/__test__/helpers.spec.ts)
- Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

**Comment by ecurrencyhodler** [comment]
Okay let's get a PR up in 1-2 days
