### ISSUE TITLE
[Tests][Component] Add tests to src/people/widgetViews/summaries/wantedSummaries/CodingBounty.tsx Bounty Payout

### ISSUE THREAD

**Issue by Vayras** [stakwork/sphinx-tribes-frontend#242]
### Context
Mark as paid button on `CodingBounty.tsx` handles the bounty payout's

### File to to test
`src/people/widgetViews/summaries/wantedSummaries/CodingBounty.tsx`

### File to create
`src/people/widgetViews/summaries/wantedSummaries/__tests__/CodingBounty.spec.tsx`

### Acceptance Criteria
- [ ] Test that clicking on  "mark as paid" button, renders: adjust amount , assignee name, amount set in Sats and next button
- [ ] Test that increment and decrement button on input field for amount works correctly
- [ ] Test that clicking on next button takes you to  `Award Badge` section assert all the necessary ui elements
- [ ] Test that button state and text changes according to selection in `Award Badge` Section
- [ ] Test that the Mark as Paid button changes the bounty paid state if the bounty is marked as paid successfully.
- [ ] I have rebased and tested locally before submitting my PR

### References
- Watch this [Jest Youtube playlist](https://www.youtube.com/watch?v=T2sv8jXoP4s&list=PLC3y8-rFHvwirqe1KHFCHJ0RqNuN61SJd) if you are new to testing
- Here is an [example unit test](https://github.com/stakwork/sphinx-tribes/blob/master/frontend/app/src/helpers/__test__/helpers.spec.ts)
- Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

**Comment by okhot** [comment]
Can I work on this? 🙏🏽

**Comment by Vayras** [comment]
@okhot let's wait for @ecurrencyhodler to approve and post this first

**Comment by okhot** [comment]
Okay thanks

**Comment by ecurrencyhodler** [comment]
It's yours. Let's get a PR up in 2 days!

**Comment by okhot** [comment]
Thanks @ecurrencyhodler on it 🙏🏽

**Comment by ecurrencyhodler** [comment]
Paid 200k! https://community.sphinx.chat/bounty/1490
