### ISSUE TITLE
Wrap text of bounty titles in superadmin

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes-frontend#246]
**Describe the bug**
Currently, the text of a long bounty doesn't wrap if there are no spaces.

**Expected behavior**
Default column width should be preserved and text should wrap. That means the height of the bounty will expand rather than the width.

**Desktop (please complete the following information):**
 - Browser: Chrome

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a screenshot or video in my PR
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I will submit a PR within 2 days of taking the bounty
- [ ] I will write a test asserting text wraps 

Here is an [example unit test](https://github.com/stakwork/sphinx-tribes/blob/master/frontend/app/src/helpers/__test__/helpers.spec.ts)
Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

**Comment by gouravmpk** [comment]
Assign

**Comment by ecurrencyhodler** [comment]
Hey @okhot this goes to @gouravmpk since he raised the issue.

**Comment by ecurrencyhodler** [comment]
Closed by #235

**Comment by gouravmpk** [comment]
@ecurrencyhodler this gets covered in the same PR

**Comment by ecurrencyhodler** [comment]
yeah that's why I reopened it!
