### ISSUE TITLE
Add dynamic bounty count to org homepage

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes-frontend#248]
### Context
Right now, the # of bounties doesn't change based on the filters.

https://github.com/stakwork/sphinx-tribes-frontend/assets/32662508/260572f1-ca29-4fea-bee0-c3c160ea9acc

### Design
The # should dynamically changed based on the # of bounties displayed

### Acceptance Criteria
- [ ] I've tested on Chrome
- [ ] I've submitted a screenshot or recording in my pr
- [ ] I've created a test that asserts the correct # gets displayed based on the # of bounties called
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a pr within 2 days of taking the bounty

Here is an [example unit test](https://github.com/stakwork/sphinx-tribes/blob/master/frontend/app/src/helpers/__test__/helpers.spec.ts)

Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

**Comment by ecurrencyhodler** [comment]
Thanks Zoe. I will scope it with the team and then get back to you.

**Comment by MahtabBukhari** [comment]
@ecurrencyhodler I am also available for this task.

**Comment by HarshKalwani** [comment]
@ecurrencyhodler  can you please assign me this issue if this issue is open

**Comment by AbdulWahab3181** [comment]
@ecurrencyhodler could you please assign me I already did same work for admin bounties

**Comment by ecurrencyhodler** [comment]
This is blocked by a backend issue.

**Comment by MirzaHanan** [comment]
Hi @ecurrencyhodler,
Assign me

**Comment by FaisalIqbal211** [comment]
@ecurrencyhodler assign me?

**Comment by MuhammadUmer44** [comment]
Hi @ecurrencyhodler,
Could you assign to me?

**Comment by ecurrencyhodler** [comment]
Closed by #304
