### ISSUE TITLE
Display dropdown when "category" in bounty creation modal is clicked

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes-frontend#250]
**Describe the bug**
Right now, clicking on "category" doesn't trigger the dropdown menu. 

https://github.com/stakwork/sphinx-tribes-frontend/assets/32662508/1be78178-9ee0-4bde-b70b-60b378a6447c

**Expected behavior**
Clicking on the text should enable the dropdown menu

**Desktop (please complete the following information):**
 - Browser: Chrome

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a screenshot or video in my PR
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 2 days of taking the bounty
- [ ] I have created a test that the dropdown is initialized when the entire section inside the rectangle is clicked

Here is an [example unit test](https://github.com/stakwork/sphinx-tribes/blob/master/frontend/app/src/helpers/__test__/helpers.spec.ts)
Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

**Comment by ecurrencyhodler** [comment]
Sure. Make sure to get a PR up within 2 days!

**Comment by ecurrencyhodler** [comment]
Welcome @FaisalIqbal211 I'd be happy to. This issue is also available for a bounty. Are you on sphinx chat? It's how we pay out bounties.

**Comment by FaisalIqbal211** [comment]
Thanks, No I am not sphinx chat

**Comment by ecurrencyhodler** [comment]
Okay. Download our sphinx chat. Here are the steps in our [FAQ](https://docs.google.com/document/d/16NQ4SM4ptP4Lz5JKERAagdNw3GFRVv9eshMZ_oU-MVw/edit?usp=sharing). 

Here is your connection code:
connect::relay.swarm4.sphinx.chat::02e951abc2dea07302fb3a7d7e78e601430d9fa44b0b8d54a0af81f893304d8090


BTW how did you hear about our project?

**Comment by FaisalIqbal211** [comment]
Thanks. @AbdulWahab3181 referred me.

**Comment by ecurrencyhodler** [comment]
Awesome. Reply back with your sphinx name, sign in here: https://community.sphinx.chat/bounties, and i'll assign the bounty to you.

**Comment by aliraza556** [comment]
Hi @ecurrencyhodler, Could you assign to me?

**Comment by FaisalIqbal211** [comment]
> Awesome. Reply back with your sphinx name, sign in here: https://community.sphinx.chat/bounties, and i'll assign the bounty to you.

Faisal Iqbal is my sphinx name.
