### ISSUE TITLE
Display qr code of provider when I click "I can help" when viewing bounty from org homepage

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes-frontend#253]
**Describe the bug**
When I go to an org homepage, click on a bounty, and click "i can help", the window automatically closes.

https://github.com/stakwork/sphinx-tribes-frontend/assets/32662508/f3b76daf-5fe9-4193-a6de-53d1247d914b

**Expected behavior**
The QR code of the provider should display. It should look like this:
<img width="1074" alt="Screenshot 2024-02-15 at 9 33 32 AM" src="https://github.com/stakwork/sphinx-tribes-frontend/assets/32662508/afd70429-249f-4034-979b-261b18a34605">

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a screenshot or video in my PR
- [ ] I have created a test that on clicking on "I can help" when bounty page is open, the modal to connect should appear
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 2 days of taking the bounty

Here is an [example unit test](https://github.com/stakwork/sphinx-tribes/blob/master/frontend/app/src/helpers/__test__/helpers.spec.ts)
Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

**Comment by ColdMice** [comment]
@ecurrencyhodler Can you assign this one to me?

**Comment by AbdulWahab3181** [comment]
@ecurrencyhodler could you please assign me

**Comment by aliraza556** [comment]
@ecurrencyhodler assign me?

**Comment by ecurrencyhodler** [comment]
Welcome back @ColdMice this is yours.

**Comment by ColdMice** [comment]
<img width="1440" alt="Screenshot 2024-02-16 at 12 33 56 PM" src="https://github.com/stakwork/sphinx-tribes-frontend/assets/157780212/bfb1f44e-22e7-4d9d-9f7c-0bd147ee9a3a">
Noticed a Strange behaviour with goBack() function if I  comment it I can see the qr for org bounties else It just goes back to org bounties with no qr

**Comment by ColdMice** [comment]
The problem seems to be the url it navigates to like if we goBack() => `/bounties` we see qr , while not visible if goBack() => `/org/bounites/orguuid`

**Comment by ecurrencyhodler** [comment]
Okay that's a good find. Can you put in a fix Coldmice and remove that behavior?

**Comment by ColdMice** [comment]
@ecurrencyhodler working on that boss, will raise a PR soon
