### ISSUE TITLE
[Tests][Component] Add tests to src/components/form/bounty/index.tsx

### ISSUE THREAD

**Issue by Vayras** [stakwork/sphinx-tribes-frontend#254]
### Context
`src/components/form/bounty/index.tsx` allows users to post a bounty add the following test for amount set for a bounty

### File to to test
`src/components/form/bounty/index.tsx`

### File to create
src/components/form/bounty/bountyCreation_spec.tsx

### Acceptance Criteria
- [ ] Test That  placeholder text for 0 sats is visible for amount input box
- [ ] Test That next button is disable if amount is set to zero, Assert we did not proceed to next page of form
- [ ] Test That changing amount upwards of zero, next button is enabled and changing it back to zero disable the next button
- [ ] Test that only values for amount upwards of zero takes you to next page of form
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a pr within 2 days of taking the bounty

### References
- Watch this [Jest Youtube playlist](https://www.youtube.com/watch?v=T2sv8jXoP4s&list=PLC3y8-rFHvwirqe1KHFCHJ0RqNuN61SJd) if you are new to testing
- Here is an [example unit test](https://github.com/stakwork/sphinx-tribes/blob/master/frontend/app/src/helpers/__test__/helpers.spec.ts)
- Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

**Comment by Khaalid-oh** [comment]
Can you assign this?

**Comment by MahtabBukhari** [comment]
@ecurrencyhodler could you assign to me?

**Comment by MirzaHanan** [comment]
Hi @ecurrencyhodler, Could you assign to me?

**Comment by ecurrencyhodler** [comment]
Let's get a PR in 2 days!

**Comment by MirzaHanan** [comment]
> Let's get a PR in 2 days!
Hi @ecurrencyhodler
Please review this PR #282
