### ISSUE TITLE
Bounty creation modal is not appearing

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes-frontend#258]
**Describe the bug**
Bounty creation modal is not appearing when I click on "post a bounty" on the home page.

https://github.com/stakwork/sphinx-tribes-frontend/assets/32662508/13d9f960-bd91-49ae-8ad1-29313a05e2cd

**Expected behavior**
The bounty creation modal should appear.

**Desktop (please complete the following information):**
 - Browser: Chrome

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a screenshot or video in my PR
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 2 days of taking the bounty

Here is an [example unit test](https://github.com/stakwork/sphinx-tribes/blob/master/frontend/app/src/helpers/__test__/helpers.spec.ts)
Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

**Comment by Vayras** [comment]
If I go directly to the `people-test.sphinx.chat` I can reproduce this but the same wont happen If I run the site locally with host.ts connecting to `people-test.sphinx.chat`

**Comment by ecurrencyhodler** [comment]
This was introduced in this PR: #255 

What's strange is that this can't be reproduced locally which is probably why it also passed the cypress E2E test which covers this scenario.

**Comment by Vayras** [comment]
@ecurrencyhodler really strange, what other checks can be implemented to avoid this

**Comment by ecurrencyhodler** [comment]
I think we need to find the root cause before figuring that out.
