### ISSUE TITLE
[Bounty Modal] After paying a bounty with an org I expect the button on the bottom right to say "Mark as Unpaid"

### ISSUE THREAD

**Issue by kevkevinpal** [stakwork/sphinx-tribes-frontend#265]
**Describe the bug**
![Screenshot 2024-02-16 at 4 46 58 PM](https://github.com/stakwork/sphinx-tribes-frontend/assets/15950706/d629e842-88bf-4147-b726-ba8c619adde6)

**To Reproduce**
Create bounty with org
attempt to pay from main bounty screen modal
observe the words

**Expected behavior**
Should say Mark as Unpaid

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a screenshot or video in my PR
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 2 days of taking the bounty
- [ ] Create a e2e test that asserts the words "Mark as Unpaid appear" after paying bounty

**Comment by okhot** [comment]
@kevkevinpal i can help with this

**Comment by ecurrencyhodler** [comment]
@kevkevinpal did you test this on prod? 

I see this on staging.
<img width="899" alt="Screenshot 2024-02-16 at 7 54 57 PM" src="https://github.com/stakwork/sphinx-tribes-frontend/assets/32662508/3761eced-bebe-482b-97ec-4b1e8f7dc45b">

**Comment by aliraza556** [comment]
HI @kevkevinpal, @ecurrencyhodler,
This issue is fixed I review this PR 
https://github.com/stakwork/sphinx-tribes-frontend/pull/252
