### ISSUE TITLE
Prevent spaces in bounty title, bounty description, and acceptance criteria during bounty creation

### ISSUE THREAD

**Issue by aliraza556** [stakwork/sphinx-tribes-frontend#266]
**Describe the bug**
A user is able to create a bounty with spaces inside of a bounty title, description, and acceptance criteria. The next button is also enabled when someone types in a space during Step 2 when a title is filled with a space.

**Demo**
https://www.loom.com/share/f592786c5e3f40ed9973ba3f8a885b2e

**Expected behavior**
1. If a space is entered in the bounty title by itself, it is not registered.
2. If a space is entered in the description by itself, it is not registered.
3. If a space is entered in the acceptance criteria by itself, it is not registered.
4. Unnecessary spaces should be trimmed at the beginning and end of the title description, bounty description, and acceptance criteria if there is a text
5. The "Next" button should only be enabled the bounty title is validly filled i.e. no fields with just spaces
https://www.loom.com/share/3232d8abc05049ffb4e2a4701a15696b

**Desktop (please complete the following information):**
 - Browser: Chrome

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a screenshot or video in my PR
- [ ] I have created a test asserting that nothing happens if a space is entered in title, description, and acceptance criteria
- [ ] I have created a test only spaces are trimmedin the bounty title, description, and acceptance criteria
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 2 days of taking the bounty

**Comment by aliraza556** [comment]
Hi @ecurrencyhodler,
Please assign me

**Comment by ecurrencyhodler** [comment]
@aliraza556 are you saying that you want to disable the "next" button on step #2 if they add a space in the title?

**Comment by aliraza556** [comment]
> @aliraza556 are you saying that you want to disable the "next" button on step #2 if they add a space in the title?

Yes

**Comment by aliraza556** [comment]
Hi @ecurrencyhodler
If the bounty title contains white spaces, then the bounty display appears as follows:
https://i.imgur.com/5ue4oJH.png

**Comment by aliraza556** [comment]
@ecurrencyhodler,
In short
https://www.loom.com/share/e2d6381155604e2a942e1d8b76ef34da

**Comment by aliraza556** [comment]
@ecurrencyhodler
Bug Demo:
https://www.loom.com/share/f592786c5e3f40ed9973ba3f8a885b2e

Expected Behavior:
https://www.loom.com/share/3232d8abc05049ffb4e2a4701a15696b

Please check it.

**Comment by ecurrencyhodler** [comment]
Hmmm I'm not sure how I feel about preventing spaces. Let me talk to my designer about this.

**Comment by aliraza556** [comment]
Sure, I understand your concerns about preventing spaces and the importance of discussing it with your designer. In the meantime, I have a related question: Why is the Next button disabled? If the Bounty title (Step 2) and description (Step 3) are not mandatory for our process, could we consider removing the functionality that disables the Next button?

**Comment by aliraza556** [comment]
Hi @ecurrencyhodler,
Please review this PR #283
