### ISSUE TITLE
Organization Creation Allows Missing Name and Fields Contain Extra Whitespace

### ISSUE THREAD

**Issue by aliraza556** [stakwork/sphinx-tribes-frontend#267]
**Describe the bug**
The organization was created without a name, and some fields contain unnecessary whitespaces.

**Demo**
https://www.loom.com/share/22f77023d4fa46f6a08234e0c65ef028

**Expected behavior**
If a space is entered in the org name by itself, it is not registered.
An org can only be created if there is a text character in the name. In other words, an org name with only spaces shouldn't be created.
This functionality is for creating and also editing an org.

**Desktop (please complete the following information):**
 - Browser: Chrome

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a screenshot or video in my PR
- [ ] I have created a test asserting that nothing happens if a space is entered in the org name
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 2 days of taking the bounty

**Comment by aliraza556** [comment]
Hi @ecurrencyhodler
Assign me

**Comment by aliraza556** [comment]
Hi @ecurrencyhodler
Expected behavior:
https://www.loom.com/share/8f5e5c25adcc47699b4d960f47e71106

**Comment by ecurrencyhodler** [comment]
Let's get a PR up within 2 days. I've removed trimming spaces and will create a backend issue for that. Make sure to review the updated ticket!

**Comment by aliraza556** [comment]
Hi @ecurrencyhodler,
I have found a new bug; please check it.
https://www.loom.com/share/556b3f994a334850bb43dc3123784b85

But I have fixed it:
https://www.loom.com/share/0b807b7b99c542c38b4527be84d2aaf7

Please review the above demonstrations.

**Comment by ecurrencyhodler** [comment]
Okay this is a great find. Let me create an issue/bounty for you.
