### ISSUE TITLE
Convert the ElasticUi input box to Custom Components 

### ISSUE THREAD

**Issue by Vayras** [stakwork/sphinx-tribes-frontend#272]
### Context
So the problem is the current Implementation of the the dropdown on the site is too abstracted, is not very efficient, and does not behave how a dropdown should actually behave. 

We currently use elastic ui Super Select:
<img width="341" alt="Screenshot 2024-02-19 at 1 40 46 AM" src="https://github.com/stakwork/sphinx-tribes-frontend/assets/89837102/3837f1be-0186-40be-82f3-5f804508c030">

### Design
To solve a lot of UI problems as discussed with the core team [@ecurrencyhodler @kevkevinpal @elraphty] we are now slowly moving towards our own custom components.

This will also solve #106

**Comment by ecurrencyhodler** [comment]
Thanks @Vayras for reporting this. I'm going to lump this in with #106. I've updated the ticket. I'll also increase the bounty because of the research and extra work it'll take to create a custom component.
