### ISSUE TITLE
[Tests][Component] Add tests to src/pages/tribes/Body.tsx

### ISSUE THREAD

**Issue by Vayras** [stakwork/sphinx-tribes-frontend#274]
### Context
`Body.tsx` renders tribes on the tribes page

### File to to test
`src/pages/tribes/Body.tsx`

### File to create
`src/pages/tribes/Body_spec..tsx

### Acceptance Criteria
- [ ] Test that public tribes are visible to both signed it and signed out user
- [ ] Test that you can click on a tribe card to see it's information like last activity, members count and admin
- [ ] Test that QR to join the tribe is visible 
- [ ] Test that Join Button open sphinx app
- [ ] Test that preview button takes you to a cached version of the chat
- [ ] Test that copy button copies the tribe pubkey
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a pr within 2 days of taking the bounty

### References
- Watch this [Jest Youtube playlist](https://www.youtube.com/watch?v=T2sv8jXoP4s&list=PLC3y8-rFHvwirqe1KHFCHJ0RqNuN61SJd) if you are new to testing
- Here is an [example unit test](https://github.com/stakwork/sphinx-tribes/blob/master/frontend/app/src/helpers/__test__/helpers.spec.ts)
- Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

**Comment by NengakDakup** [comment]
@ecurrencyhodler can i take this?

**Comment by ecurrencyhodler** [comment]
It's yours nen. Let's get a PR within 2 days. https://community.sphinx.chat/bounty/1535

**Comment by VividhPandey003** [comment]
Can I work on this?

**Comment by ecurrencyhodler** [comment]
Paid 250k sats! https://community.sphinx.chat/bounty/1535
