### ISSUE TITLE
[Tests][Component] Add tests to src/pages/leaderboard/index.tsx

### ISSUE THREAD

**Issue by Vayras** [stakwork/sphinx-tribes-frontend#275]
### Context
`src/pages/leaderboard/index.tsx`

### File to to test
`src/pages/leaderboard/index.tsx`

### File to create
`src/pages/leaderboard/LeaderBoard_Spec.tsx`

### Acceptance Criteria
- [ ] Test that leaderboard page is rendered and is visible
- [ ] Test that total sats earned and total task completed are rendered and is visible
- [ ] Test that top 3 contributors are rendered 
- [ ] Test that total list of contributors is visible
- [ ] Test that clicking on the clip icon for a contributor takes you to their profile
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a pr within 2 days of taking the bounty

### References
- Watch this [Jest Youtube playlist](https://www.youtube.com/watch?v=T2sv8jXoP4s&list=PLC3y8-rFHvwirqe1KHFCHJ0RqNuN61SJd) if you are new to testing
- Here is an [example unit test](https://github.com/stakwork/sphinx-tribes/blob/master/frontend/app/src/helpers/__test__/helpers.spec.ts)
- Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

**Comment by okhot** [comment]
Can I get this?

**Comment by MahtabBukhari** [comment]
@ecurrencyhodler Could you assign to me?

**Comment by ecurrencyhodler** [comment]
@MahtabBukhari it's yours. Let's get a PR up in 2 days: https://community.sphinx.chat/bounty/1537

**Comment by okhot** [comment]
> Can I get this?

🙄

**Comment by ecurrencyhodler** [comment]
I just gave you one @okhot
