### ISSUE TITLE
Unsettled deposit invoices are marked as deposited in org txn history

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes-frontend#276]
**Describe the bug**
An unsettled invoice in an org is marked as "paid" if someone generates an invoice, goes out of the org, then comes back to the org. 

https://github.com/stakwork/sphinx-tribes-frontend/assets/32662508/2b1a97b0-c96f-4973-af2b-e14ecb2237b8

Good news is that the org balance isn't updated.

**Expected behavior**
Deposit invoices that aren't settled shouldn't be displayed as "deposited" in the org txn history. Org amount should also not be updated.

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a screenshot or video in my PR
- [ ] I have created a test that unsettled invoices are not marked as deposited
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 2 days of taking the bounty

Here is an [example unit test](https://github.com/stakwork/sphinx-tribes/blob/master/frontend/app/src/helpers/__test__/helpers.spec.ts)
Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

**Comment by saithsab877** [comment]
Hi @ecurrencyhodler,
Could you assign to me? When you post the bounty.

**Comment by ecurrencyhodler** [comment]
We need to investigate this a bit more. Thanks ya'll.

**Comment by ecurrencyhodler** [comment]
This is raph's.
