### ISSUE TITLE
Correctly link profiles to users on the Leaderboard Page

### ISSUE THREAD

**Issue by aliraza556** [stakwork/sphinx-tribes-frontend#279]
**Describe the bug**
The user is not routed to the correct person on the leaderboard page.

***Bug Demo***
https://www.loom.com/share/489c05fc88dd4e698b47ef501df403a3

**To Reproduce**
1. Go to '(https://community.sphinx.chat/leaderboard)'
2. Click on any person of the name
3. See error

**Expected behavior**
When a user navigates to the leaderboard page and selects a person, the system should accurately route them to the detailed profile or information page of the selected person, ensuring that the user views the correct individual's data and achievements as intended.

**Desktop (please complete the following information):**
 - Browser [e.g. chrome]

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a screenshot or video in my PR
- [ ] I have created a test that asserts the right profile is mapped to the right name displayed
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 2 days of taking the bounty

**Comment by aliraza556** [comment]
Hi @ecurrencyhodler, please review this issue and assign it to me.

**Comment by ecurrencyhodler** [comment]
@aliraza556 thanks for reporting this issue. I see that you have several pending bounties. I'm going to assign this to another hunter.

**Comment by MuhammadUmer44** [comment]
Hi @ecurrencyhodler,
Assign me?

**Comment by ecurrencyhodler** [comment]
Hi Muhammad! Welcome. We have a bitcoin bounty for this as well.  Also are you on sphinx chat? It's how we pay out the bitcoin bounties.

Also how did you hear about our project?

**Comment by MuhammadUmer44** [comment]
@saithsab877 refer me this project

**Comment by ecurrencyhodler** [comment]
Okay I'm going to assume you don't have sphinx chat. You can follow the steps in our [FAQ](https://docs.google.com/document/d/16NQ4SM4ptP4Lz5JKERAagdNw3GFRVv9eshMZ_oU-MVw/edit?usp=sharing) to DL the app. 

Here is a connection code for you:
connect::relay.swarm4.sphinx.chat::02d5ee5907bd6e34332b8153bc3f50b4083a039e9dca7d85e02065ddf361a2bc72

Then sign into the [website](https://community.sphinx.chat/bounties) and reply back with your sphinx name and i'll assign the bounty to you!

**Comment by MuhammadUmer44** [comment]
@ecurrencyhodler
My Sphinx name is Muhammad Umer.

**Comment by ecurrencyhodler** [comment]
It's been assigned: https://community.sphinx.chat/bounty/1560
Let's get a pr within 2 days.

**Comment by MuhammadUmer44** [comment]
> It's been assigned: https://community.sphinx.chat/bounty/1560 Let's get a pr within 2 days.

Thanks

**Comment by MuhammadUmer44** [comment]
Hi @ecurrencyhodler
I cannot login sphinx mobile app with this code connect::relay.swarm4.sphinx.chat::02d5ee5907bd6e34332b8153bc3f50b4083a039e9dca7d85e02065ddf361a2bc72

**Comment by MuhammadUmer44** [comment]
I accidentally removed the mobile app. Please guide me on how to log in again to the mobile app.

**Comment by ecurrencyhodler** [comment]
@MuhammadUmer44 did you save the backup code?

**Comment by MuhammadUmer44** [comment]
> @MuhammadUmer44 did you save the backup code?
No

**Comment by ecurrencyhodler** [comment]
You'll need to create a new account: connect::relay.swarm4.sphinx.chat::02f63607407b6a39c5b468d1d5fd5cdf4b45d3ce9f2df382b760ab9df3b9b97a5c

Make sure to follow the steps in the FAQ to save your pin and backup code!

**Comment by MuhammadUmer44** [comment]
> connect::relay.swarm4.sphinx.chat::02f63607407b6a39c5b468d1d5fd5cdf4b45d3ce9f2df382b760ab9df3b9b97a5c

Thanks please assign bounty this sphinx profile name `umer`

**Comment by ecurrencyhodler** [comment]
Done: https://community.sphinx.chat/bounty/1560

**Comment by MuhammadUmer44** [comment]
Hi @ecurrencyhodler,
I've fixed the issue; please check the demo: 
https://www.loom.com/share/fbea8fb97b6d4a69b6b10cdc30955f2f

I'm just waiting to merge this PR #293 before I create my own.

**Comment by ecurrencyhodler** [comment]
@MuhammadUmer44 this is ready to go!

**Comment by ecurrencyhodler** [comment]
Tested and paid 200k sats! GJ!
