### ISSUE TITLE
View org description when user is logged out

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes-frontend#284]
**Describe the bug**
Currently when viewing an org as a signed out user, I do not see the org description.

<img width="905" alt="Screenshot 2024-02-21 at 2 49 13 PM" src="https://github.com/stakwork/sphinx-tribes-frontend/assets/32662508/c16ea95c-c0ed-4b0c-805d-7ff1a9e81fd1">

**Expected behavior**
I should be able to see the org description like this:
<img width="906" alt="Screenshot 2024-02-21 at 2 49 23 PM" src="https://github.com/stakwork/sphinx-tribes-frontend/assets/32662508/221d062e-b022-4b81-ae56-ad270a291310">

**Desktop (please complete the following information):**
 - Browser: Chrome

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a screenshot or video in my PR
- [ ] I have created a test that asserts the org description is viewable if a user is signed out
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 2 days of taking the bounty

Here is an [example unit test](https://github.com/stakwork/sphinx-tribes/blob/master/frontend/app/src/helpers/__test__/helpers.spec.ts)
Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

**Comment by okhot** [comment]
Can I have this 😅

**Comment by okhot** [comment]
PR will be on schedule 👌

**Comment by FaisalIqbal211** [comment]
@ecurrencyhodler assign me?

**Comment by saithsab877** [comment]
@ecurrencyhodler assign me

**Comment by ColdMice** [comment]
@ecurrencyhodler can you assign this issue to me

**Comment by chiragDork** [comment]
Hi @ecurrencyhodler can you please assign this to me
