### ISSUE TITLE
Call bounty statuses in superadmin in the beginning

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes-frontend#285]
**Describe the bug**
Right now only open bounties are called when I land on the page

https://github.com/stakwork/sphinx-tribes-frontend/assets/32662508/90f4e843-e1ac-4a7a-b5bd-2643c701c011

**Expected behavior**
All bounties should be called and displayed when I first go to the superadmin page.

**Desktop (please complete the following information):**
 - Browser: Chrome

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a screenshot or video in my PR
- [ ] I have created a test that bounties of all statuses are displayed
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 2 days of taking the bounty

Here is an [example unit test](https://github.com/stakwork/sphinx-tribes/blob/master/frontend/app/src/helpers/__test__/helpers.spec.ts)
Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

**Comment by AbdulWahab3181** [comment]
@ecurrencyhodler assign me

**Comment by vishnu552** [comment]
Hey can I take this one
