### ISSUE TITLE
Add provider filter to superadmin

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes-frontend#294]
### Context
I'd like to be able to filter for providers when looking at bounties inside of superadmin.

We are currently grabbing bounties using this call: `metrics/bounties`. 

We are adding an optional word clause to search for providers and their bounties only using or statements so that multiple providers and the bounties they posted are returned. This is being developed in https://github.com/stakwork/sphinx-tribes/issues/1547

### Design
Here is the design in [figma](https://www.figma.com/file/1aL3lgG5Rpkti4b0j42fwf/Bounties---FINAL-DESIGNS?type=design&node-id=9067%3A23134&mode=dev&t=KJcch6Dg5pyA5oEO-1). Use [dev move ](https://www.figma.com/dev-mode/) for exact requirements:
![Dropdown v2](https://github.com/stakwork/sphinx-tribes-frontend/assets/32662508/c5a64358-8af2-4537-befe-f3faa2bd75c2)

In terms of functionality, I click on "Providers" and displays a dropdown.

The dropdown will aggregate and display all unique providers within the set date range by default. I can also click on multiple providers.

I will only be displayed 5 providers initially but will have the ability to scroll to see the rest. I will also see their sphinx alias's not pubkeys. If there is no sphinx alias and only a pubkey, follow the design above. 

The call will be made when I click "apply". When I click "clear" all selections will be removed but dropdown filter display will be preserved.

### Acceptance Criteria
- [ ] I've tested on Chrome
- [ ] I've submitted a screenshot or recording in my pr
- [ ] I've created a test that displays the dropdown when I click on "providers"
- [ ] I've created a test that the appropriate call is stored when I select providers
- [ ] I've created a test that makes a call when I "apply"
- [ ] I've created a test that clears selections when I click "clear"
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a pr within 2 days of taking the bounty

Here is an [example unit test](https://github.com/stakwork/sphinx-tribes/blob/master/frontend/app/src/helpers/__test__/helpers.spec.ts)

Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

**Comment by vishnu552** [comment]
Hey, @ecurrencyhodler I would like to work on this issue

**Comment by MahtabBukhari** [comment]
@ecurrencyhodler Could you assign me as it is posted?

**Comment by arimusdev** [comment]
assign

**Comment by ManyRios** [comment]
I can take a look on this

**Comment by aliraza556** [comment]
Hi @ecurrencyhodler,
Assign me?

**Comment by AbdulWahab3181** [comment]
@ecurrencyhodler Could you please assign me?

**Comment by ecurrencyhodler** [comment]
paid
