### ISSUE TITLE
Make description bounty grey and uneditable when editing a bounty and if github issue is provided.

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes-frontend#296]
**Describe the bug**
Currently when a bounty is grabbing a bounty description from the github issue, it overrides any edits made within the "edit a bounty" modal. 

https://github.com/stakwork/sphinx-tribes-frontend/assets/32662508/de62d925-a04a-4752-8756-93ca5e76f72f

**Expected behavior**
Let's lock the description part of the bounty by making it unclickable and add a shade of grey. 

**Desktop (please complete the following information):**
 - Browser: Chrome

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a screenshot or video in my PR
- [ ] I have created a test that asserts the description is uneditable when description is getting pulled from a github issue
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 2 days of taking the bounty

Here is an [example unit test](https://github.com/stakwork/sphinx-tribes/blob/master/frontend/app/src/helpers/__test__/helpers.spec.ts)
Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

**Comment by AbdulWahab3181** [comment]
@ecurrencyhodler could you please assign me?

**Comment by AbdulWahab3181** [comment]
@ecurrencyhodler could you please reupload the bug video? It's not properly uploaded.

**Comment by MahtabBukhari** [comment]
@ecurrencyhodler Could you assign me?

**Comment by HarshKalwani** [comment]
@ecurrencyhodler I'm a new contributor looking for my first issue to work on can you please assign me to this

**Comment by VividhPandey003** [comment]
@ecurrencyhodler can I work on this?

**Comment by ecurrencyhodler** [comment]
Hey @HarshKalwani welcome! Are you on sphinx chat? It's how we pay bitcoin bounties. Also how did you hear about our project?

I'll try and find another bounty for you

**Comment by ecurrencyhodler** [comment]
@VividhPandey003 let's get a PR up within 2 days!

**Comment by VividhPandey003** [comment]
Sure thing!

**Comment by HarshKalwani** [comment]
> Hey @HarshKalwani welcome! Are you on sphinx chat? It's how we pay bitcoin bounties. Also how did you hear about our project?
> 
> I'll try and find another bounty for you

Hey!, i joined approximately a month ago, I was referred by @Vayras

**Comment by ecurrencyhodler** [comment]
Ah what's your sphinx name?

**Comment by HarshKalwani** [comment]
> Ah what's your sphinx name?
> 

Harshkalwani
