### ISSUE TITLE
Add toasts when user roles are updated or user is deleted

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes-frontend#297]
### Context
Right now, there are no toast messages when user roles are updated or when a user is deleted.

### Design
Add following toast messages:
- User permissions updated!
- User removed from org!

https://github.com/stakwork/sphinx-tribes-frontend/assets/32662508/ce3f8207-2944-4ca3-a932-9344b180431f

### Acceptance Criteria
- [ ] I've tested on Chrome
- [ ] I've submitted a screenshot or recording in my pr
- [ ] I've created a tests for the toast messages
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a pr within 2 days of taking the bounty

Here is an [example unit test](https://github.com/stakwork/sphinx-tribes/blob/master/frontend/app/src/helpers/__test__/helpers.spec.ts)

Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

**Comment by ecurrencyhodler** [comment]
@saithsab877 Hey so can you update the toast messages to the ones listed in the ticket?

**Comment by okhot** [comment]
@ecurrencyhodler im already working on toast can i get this?

**Comment by ecurrencyhodler** [comment]
@saithsab877 reported it so it's his.

**Comment by okhot** [comment]
🫡

**Comment by saithsab877** [comment]
Hi @ecurrencyhodler i fix it
