### ISSUE TITLE
Design confirmation screen when paying a bounty

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes-frontend#298]
### Context
Right now, when someone clicks "pay bounty" button on a bounty, it auto-pays. 
<img width="689" alt="Screenshot 2024-02-22 at 1 52 50 PM" src="https://github.com/stakwork/sphinx-tribes-frontend/assets/32662508/3eea7fb8-7f0c-40d1-83a8-9f7ddd57799a">

### Design
Lets design confirmation screen that appears. The text should say, "Are you sure you want to pay this bounty?".

It should then have the following buttons: Yes, No

**Comment by Antanasijevic** [comment]
@ecurrencyhodler Here is option based on same modal we are using for deleting a Bounty

Figma 
https://www.figma.com/file/1aL3lgG5Rpkti4b0j42fwf/Bounties---FINAL-DESIGNS?type=design&node-id=11516%3A27998&mode=design&t=LiwtI1ap5odwCbA5-1

![Image](https://github.com/stakwork/sphinx-tribes-frontend/assets/13258550/7912b4af-8e1b-4f9d-8772-ea7d043eb67e)

**Comment by ecurrencyhodler** [comment]
Okay this works. Thanks!
