### ISSUE TITLE
Prevent character count increasing if there is no count in the selected field when creating or editing an org

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes-frontend#299]
### Bug
When a user adds a character to website or github, the character count increases in org description. It even goes past the restricted character limit.

https://www.loom.com/share/556b3f994a334850bb43dc3123784b85

### Expected behavior
Writing something in one field shouldn't increase the character count in other fields
https://www.loom.com/share/0b807b7b99c542c38b4527be84d2aaf7

**Desktop (please complete the following information):**
 - Browser: Chrome

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a screenshot or video in my PR
- [ ] I have created a test that asserts character counts do not increase in other fields
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 2 days of taking the bounty

Here is an [example unit test](https://github.com/stakwork/sphinx-tribes/blob/master/frontend/app/src/helpers/__test__/helpers.spec.ts)
Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

**Comment by ecurrencyhodler** [comment]
@aliraza556 can you comment here? And please take a look at the updated issue.

**Comment by aliraza556** [comment]
@ecurrencyhodler
Assign me

**Comment by ecurrencyhodler** [comment]
Here's the bounty: https://community.sphinx.chat/bounty/1573
