### ISSUE TITLE
Clear assignee after saving edit if hunter has been unassigned

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes-frontend#30]
**Describe the bug**
When I remove a hunter from a bounty, edit it, and save it, the hunter gets reassigned automatically.

https://github.com/stakwork/sphinx-tribes-frontend/assets/32662508/790ab69c-33bb-4cae-a05d-12fdbb4616b9

**Expected behavior**
The hunter should not be reassigned after I edit it. 

**Desktop (please complete the following information):**
 - Browser: Chrome

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a in my PR
- [ ] I've created a test to check hunter has been cleared when they are unassigned

**Comment by gouravmpk** [comment]
I can take this

**Comment by ecurrencyhodler** [comment]
Hey you've got one bounty without a pr. Let's get this to a diff. hunter.

**Comment by Vayras** [comment]
@ecurrencyhodler I would like to work on this , Can I take this issue? , let me know

**Comment by AbdulWahab3181** [comment]
@ecurrencyhodler Could you please assign me

**Comment by ecurrencyhodler** [comment]
@AbdulWahab3181 do you have an update on this? You have 2 days left before I unassign.

**Comment by AbdulWahab3181** [comment]
@ecurrencyhodler I am working on it. I will create a PR by end of day, or maybe by tomorrow afternoon.

**Comment by AbdulWahab3181** [comment]
@ecurrencyhodler Could you please review this PR https://github.com/stakwork/sphinx-tribes-frontend/pull/96
