### ISSUE TITLE
Display search term in search bar when typed for tribes page

### ISSUE THREAD

**Issue by Fog3211** [stakwork/sphinx-tribes-frontend#301]
**Describe the bug**
When I type a word or term in the search bar, the word/term is not visible to me. 

**To Reproduce**
1. Go to https://community.sphinx.chat/t
2. Search by keyword 
3. Can not display the keyword what i have Typing

https://github.com/stakwork/sphinx-tribes-frontend/assets/23151576/541aaa4c-9fc0-4d7e-8be7-027714bf0edd

**Expected behavior**
The keyword show be displayed to me in black font when I am typing.

**Desktop (please complete the following information):**
 - Browser Chrome 120

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a screenshot or video in my PR
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 2 days of taking the bounty

Here is an [example unit test](https://github.com/stakwork/sphinx-tribes/blob/master/frontend/app/src/helpers/__test__/helpers.spec.ts)
Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

**Comment by Fog3211** [comment]
@ecurrencyhodler please assign it to me

**Comment by ecurrencyhodler** [comment]
Posted: https://community.sphinx.chat/bounty/1577

This seems to be a simple font color change so the bounty is small.

**Comment by ecurrencyhodler** [comment]
Also did you get your other fog3211 account removed? The one you lost access to? I only see one fog account

**Comment by Fog3211** [comment]
> https://community.sphinx.chat/bounty/1577

Thanks

**Comment by ecurrencyhodler** [comment]
Paid! https://community.sphinx.chat/bounty/1577
