### ISSUE TITLE
Center loading spinner placement on tribes, bounties, and people

### ISSUE THREAD

**Issue by MahtabBukhari** [stakwork/sphinx-tribes-frontend#307]
**Describe the bug**
There is an inconsistency with the loading spinner placement on the last three pages. It should be positioned in the center of the page.

https://www.loom.com/share/e9b41343da5d46af96e03eaf5661e4f6?sid=0f339880-04aa-4e77-ab4b-d7a13cd630fb

**To Reproduce**
1. click on all pages nav links in navbar one by one
2. see the bug that is loading spinner is not at center in all pages

**Expected behavior**
 It should be positioned in the center of the page.

**Desktop (please complete the following information):**
 - Browser: Chrome

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a screenshot or video in my PR
- [ ] I've created a test that spinners are centered
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 2 days of taking the bounty

**Comment by MahtabBukhari** [comment]
@ecurrencyhodler Could you assign me?

**Comment by ecurrencyhodler** [comment]
Here you go! https://community.sphinx.chat/bounty/1580

**Comment by MahtabBukhari** [comment]
Hi @ecurrencyhodler 
I have completed my work 
https://www.loom.com/share/b1d7666f73a0487497a0bf16b544b247?sid=3c3e175f-7a53-47b1-ab5d-bc67c70a4191

I am just waiting for to resolved the tests problem in "AddUserModal.spec.tsx" that is reported by @aliraza556 and @Vayras

**Comment by ecurrencyhodler** [comment]
Paid 100k sats! Gj! https://community.sphinx.chat/bounty/1580
