### ISSUE TITLE
Wrong bounties displayed on homepage post-bounty creation.

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes-frontend#31]
**Describe the bug**
When I create a bounty, the wrong bounties are displayed after it's been created. 

**Staging**
https://github.com/stakwork/sphinx-tribes-frontend/assets/32662508/fddb92c6-ba4b-4e57-aee5-f5a487a2e45b

**Prod**
https://github.com/stakwork/sphinx-tribes-frontend/assets/32662508/abeb8e69-cce7-423d-a655-b521439cff5c

**Expected behavior**
The filter state before bounty was created should be preserved. So if open + assigned was selected, that should still be displayed. If only open, only open should be displayed. If open + typescript, only those bounties should be displayed.

**Desktop (please complete the following information):**
 - Browser: Chrome

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted video in my PR
- [ ] I've created a test that the filter before bounty creation is preserved post bounty creation

**Comment by aliraza556** [comment]
@ecurrencyhodler Please assign me?

**Comment by ecurrencyhodler** [comment]
okay this is yours

**Comment by aliraza556** [comment]
Thanks

**Comment by aliraza556** [comment]
Hi @ecurrencyhodler,
Please see [demo](https://www.loom.com/share/fce98b98606f4c8b8ded59896a384709)

**Comment by ecurrencyhodler** [comment]
Hmmm I wonder if it's just me then... I'll have to double check.

**Comment by aliraza556** [comment]
@ecurrencyhodler
See this [Link](https://www.loom.com/share/c4b4de4a954143aaa6c2e9daea071e11)

**Comment by aliraza556** [comment]
@ecurrencyhodler 
See this [Link](https://www.loom.com/share/9cd10a42731d4e208f01c8b596bd0f3b) Staging side without assign.

**Comment by ecurrencyhodler** [comment]
I'm seeing this behavior now. Are you? It also happens when I delete a bounty too.

https://github.com/stakwork/sphinx-tribes-frontend/assets/32662508/00f18885-4a51-44f1-b7fe-db783f34af82

**Comment by ecurrencyhodler** [comment]
This is on staging.

**Comment by ecurrencyhodler** [comment]
Okay looks like it's a browser issue on my end. I'm closing this.
