### ISSUE TITLE
[Org Homepage] Enable hover button on "skill" button and default to grey text

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes-frontend#313]
**Describe the bug**
Right now, the org homepage has a skill button that does not have a default grey text such as status. Also when the mouse overs over the button it fails in two aspects:
1. It doesn't trigger hand icon over the text "skill"
2. It also doesn't turn black like other buttons such as "status"

https://github.com/stakwork/sphinx-tribes-frontend/assets/32662508/48e5808c-6f8c-472b-979f-52a9f8627952

**Expected behavior**
Default text should be grey, should turn black when mouse is hovering over it, and mouse should trigger hand icon when it hovers of the word "skill".

**Desktop (please complete the following information):**
 - Browser: Chrome

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a screenshot or video in my PR
- [ ] I have created a test that asserts the mouse triggers hand icon when it hovering over the text and arrow icon.
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 2 days of taking the bounty

Here is an [example unit test](https://github.com/stakwork/sphinx-tribes/blob/master/frontend/app/src/helpers/__test__/helpers.spec.ts)
Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

**Comment by Ekep-Obasi** [comment]
@ecurrencyhodler can I get this?

**Comment by MuhammadUmer44** [comment]
Hi @ecurrencyhodler,
Please assign me?

**Comment by ManyRios** [comment]
🙋

**Comment by MuhammadUmer44** [comment]
Hi @ecurrencyhodler,
I have fixed it; I'm just waiting to resolve this issue in `src/people/widgetViews/__tests__/AddUserModal.spec.tsx` before creating my own PR.
https://www.loom.com/share/e307fe8fdef240f0a042e871b400fb2c
