### ISSUE TITLE
[Tests][Component] Add tests to src/people/userInfo/UserInfoDesktopView.tsx 

### ISSUE THREAD

**Issue by Vayras** [stakwork/sphinx-tribes-frontend#314]
### Context
`UserInfoDesktopView.tsx` renders info for a created user

### File to to test
`src/people/userInfo/UserInfoDesktopView.tsx`

### File to create
`src/people/userInfo/UserInfoDesktopView.Spec.tsx

### Acceptance Criteria
- [ ] Test that user profile photo is visible
- [ ] Test that user connect QR button is rendered and upon clicking it renders connect modal on page
- [ ] Test that description/bio for a user is visible if provided 
- [ ] Test that connect and send tip buttons are rendered and open connect and send tip modals upon clicking 
- [ ] Test that price to connect,  pubkey , copy button, email if provided, and github account if provided are visible
- [ ] Test that user skills are visible and rendered if provided
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a pr within 2 days of taking the bounty

### References
- Watch this [Jest Youtube playlist](https://www.youtube.com/watch?v=T2sv8jXoP4s&list=PLC3y8-rFHvwirqe1KHFCHJ0RqNuN61SJd) if you are new to testing
- Here is an [example unit test](https://github.com/stakwork/sphinx-tribes/blob/master/frontend/app/src/helpers/__test__/helpers.spec.ts)
- Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

**Comment by okhot** [comment]
I'd love to work on this

**Comment by arimusdev** [comment]
assign

**Comment by NengakDakup** [comment]
@ecurrencyhodler can i take this

**Comment by Fog3211** [comment]
@ecurrencyhodler can i take this

**Comment by okhot** [comment]
> I'd love to work on this

@ecurrencyhodler I can help with this

**Comment by ManyRios** [comment]
🙋

**Comment by ecurrencyhodler** [comment]
@ManyRios let's get a pr up in 2 days.
