### ISSUE TITLE
Create error notification if bounty fails to get created

### ISSUE THREAD

**Issue by kevkevinpal** [stakwork/sphinx-tribes-frontend#323]
So basically right now even if we fail to post a bounty the modal will disappear and the user is left wondering if their bounty has actually been posted and that is not good ui/ux

This can be reproduced by running on localhost by only modifying the `host.ts` and `modeDispacter.ts` files and when you try and post a bounty you will get a `406` response from the golang server for an invalid jwt token but we should have a modal or a toast saying "bounty failed to upload please contact bounty server host or try again".

If the user creates a bounty and gets a `406` response, then keep the bounty modal open and flash a notification on the bottom right of the screen saying "Bounty could not be created".

### Design
The triggering event is the button "finish". Therefore the screen that should not be closed and preserved is the one below. 
<img width="1191" alt="Bounty Modal" src="https://github.com/stakwork/sphinx-tribes/assets/32662508/3cc597aa-cd7c-40a2-acfc-66790000f001">

### Acceptance Criteria

- [ ] I've tested on Chrome
- [ ] I've posted a video of the notification
- [ ] Create component test for failure pop-up modal 
- [ ] I've submitted a PR within 2 days of taking the bounty
- [ ] I have rebased and tested locally before submitting my PR

**Comment by ecurrencyhodler** [comment]
Paid 400k sats: https://community.sphinx.chat/bounty/1016
