### ISSUE TITLE
Enable delete button after unassigning a hunter

### ISSUE THREAD

**Issue by kevkevinpal** [stakwork/sphinx-tribes-frontend#324]
After removing user from bounty it does not make delete button available until I refresh.

https://github.com/stakwork/sphinx-tribes/assets/32662508/346517b5-b46f-43c6-a74f-799fb3db67a6

_Originally posted by @kevkevinpal in https://github.com/stakwork/sphinx-tribes/issues/1104#issuecomment-1860955568_

### Expected behavior
The delete button should be clickable once a hunter has been unassigned without needing to refresh.

### Acceptance Criteria

- [ ] I have tested on Chrome
- [ ] I have posted a video of being able to delete button after unassigning someone from the bounty

**Comment by ecurrencyhodler** [comment]
Tested and paid 200k sats! https://community.sphinx.chat/bounty/952
