### ISSUE TITLE
Design filter button for bounty statuses when viewing created or assigned bounties in profile

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes-frontend#326]
### Context
We want to enable the ability for users to filter bounties when viewing created and assigned bounties on their profile.

For the bounties tab, the bounties will display by default:
- open
- assigned
- paid

The filter options include the 3 mentioned above as well.
<img width="1122" alt="Screenshot 2024-02-28 at 1 29 30 PM" src="https://github.com/stakwork/sphinx-tribes/assets/32662508/31b42743-2be7-472a-b73f-13f2dff4dd14">

For assigned tab, the bounties will display by default:
- assigned
- paid

The filter options include the 2 mentioned above as well.
<img width="1124" alt="Screenshot 2024-02-28 at 1 22 15 PM" src="https://github.com/stakwork/sphinx-tribes/assets/32662508/2f30439c-18cf-494c-855e-afa13e57bbff">

### Design
Let's create a small button that is easily accessible on the individual created and assigned bounties tab. This shouldn't be a redesign. A small and quick UI update will suffice. 

The two types of filters we use right now are the following:
<img width="73" alt="Screenshot 2024-02-28 at 3 21 47 PM" src="https://github.com/stakwork/sphinx-tribes-frontend/assets/32662508/89f05261-2f69-4f32-a43c-2f8182bed082">

<img width="277" alt="Screenshot 2024-02-28 at 3 30 47 PM" src="https://github.com/stakwork/sphinx-tribes-frontend/assets/32662508/d3942ffc-b120-4b36-97f6-cec4ca16dddc">

**Comment by Antanasijevic** [comment]
Bounties
![image](https://github.com/stakwork/sphinx-tribes-frontend/assets/13258550/4bc9f9f2-7408-4f4f-ba18-d246336042f3)

Assigned Bounties
![image](https://github.com/stakwork/sphinx-tribes-frontend/assets/13258550/6c05d398-8800-4bba-ab1e-56a8303a6ae1)

**Comment by ecurrencyhodler** [comment]
LGTM. Thanks.
