### ISSUE TITLE
Make "Sort by" button in Superadmin grey by default

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes-frontend#329]
**Describe the bug**
Make "Sort by" button in Superadmin grey by default. This includes the text and the arrow. When a mouse hovers over the button, it should turn black similar to the behavior of the "status" button.
<img width="1124" alt="Screenshot 2024-02-28 at 3 22 12 PM" src="https://github.com/stakwork/sphinx-tribes-frontend/assets/32662508/5a9f8290-f905-4730-9e95-0f52476c5ae5">

**Desktop (please complete the following information):**
 - Browser: Chrome

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a screenshot or video in my PR
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 2 days of taking the bounty

**Comment by okhot** [comment]
@ecurrencyhodler I can send a PR for this in a couple hours

**Comment by Fog3211** [comment]
can i take this？
