### ISSUE TITLE
Display default photo in bounty 

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes-frontend#334]
**Describe the bug**
The user Tom S doesn't have a photo. Therefore a default face picture is displayed on his behalf. However when you click inside the bounty, another stock-image is displayed.

https://github.com/stakwork/sphinx-tribes-frontend/assets/32662508/4de43e1a-face-4574-b2bc-2ee3126ff090

**Expected behavior**
The default face picture should also be displayed inside the bounty. Implement this on desktop and mobile.

**Desktop (please complete the following information):**
 - Browser: Chrome

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a screenshot or video in my PR
- [ ] I have created a test that asserts that the default face image is displayed
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 2 days of taking the bounty

Here is an [example unit test](https://github.com/stakwork/sphinx-tribes/blob/master/frontend/app/src/helpers/__test__/helpers.spec.ts)
Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

**Comment by aliraza556** [comment]
Hi @ecurrencyhodler,
Assign me?

**Comment by okhot** [comment]
@ecurrencyhodler can I get this
