### ISSUE TITLE
[Tests][Component] Add Test to src/pages/tickets/Tickets.tsx and src/pages/tickets/TicketModalPage.tsx

### ISSUE THREAD

**Issue by Vayras** [stakwork/sphinx-tribes-frontend#335]
### Context
`Tickets.tsx` page renders the bounty tickets on the page and `TicketModalPage.tsx` renders the bounty modal, we are increasing the coverage for that in this page

### File to to test
`src/pages/tickets/Tickets.tsx` and `src/pages/tickets/TicketModalPage.tsx`

### File to create
`src/pages/tickets/Tickets.spec.tsx` and `src/pages/tickets/TicketModalPage.spec.tsx

### Acceptance Criteria
- [ ] Test that load more button is visible at bottom of page when there's 10 or more bounties
- [ ] Test that If load more button is clicked, it triggers the "get bounties" api call.
- [ ] Test that clicking on bounty opens the bounty modal
- [ ] Test that on bounty modal left and right arrows are visible
- [ ] Test that left and right arrows take you to previous and next bounties respectively
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a pr within 2 days of taking the bounty

### References
- Watch this [Jest Youtube playlist](https://www.youtube.com/watch?v=T2sv8jXoP4s&list=PLC3y8-rFHvwirqe1KHFCHJ0RqNuN61SJd) if you are new to testing
- Here is an [example unit test](https://github.com/stakwork/sphinx-tribes/blob/master/frontend/app/src/helpers/__test__/helpers.spec.ts)
- Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

**Comment by okhot** [comment]
I can help with this

**Comment by ecurrencyhodler** [comment]
It's yours

**Comment by ecurrencyhodler** [comment]
Paid 300k sats! https://community.sphinx.chat/bounty/1609
