### ISSUE TITLE
Display profile photo when viewing assigned bounties in profile

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes-frontend#336]
**Describe the bug**
When viewing assigned bounties from this user (https://community.sphinx.chat/p/ckpcvk84nncso5beu0a0/assigned), the profile photo of the creator is not displayed. However this bug isn't reproducible all the time as other profiles display the profile photo correctly.

https://github.com/stakwork/sphinx-tribes-frontend/assets/32662508/c140548a-9cd8-4702-82aa-d456f6758fcb

**Expected behavior**
Display the correct profile photo when viewing assigned bounties.

**Desktop (please complete the following information):**
 - Browser: Chrome

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a screenshot or video in my PR
- [ ] I have created a test that asserts the correct profile photo is displayed
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 2 days of taking the bounty

Here is an [example unit test](https://github.com/stakwork/sphinx-tribes/blob/master/frontend/app/src/helpers/__test__/helpers.spec.ts)
Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

**Comment by saithsab877** [comment]
@ecurrencyhodler 
Could you assign me?

**Comment by MirzaHanan** [comment]
Hi @ecurrencyhodler,
Please assign me?

**Comment by AbdulWahab3181** [comment]
@ecurrencyhodler could you please assign me?

**Comment by ecurrencyhodler** [comment]
@MirzaHanan I will find you another one.

**Comment by ecurrencyhodler** [comment]
Tested and paid 200k sats! https://community.sphinx.chat/bounty/1610
