### ISSUE TITLE
[Tests][Component] Add Test to src/people/widgetViews/BountyHeader.tsx and src/people/main/Header.tsx

### ISSUE THREAD

**Issue by Vayras** [stakwork/sphinx-tribes-frontend#337]
### Context
`BountyHeader.tsx` and `Header.tsx` renders the header on the bounties homepage, we are increasing the coverage for this component

### File to to test
`src/people/widgetViews/BountyHeader.tsx and `src/people/main/Header.tsx`

### File to create
`src/people/widgetViews/BountyHeader.spec.tsx and `src/people/main/Header.spec.tsx`

### Acceptance Criteria
- [ ] Test that clicking on `Get Sphinx` button is visible and renders the startup modal on clicking
- [ ] Test that clicking on `Get Sphinx` on the modal takes you to the `https://buy.sphinx.chat/`
- [ ] Test that clicking on sign-in button, the sign-in component is rendered
- [ ] Test that Leaderboard button takes you to the leaderboard
- [ ] Test that Post a bounty button takes you to "Get Sphinx" modal as a signed out user
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a pr within 2 days of taking the bounty

### References
- Watch this [Jest Youtube playlist](https://www.youtube.com/watch?v=T2sv8jXoP4s&list=PLC3y8-rFHvwirqe1KHFCHJ0RqNuN61SJd) if you are new to testing
- Here is an [example unit test](https://github.com/stakwork/sphinx-tribes/blob/master/frontend/app/src/helpers/__test__/helpers.spec.ts)
- Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

**Comment by MirzaHanan** [comment]
Hi @ecurrencyhodler,
assign me?

**Comment by ecurrencyhodler** [comment]
Paid 300k sats! https://community.sphinx.chat/bounty/1611
