### ISSUE TITLE
Write component tests for profile header and bounty created tab

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes-frontend#339]
### Context

`people/main/Header.tsx` renders the header for the user profile and `tabs/index.tsx` renders the bounties created tab inside of a profile. We are increasing coverage for these areas.

### File to to test
For A and B of the acceptance criteria.
https://github.com/stakwork/sphinx-tribes-frontend/blob/master/src/people/main/Header.tsx

For C of the acceptance criteria.
https://github.com/stakwork/sphinx-tribes-frontend/blob/435b926a7c7d40d0553517a71902addbc4e12723/src/pages/people/tabs/index.tsx

### File to update
For A and B of the acceptance criteria.
https://github.com/stakwork/sphinx-tribes-frontend/blob/master/src/people/main/__tests__/Header.spec.tsx

For C of the acceptance criteria.

### Acceptance Criteria
Create component tests for the following actions:
- [ ] A. Click on the profile and view the title sections for org, badges, bounties, assigned.
- [ ] B. Click on bounties tab inside the profile and view a "Post a bounty" button if I am signed in
- [ ] C. View various statuses for bounties created including open, assigned, and paid inside bounties tab
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a pr within 2 days of taking the bounty

### References
- Watch this [Jest Youtube playlist](https://www.youtube.com/watch?v=T2sv8jXoP4s&list=PLC3y8-rFHvwirqe1KHFCHJ0RqNuN61SJd) if you are new to testing
- Here is an [example unit test](https://github.com/stakwork/sphinx-tribes/blob/master/frontend/app/src/helpers/__test__/helpers.spec.ts)
- Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

**Comment by okhot** [comment]
Can help with this

**Comment by Fog3211** [comment]
Can is take this?

**Comment by NengakDakup** [comment]
@ecurrencyhodler i can work on this
