### ISSUE TITLE
Assigned Bounties in People page shows only 10 bounties and loadmore code fix

### ISSUE THREAD

**Issue by VividhPandey003** [stakwork/sphinx-tribes-frontend#34]
**Describe the bug**

Assigned Bounties in People page shows only 10 bounties 
![image](https://github.com/stakwork/sphinx-tribes-frontend/assets/91251535/59681c81-e487-4ee4-83f0-99993dbfe123)

**To Reproduce**

https://people-test.sphinx.chat/p/0276681167b8beb1e6113b259504ab7f9d84432cb3626b1f81b388154eb924073f/usertickets

**Expected behavior**
It should display first 20 bounties initially with a loadmore button to display the next bounties

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a screenshot or video in my PR

**Comment by VividhPandey003** [comment]
I would like to fix this. Could you please assign me.

**Comment by ecurrencyhodler** [comment]
Hey Vividh. Where are you seeing 10 bounties? I see 20 on staging.

**Comment by VividhPandey003** [comment]
> Hey Vividh. Where are you seeing 10 bounties? I see 20 on staging.

![image](https://github.com/stakwork/sphinx-tribes-frontend/assets/91251535/3483327c-4ef2-4f01-a01f-3e0254ca1f19)

![image](https://github.com/stakwork/sphinx-tribes-frontend/assets/91251535/41f8aafd-692a-47a4-969f-5fa58dfe8edb)


https://people-test.sphinx.chat/p/0276681167b8beb1e6113b259504ab7f9d84432cb3626b1f81b388154eb924073f/usertickets


The assigned bounties shows only 10 bounties because of the pagination update from the backend. The frontend code needs to be updated accordingly

**Comment by ecurrencyhodler** [comment]
Got it. Okay let's do that.

**Comment by ecurrencyhodler** [comment]
From vividh: "With the new pagination queries it wont work."

Let's wait for raph to push his backend update first then we can tackle this.

**Comment by VividhPandey003** [comment]
> From vividh: "With the new pagination queries it wont work."
> 
> Let's wait for raph to push his backend update first then we can tackle this.

The backend works fine. We just need to update the frontend wrt the backend updates
