### ISSUE TITLE
[Tests][Component] Add Test to src/pages/people/tabs/Wanted.tsx and src/pages/people/tabs/index.tsx

### ISSUE THREAD

**Issue by Vayras** [stakwork/sphinx-tribes-frontend#344]
### Context
`src/pages/people/tabs/Wanted.tsx` renders user created bounties  and `src/pages/people/tabs/index.tsx` and renders the tabs to navigate to segments of user profile

### File to to test
`src/pages/people/tabs/Wanted.tsx` and `src/pages/people/tabs/index.tsx`

### File to create
`src/pages/people/tabs/Wanted.spec.tsx` and `src/pages/people/tabs/index.spec.tsx`

### Acceptance Criteria
- [ ] Test that clicking on the profile and view the title sections for org, badges, bounties, assigned.
- [ ] Test that Clicking on bounties tab inside the profile and view a "Post a bounty" button if I am signed in
- [ ] Test that user can view various statuses for bounties created including open, assigned, and paid inside bounties tab
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a pr within 2 days of taking the bounty

### References
- Watch this [Jest Youtube playlist](https://www.youtube.com/watch?v=T2sv8jXoP4s&list=PLC3y8-rFHvwirqe1KHFCHJ0RqNuN61SJd) if you are new to testing
- Here is an [example unit test](https://github.com/stakwork/sphinx-tribes/blob/master/frontend/app/src/helpers/__test__/helpers.spec.ts)
- Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

**Comment by NengakDakup** [comment]
@ecurrencyhodler can i take this

**Comment by okhot** [comment]
@NengakDakup I can help if you are facing a blocker on this task

**Comment by NengakDakup** [comment]
> @NengakDakup I can help if you are facing a blocker on this task

Somehow missed the notification that i was assigned to this issue, just found out yesterday, so i should be done by today. What's your sphinx username though?

**Comment by NengakDakup** [comment]
Hi @Vayras can you explain more the first Acceptance criteria 'Test that clicking on the profile and view the title sections for org, badges, bounties, assigned.'

**Comment by Vayras** [comment]
@NengakDakup Test that clicking on profile renders the tab to navigate between sections of profile

**Comment by ecurrencyhodler** [comment]
paid!
