### ISSUE TITLE
[Superadmin] Add apply button and fire call only when clicked

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes-frontend#347]
### Context
Right now, clicking a status in the filter in superadmin fires a call each time. 

https://github.com/stakwork/sphinx-tribes-frontend/assets/32662508/c9bc344d-488f-4c78-9184-724556466959

# Expected behavior
Add an apply button at the bottom of the filter. Fire the call with the correctly selected statuses after the save button has been clicked. 

You can use the same save button found in figma [here.](https://www.figma.com/file/1aL3lgG5Rpkti4b0j42fwf/Bounties---FINAL-DESIGNS?type=design&node-id=9067%3A23134&mode=design&t=e242BV3yxdgmTPs0-1)

### Acceptance Criteria
- [ ] I've tested on Chrome
- [ ] I've submitted a screenshot or recording in my pr
- [ ] I've created a test that asserts a call is made when apply is clicked
- [ ] I've created a test that correct bounties are displayed after apply is clicked
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a pr within 2 days of taking the bounty

Here is an [example unit test](https://github.com/stakwork/sphinx-tribes/blob/master/frontend/app/src/helpers/__test__/helpers.spec.ts)

Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

**Comment by MirzaHanan** [comment]
Hi @ecurrencyhodler
assign me?

**Comment by Ekep-Obasi** [comment]
@ecurrencyhodler Could you please assign?

**Comment by ManyRios** [comment]
🙋

**Comment by ecurrencyhodler** [comment]
Paid 200k sats! https://community.sphinx.chat/bounty/1616
