### ISSUE TITLE
[Cypress] Create 20 bounties

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes-frontend#348]
### Context
We are implementing cypress tests for E2E testing.

This test requires the following user story:

Go to homepage, create a bounty without an organization for 10,000 sats, Title it "Title 1", <3 hr estimation, typescript skill selected, web development selected, no github link, description added (Lorem Ipsum Dolor), and shown to public. Do this 20 times and title it up to "Title 20".

Put the test in this folder: 
https://github.com/stakwork/sphinx-tribes-frontend/tree/master/cypress/e2e

And title it the following: 
` 3_Create_20_bounties`

### Resources
1. Get up to speed on cypress tests here: https://github.com/stakwork/sphinx-tribes-frontend/blob/master/docs/setupCypressTest.md
2. Here is an example of a [cypress test](https://github.com/stakwork/sphinx-tribes-frontend/blob/master/cypress/e2e/create_bounty.cy.ts).
3. You'll also need to run [sphinx-stack](https://github.com/stakwork/sphinx-stack) locally to complete the tests.

### Acceptance Criteria

- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a pr within 5 days of taking the bounty

**Comment by AbdulWahab3181** [comment]
@ecurrencyhodler I would like to try this

**Comment by ecurrencyhodler** [comment]
Okay.

**Comment by ecurrencyhodler** [comment]
Let me know if you run into pain points and what steps you took to resolve them. We should document this to make it easier for other contributors.

**Comment by kevkevinpal** [comment]
what does the '3' in `3_Create_20_bounties` mean? I think that makes reading what the tests are doing a bit more difficult.

I think `create_20_bounties.cy.ts` makes more sense and fits the snake case format that we currently have

**Comment by AbdulWahab3181** [comment]
> what does the '3' in `3_Create_20_bounties` mean? I think that makes reading what the tests are doing a bit more difficult.
> 
> I think `create_20_bounties.cy.ts` makes more sense and fits the snake case format that we currently have

@kevkevinpal Addressed

**Comment by ecurrencyhodler** [comment]
Paid 300k sats! https://community.sphinx.chat/bounty/1617

Great work abdul.

**Comment by AbdulWahab3181** [comment]
> Paid!
> 
> Great work abdul.

Thanks
