### ISSUE TITLE
[Tests][Component] Add Test to src/pages/tickets/Tickets.tsx

### ISSUE THREAD

**Issue by Vayras** [stakwork/sphinx-tribes-frontend#350]
### Context
We are increasing coverage for connect card, available with tickets on the bounties homepage

### File to to test
`src/pages/tickets/Tickets.tsx`

### File to create
`src/pages/tickets/_test_/Tickets.tsx`

### Acceptance Criteria
- [ ] Test that Connection code QR is displayed when "I can help" is clicked.
- [ ] Test that if user is signed out clicking on I can help loads get sphinx modal
- [ ] Test that out of connection code is displayed when there are no codes
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a pr within 2 days of taking the bounty

### References
- Watch this [Jest Youtube playlist](https://www.youtube.com/watch?v=T2sv8jXoP4s&list=PLC3y8-rFHvwirqe1KHFCHJ0RqNuN61SJd) if you are new to testing
- Here is an [example unit test](https://github.com/stakwork/sphinx-tribes/blob/master/frontend/app/src/helpers/__test__/helpers.spec.ts)
- Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

**Comment by Fog3211** [comment]
@ecurrencyhodler Can you assign it to me?

**Comment by Ekep-Obasi** [comment]
@ecurrencyhodler could you please assign?

**Comment by okhot** [comment]
@ecurrencyhodler I can help with this

**Comment by ecurrencyhodler** [comment]
Let's get a PR up in 2 days ekep

**Comment by Ekep-Obasi** [comment]
@ecurrencyhodler, please can you clarify the 03 test?

**Comment by ecurrencyhodler** [comment]
Paid! https://community.sphinx.chat/bounty/1621
