### ISSUE TITLE
[Tests][Component] Add Test to src/pages/tickets/Tickets.tsx and src/store/main.ts

### ISSUE THREAD

**Issue by Vayras** [stakwork/sphinx-tribes-frontend#355]
### Context
With this ticket we are increasing the coverage for bounties hompage and also increasing coverage for api endpoints

### File to to test
`src/pages/tickets/Tickets.tsx` and `src/store/main.ts`

### File to create
`src/pages/tickets/_test_/Tickets.spec.tsx and src/store/__test__/main.spec.ts

### Acceptance Criteria
- [ ] Test that the `search` endpoint accepts search query, limits query, languages, filters, and bounty status 
- [ ] Test that the `filter` endpoint accepts search query, limits query, languages, filters, and bounty status
- [ ] Test that newer bounties created are visible on the homepage
- [ ] I have rebased to master
- [ ] I can submit a pr within 2 days of taking the bounty

### References
- Watch this [Jest Youtube playlist](https://www.youtube.com/watch?v=T2sv8jXoP4s&list=PLC3y8-rFHvwirqe1KHFCHJ0RqNuN61SJd) if you are new to testing
- Here is an [example unit test](https://github.com/stakwork/sphinx-tribes/blob/master/frontend/app/src/helpers/__test__/helpers.spec.ts)
- Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

**Comment by okhot** [comment]
Can I get this?

**Comment by Ekep-Obasi** [comment]
@ecurrencyhodler could please assign me?

**Comment by Jeezman** [comment]
@ecurrencyhodler PR ready for review

**Comment by elraphty** [comment]
@aliraza556 comment on this

**Comment by aliraza556** [comment]
@elraphty assign me
