### ISSUE TITLE
Search Box on People Page Not Clear When Clicking `Back Arrow` Button

### ISSUE THREAD

**Issue by aliraza556** [stakwork/sphinx-tribes-frontend#356]
**Describe the bug**
The search box on the People page isn't clear when clicking the back arrow button.

**Bug Demo:**
https://www.loom.com/share/307a38d72e884bb3ba1d925f6005c25c

**To Reproduce**
1. Go to 'https://community.sphinx.chat/p'
2. Click on the search box and search for any developer name.
3. After searching for the developer, click on their name to go to this route:  `https://community.sphinx.chat/p/{uuid}/organizations`
4. Click the back arrow button
5. Observe the bug.

**Expected behavior**
After clicking the back arrow button, the People page should return to its normal state.
https://www.loom.com/share/fb4bb0f3c72b4875be015ea21030ff4d

**Desktop (please complete the following information):**
 - Browser [e.g. chrome]

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a screenshot or video in my PR
- [ ] I have created a test that asserts the search bar is cleared when back arrow button is clicked
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 2 days of taking the bounty

**Comment by aliraza556** [comment]
Hi @ecurrencyhodler,
Please review and assign me to task.

**Comment by MahtabBukhari** [comment]
@ecurrencyhodler Could you assign me?

**Comment by ecurrencyhodler** [comment]
Tested and paid!
