### ISSUE TITLE
Add bounty filters to profile when viewing created or assigned bounties.

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes-frontend#361]
### Context
We are enabling hunters to filter bounties on their profile when viewing created or assigned bounties.

The backend to implement this call was worked on here: https://github.com/stakwork/sphinx-tribes/pull/1579

The default state is to display all bounties and have all the boxes unchecked. The call to focus on one bounty gets made once they select a box in the UI.

### Design
Link to [figma](https://www.figma.com/file/1aL3lgG5Rpkti4b0j42fwf/Bounties---FINAL-DESIGNS?type=design&node-id=11564%3A25967&mode=design&t=8R2VRldxKyurpWlb-1).
Design for created bounties
![My Profile - Bounties](https://github.com/stakwork/sphinx-tribes-frontend/assets/32662508/7c369bd0-c18d-4735-8888-ea19fe83329b)

Design for assigned bounties
![image](https://github.com/stakwork/sphinx-tribes-frontend/assets/13258550/6c05d398-8800-4bba-ab1e-56a8303a6ae1)

### Acceptance Criteria
- [ ] I've tested on Chrome
- [ ] I've submitted a screenshot or recording in my pr
- [ ] I've created a test that the filters are displayed (open/assigned/paid) on created and (assigned paid) for assigned bounties
- [ ] I've created a test that the correct calls are made when boxes are clicked for created bounties tab and assigned bounties tab
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a pr within 2 days of taking the bounty

Here is an [example unit test](https://github.com/stakwork/sphinx-tribes/blob/master/frontend/app/src/helpers/__test__/helpers.spec.ts)

Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

**Comment by okhot** [comment]
@ecurrencyhodler i can help

**Comment by ecurrencyhodler** [comment]
Let's get a pr up in 2 days okhot

**Comment by okhot** [comment]
@elraphty the backend implementation returns a 400 error each time I pass either "open" or "assigned" to the sortBy query. It returns a 200 success code only when I pass "paid" as query param.

Here's the endpoint I'm hitting:
people/wanteds/created/{uuid}?page=1&limit=20&sortBy={param}&search=

Do you please have any ideas on why this might be failing? Thanks

**Comment by elraphty** [comment]
Are you using this format? people/wanteds/created/{uuid}?page=1&limit=20&sortBy={param}&search=&Open=true&Paid=true&Assigned=true
