### ISSUE TITLE
[Tests][Component] Add Test to src/people/widgetViews/summaries/wantedSummaries/CodingBounty.tsx

### ISSUE THREAD

**Issue by Vayras** [stakwork/sphinx-tribes-frontend#362]
### Context
`CodingBounty.tsx` renders the bounty on the page, we are increasing the coverage for this component

### File to to test
`src/people/widgetViews/summaries/wantedSummaries/CodingBounty.tsx`

### File to create
`src/people/widgetViews/summaries/wantedSummaries/_test_/CodingBounty.spec.tsx

### Acceptance Criteria
- [ ] Test that share twitter takes user to templated twitter post
- [ ] Test that clicking on github button takes user to github link
- [ ] Test that When I click on "I can help", the bounty page should persist and not disappear.
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a pr within 2 days of taking the bounty

### References
- Watch this [Jest Youtube playlist](https://www.youtube.com/watch?v=T2sv8jXoP4s&list=PLC3y8-rFHvwirqe1KHFCHJ0RqNuN61SJd) if you are new to testing
- Here is an [example unit test](https://github.com/stakwork/sphinx-tribes/blob/master/frontend/app/src/helpers/__test__/helpers.spec.ts)
- Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

**Comment by MirzaHanan** [comment]
Hi @ecurrencyhodler,
Please assign me?

**Comment by ecurrencyhodler** [comment]
Paid 150k sats! https://community.sphinx.chat/bounty/1624
