### ISSUE TITLE
Default Photo Not Showing in Assigned Bounties on Mobile and Desktop

### ISSUE THREAD

**Issue by aliraza556** [stakwork/sphinx-tribes-frontend#365]
**Describe the bug**
Default Photo Not Showing in Assigned Bounties on Mobile and Desktop

**Bug Demo**
https://www.loom.com/share/302749163c5444c087562145b350079c

**To Reproduce**
1. Go to https://community.sphinx.chat/p/{uuid}/assigned
2. See error

**Expected behavior**
The default face picture should also be displayed. Implement this on desktop and mobile.

**Desktop (please complete the following information):**

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a screenshot or video in my PR
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 2 days of taking the bounty

**Comment by aliraza556** [comment]
Hi @ecurrencyhodler,
Please review and assign me to the task.

**Comment by MirzaHanan** [comment]
Hi @ecurrencyhodler,
assign me?

**Comment by AbdulWahab3181** [comment]
@ecurrencyhodler Could you please assign me

**Comment by ecurrencyhodler** [comment]
I've tested this on staging and it works. Closing for now unless you can provide me a staging profile I can look at that displays this behavior.
