### ISSUE TITLE
[Tests][Component] Add Test to src/pages/tickets/org/OrgTickets.tsx

### ISSUE THREAD

**Issue by Vayras** [stakwork/sphinx-tribes-frontend#366]
### Context
`Wanted.tsx` renders user created bounties, we are increasing coverage for that with this ticket

### File to to test
`src/pages/people/tabs/Wanted.tsx`

### File to create
`src/pages/people/tabs/Wanted.spec.tsx`

### Acceptance Criteria
- [ ] Test that org bounties are scrollable on org home page
- [ ] Test that `post a bounty` button, auto-populates newer bounties on org bounty page and bounties
- [ ] Move the OrgHeader.spec.tsx test from src/people/widgetViews/__tests__/OrgHeader.spec.tsx to src/pages/tickets/__tests__/OrgHeader.spec.tsx 
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a pr within 2 days of taking the bounty

### References
- Watch this [Jest Youtube playlist](https://www.youtube.com/watch?v=T2sv8jXoP4s&list=PLC3y8-rFHvwirqe1KHFCHJ0RqNuN61SJd) if you are new to testing
- Here is an [example unit test](https://github.com/stakwork/sphinx-tribes/blob/master/frontend/app/src/helpers/__test__/helpers.spec.ts)
- Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

**Comment by okhot** [comment]
I can help with this

**Comment by Fog3211** [comment]
assign

**Comment by ecurrencyhodler** [comment]
@okhot it's yours

**Comment by elraphty** [comment]
@AbdulWahab3181 you can take this

**Comment by AbdulWahab3181** [comment]
@elraphty Ok, please assign me

**Comment by elraphty** [comment]
@Vayras what is this issue supposed to test  `OrgTicketsPage` or `Wanted.tsx`?  this section `Test that post a bounty button, auto populates newer bounties on org bounty page and bounties section on profile` is confusing.

**Comment by Vayras** [comment]
@elraphty yeah I think we need to cover the `Test that post a bounty button, auto populates newer bounties on org bounty page and bounties section on profile` in `OrgTicketsPage` , might have been an oversight on my end, Thanks of checking this one

**Comment by elraphty** [comment]
> @elraphty yeah I think we need to cover the `Test that post a bounty button, auto populates newer bounties on org bounty page and bounties section on profile` in `OrgTicketsPage` , might have been an oversight on my end, Thanks of checking this one

That will be difficult to achieve with a component tests, these are 2 entirely different components
