### ISSUE TITLE
Put default org logo photo when editing org with no image

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes-frontend#37]
**Describe the bug**
The wrong red S logo is displayed when editing an org that doesn't have an image.

https://github.com/stakwork/sphinx-tribes-frontend/assets/32662508/081acb09-14a2-4f13-b420-dc920ff6fc25

**Expected behavior**
Replace the red S logo with the default logo image if there is no image.

You can find the Logo image here in [figma](https://www.figma.com/file/1aL3lgG5Rpkti4b0j42fwf/Bounties---FINAL-DESIGNS?type=design&node-id=10359%3A25879&mode=design&t=eOh4ZA44oOjZeKv3-1) if needed.

**Desktop (please complete the following information):**
 - Browser: Chrome

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a screenshot in my PR

**Comment by VividhPandey003** [comment]
Can I work on this @ecurrencyhodler ?

**Comment by ColdMice** [comment]
@ecurrencyhodler can you assign me to this
