### ISSUE TITLE
[GOOD FIRST ISSUE] Make the Navigation Header Responsive

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes-frontend#376]
**Describe the bug**

The Navigation header becomes unresponsive on smaller desktop screens, making the username invisible.

Loom Video

https://www.loom.com/share/c0e9ce48c97542e1b1fc7cb3b61a85c0

- Use CSS media queries to make the navigation header responsive on smaller screens, by reducing text sizes,  and paddings
- Write a test to show that the username is visible from a desktop viewport width of 1440 - 950

**To Reproduce**

Adjust the screen size to various desktop sizes by using developer mode

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a screenshot or video in my PR
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 2 days of taking the bounty

Here is an [example unit test](https://github.com/stakwork/sphinx-tribes/blob/master/frontend/app/src/helpers/__test__/helpers.spec.ts)
Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

**Comment by AbdulWahab3181** [comment]
?

**Comment by Ekep-Obasi** [comment]
@elraphty please assign me

**Comment by elraphty** [comment]
> Could you please assign me?

@AbdulWahab3181 let me give this to @Ekep-Obasi, you will get a couple of test issues next week.

**Comment by elraphty** [comment]
> @elraphty please assign me

Assigned.
