### ISSUE TITLE
[Test][cypress] View bounty modal

### ISSUE THREAD

**Issue by kevkevinpal** [stakwork/sphinx-tribes-frontend#377]
### Context
Currently, we have a cypress command to [create a bounty](https://github.com/stakwork/sphinx-tribes-frontend/blob/master/cypress/support/commands.ts#L108) but we want to assert that we can view the bounty modal after creating it

So what we want to do is use create a bounty and then after open the first bounty on the page to view the modal. We want to assert that a few things in the modal appear

- Bounty owner
- Title
- Description
- Acceptance criteria
- Assignee
- sat amount
- estimated time
- copy link button
- share to twitter button
- mark as paid button
- pay bounty button

### File to create
`sphinx-tribes-frontend/cypress/e2e/4_openBountyModal.cy.ts`
there will be modifications to `sphinx-tribes-frontend/cypress/support/commands.ts`

### Acceptance Criteria

> Given a user is signed in
> When we create a bounty and click on the bounty tile
> Then the test asserts that in the bounty modal the bounty owner appears

> Given a user is signed in
> When we create a bounty and click on the bounty tile
> Then the test asserts that in the bounty modal the bounty title appears

> Given a user is signed in
> When we create a bounty and click on the bounty tile
> Then the test asserts that in the bounty modal the bounty description appears

> Given a user is signed in
> When we create a bounty and click on the bounty tile
> Then the test asserts that in the bounty modal the bounty acceptance criteria appears

> Given a user is signed in
> When we create a bounty and click on the bounty tile
> Then the test asserts that in the bounty modal the bounty assignee appears

> Given a user is signed in
> When we create a bounty and click on the bounty tile
> Then the test asserts that in the bounty modal the bounty sat amount appears

> Given a user is signed in
> When we create a bounty and click on the bounty tile
> Then the test asserts that in the bounty modal the bounty copy link button appears

> Given a user is signed in
> When we create a bounty and click on the bounty tile
> Then the test asserts that in the bounty modal the bounty estimate time appears

> Given a user is signed in
> When we create a bounty and click on the bounty tile
> Then the test asserts that in the bounty modal the bounty share to twitter appears

> Given a user is signed in
> When we create a bounty and click on the bounty tile
> Then the test asserts that in the bounty modal the bounty mark as paid button appears

Modal shown below
![image](https://github.com/stakwork/sphinx-tribes-frontend/assets/15950706/a1989c26-1d5c-4542-80b1-261444026a4f)
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a pr within 2 days of taking the bounty

### References
Example cypress test
`https://github.com/stakwork/sphinx-tribes-frontend/blob/master/cypress/e2e/0_create_bounty.cy.ts`

**Comment by okhot** [comment]
I can help with these

**Comment by kevkevinpal** [comment]
I assigned it to you @okhot let me know if you run into any issues you can refer to this doc

please refer to this if you need to setup cypress locally
https://github.com/stakwork/sphinx-tribes-frontend/blob/master/docs/setupCypressTest.md

**Comment by kevkevinpal** [comment]
> @kevkevinpal I'm facing issues running test locally. I this error when I try to run locally. Any Clues on why?
> 
> ![Screenshot 2024-03-11 at 16 52 34](https://private-user-images.githubusercontent.com/33989423/311770222-a4b230c7-d95d-452a-8bd6-e70cacf0485b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxNzI4NzIsIm5iZiI6MTcxMDE3MjU3MiwicGF0aCI6Ii8zMzk4OTQyMy8zMTE3NzAyMjItYTRiMjMwYzctZDk1ZC00NTJhLThiZDYtZTcwY2FjZjA0ODViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzExVDE1NTYxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkYWE2NzEwMWVmY2EyNDYzNThmZWQxMDg3NTkxZjM5MmVjMWI1OTAzOTY1NTAyODcwNzlkZDcyMDJmZDhjOWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CIpmVKZXPJHnsILIWFltP1C3M46oNgHYSCF6QkUjtgY)

did you setup sphinx stack and move the NODES.json files over to the correct location?

**Comment by okhot** [comment]
Yes I followed the documentation to the letter

**Comment by saithsab877** [comment]
Hi @elraphty, @kevkevinpal,
Please assign me if @okhot  gives up.

**Comment by elraphty** [comment]
@aliraza556 You can take this.

**Comment by aliraza556** [comment]
@elraphty,
Yes
