### ISSUE TITLE
[tests][cypress] Delete bounty

### ISSUE THREAD

**Issue by kevkevinpal** [stakwork/sphinx-tribes-frontend#378]
### Context
Currently, we have a cypress command to [create a bounty](https://github.com/stakwork/sphinx-tribes-frontend/blob/master/cypress/support/commands.ts#L108) but we want to assert that we can delete the bounty after creating it

So what we want to do is use create a bounty and then after open the first bounty on the page to view the modal. We want to assert that when we click on the delete button then the bounty does not exist on the home page anymore

### File to create
`sphinx-tribes-frontend/cypress/e2e/5_deleteBountyFromModal.cy.ts`
there will be modifications to `sphinx-tribes-frontend/cypress/support/commands.ts`

### Acceptance Criteria

> Given a user is signed in
> When we create a bounty and click on the bounty tile
> Then the test asserts that we can delete the bounty

delete button shown below
![image](https://github.com/stakwork/sphinx-tribes-frontend/assets/15950706/63a12ac4-1325-4db7-876a-a1252b6c510e)
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a pr within 2 days of taking the bounty

### References
Example cypress test
`https://github.com/stakwork/sphinx-tribes-frontend/blob/master/cypress/e2e/0_create_bounty.cy.ts`

**Comment by MahtabBukhari** [comment]
@kevkevinpal Could you assign me?

**Comment by kevkevinpal** [comment]
I assigned it to you @Knight0p6 let me know if you run into any issues you can refer to this doc

please refer to this if you need to setup cypress locally
https://github.com/stakwork/sphinx-tribes-frontend/blob/master/docs/setupCypressTest.md

**Comment by aliraza556** [comment]
Hi @elraphty, @kevkevinpal,
Assign me

**Comment by elraphty** [comment]
> Hi @elraphty, @kevkevinpal, Please assign me if @Knight0p6 gives up.

It's over 2 days already @kevkevinpal, I'm reassigning to @aliraza556
