### ISSUE TITLE
Enable "no results" state for filters when appropriate

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes-frontend#38]
**Describe the bug**
Currently when a filter is selected that has no results, a pending circle appears indefinitely.

![sphinx fri 26 jan 11 04 04](https://github.com/stakwork/sphinx-tribes-frontend/assets/32662508/ca274805-ec67-4dea-8dd9-bfcd202fccea)

**Expected behavior**
Let's display a "no results" text instead.

![sphinx fri 26 jan 11 05 48](https://github.com/stakwork/sphinx-tribes-frontend/assets/32662508/33b9927a-9e65-459a-9124-f87a7c492093)

**Desktop (please complete the following information):**
 - Browser: Chrome

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a video in my PR
- [ ] I have created a test that asserts the no results text will be displayed if there are no bounties that meet that criteria

**Comment by ChetanKarwa** [comment]
I would like to work on this

**Comment by bilalshaikh292** [comment]
assign

**Comment by ecurrencyhodler** [comment]
Sorry @bilalshaikh292 this goes to chetan because he reported the issue and asked for a bounty when he sent it to me.

**Comment by bilalshaikh292** [comment]
ok @ecurrencyhodler
