### ISSUE TITLE
[BUG FIX] Bounty doesn't navigate to the right page after creation when a user is assigned

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes-frontend#382]
**Describe the bug**

When a bounty is created with a user assigned in the creation process the bounty navigates to the first open bounty on the bounties list after creation, it navigates to the right page only when a user is not assigned during creation.

When a bounty is created and a user is assigned, it should navigate to the right page of the newly created bounty `${host}/bounty/${id}`

Loom Video

https://www.loom.com/share/462fdecc53c346c290767709bf7defe6

### Acceptance Criteria

- [ ] I have tested on Chrome desktop
- [ ] I have posted a screenshot or video in my PR
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 2 days of taking the bounty

Here is an [example unit test](https://github.com/stakwork/sphinx-tribes/blob/master/frontend/app/src/helpers/__test__/helpers.spec.ts)
Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

**Comment by okhot** [comment]
S

**Comment by chiragDork** [comment]
Can you please assign this to me
