### ISSUE TITLE
[Test][cypress] View Organization Bounties

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes-frontend#383]
### Context

Currently, we have a cypress command to [create a bounty](https://github.com/stakwork/sphinx-tribes-frontend/blob/master/cypress/support/commands.ts#L108) but we want to assert that we can create a bounty linked to an organization, and view all the bounties created by the organization. 

So what we want to do is use [Create org](https://github.com/stakwork/sphinx-tribes-frontend/blob/master/cypress/support/commands.ts#L252) and create a new bounty with an org, we also want to assert that the bounty appears and it has the org label on it, and when the organization label is clicked it leads the user to the organization bounties page.

### File to create
`sphinx-tribes-frontend/cypress/e2e/7_viewOrgBounties.cy.ts`
there will be modifications to `sphinx-tribes-frontend/cypress/support/commands.ts`

### Acceptance Criteria

> Given a user is signed in and an org is created
> When we create a bounty attached to the org
> Then the test asserts that the bounty tile has the org label attached and is clickable
> Then test that when the label is clicked it leads to an organization bounties page, and has the newly created bounty on the list of bounties

The label is shown below
![image](https://github.com/stakwork/sphinx-tribes-frontend/assets/15950706/2400b6e3-03e9-45da-b1be-39999932e688)

- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 2 days of taking the bounty

### References
Example cypress test
`https://github.com/stakwork/sphinx-tribes-frontend/blob/master/cypress/e2e/0_create_bounty.cy.ts`

**Comment by chiragDork** [comment]
Can you please assign this to me
