### ISSUE TITLE
[tests][cypress] Assign Hunter

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes-frontend#386]
### Context

Currently, we have a cypress command to [create a bounty](https://github.com/stakwork/sphinx-tribes-frontend/blob/master/cypress/support/commands.ts#L108), but we want to assert that we can create a bounty without assigning a hunter, and then assign the hunter afterward

So, create a bounty without assigning a hunter and click on the newly created bounty to view it on the bounty modal. We want to assert that when we click on `Not Assigned`, we can assign a bounty hunter to the bounty.

### File to create
`sphinx-tribes-frontend/cypress/e2e/8_assign_hunter.cy.ts`
there will be no modifications to `sphinx-tribes-frontend/cypress/support/commands.ts`

### Acceptance Criteria

> Given a user is signed in
> When we create a bounty without an assignee and click on the bounty tile
> Then the test asserts that we can assign a bounty hunter to the bounty
> Then assert that the assignee on the bounty is equal to the hunter that was assigned

The edit button is shown below
![image](https://i.ibb.co/CBGnBT0/Screenshot-2024-03-12-at-12-12-36.png)

- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 2 days of taking the bounty

### References
Example cypress test
`https://github.com/stakwork/sphinx-tribes-frontend/blob/master/cypress/e2e/0_create_bounty.cy.ts`

**Comment by AbdulWahab3181** [comment]
assihn?
