### ISSUE TITLE
[tests][cypress] UnAssign Hunter

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes-frontend#388]
### Context

Currently, we have a cypress command to [create a bounty](https://github.com/stakwork/sphinx-tribes-frontend/blob/master/cypress/support/commands.ts#L108), but we want to assert that we can unassign a bounty hunter after creating the bounty with an assignee

So, create a bounty with an assignee and click on the newly created bounty to view it on the bounty modal. We want to assert that when we click on the `x` icon beside the bounty assignee name and unassign the assignee of the bounty.

### File to create
`sphinx-tribes-frontend/cypress/e2e/9_unassign_hunter.cy.ts`
there will be no modifications to `sphinx-tribes-frontend/cypress/support/commands.ts`

### Acceptance Criteria

> Given a user is signed in
> When we create a bounty with an assignee and click on the bounty tile
> Then the test asserts that we can unassign a bounty hunter to the bounty
> Then assert that the bounty has no assignee

The edit button is shown below
![image](https://i.ibb.co/CBGnBT0/Screenshot-2024-03-12-at-12-12-36.png)

- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 2 days of taking the bounty

### References
Example cypress test
`https://github.com/stakwork/sphinx-tribes-frontend/blob/master/cypress/e2e/0_create_bounty.cy.ts`

**Comment by NengakDakup** [comment]
@elraphty can i take this

**Comment by elraphty** [comment]
> @elraphty can i take this

I'm working on this myself. Have you tried running the cypress test locally?

**Comment by NengakDakup** [comment]
> > @elraphty can i take this
> 
> I'm working on this myself. Have you tried running the cypress test locally?

Ohhh, okay
Yeah I've tried running some cypress tests before

**Comment by elraphty** [comment]
> > > @elraphty can i take this
> > 
> > 
> > I'm working on this myself. Have you tried running the cypress test locally?
> 
> Ohhh, okay Yeah I've tried running some cypress tests before

Okay, I will create some cypress issues after doing these.
