### ISSUE TITLE
[tests][cypress] Pay Bounty Full Node

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes-frontend#390]
### Context

Currently, we have a cypress command to [create a bounty](https://github.com/stakwork/sphinx-tribes-frontend/blob/master/cypress/support/commands.ts#L108) and create an organization [create org](https://github.com/stakwork/sphinx-tribes-frontend/blob/master/cypress/support/commands.ts#L252C1-L294C4)

but we want to assert that we can create an organization, fund the organization, create a bounty tied to the organization, and pay the bounty.

So, create a bounty with an assignee after an organization is created and funded with an assignee, and click on the newly created bounty to view it on the bounty modal. We want to assert that when we click the `Pay Bounty` button, the bounty gets paid, and the bounty status is changed to PAID.

### File to create
`sphinx-tribes-frontend/cypress/e2e/10_pay_bounty.cy.ts`
there will be modifications to `sphinx-tribes-frontend/cypress/support/commands.ts`

### Acceptance Criteria

> Given a user is signed in
> Create an organization
> Fund the organization
> Create a bounty with the organization selected and a full node user selected as the assignee
> When we create a bounty with an assignee and click on the bounty tile
> Then the test asserts that we can pay the bounty
> Then assert that the bounty status is changed to PAID

The `Pay Bounty` button is shown below
![image](https://i.ibb.co/6bLCXLS/Screenshot-2024-03-12-at-16-53-44.png)

- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 2 days of taking the bounty

### References
Example cypress test
`https://github.com/stakwork/sphinx-tribes-frontend/blob/master/cypress/e2e/0_create_bounty.cy.ts`

**Comment by NengakDakup** [comment]
@elraphty can i give it a go?

**Comment by elraphty** [comment]
> @elraphty can i give it a go?

@NengakDakup this one is pretty complicated, I have to do this one myself. I will create some good first cypress tests today/ tomorrow.
