### ISSUE TITLE
[tests][cypress] Mark Bounty As Paid

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes-frontend#393]
### Context

Currently, we have a cypress command to [create a bounty](https://github.com/stakwork/sphinx-tribes-frontend/blob/master/cypress/support/commands.ts#L108)

but we want to assert that we can mark a bounty as paid using the `Mark As Paid` button.

So, create a bounty with an assignee, and click on the newly created bounty to view it on the bounty modal. We want to assert that when we click the `Mark As Paid` button the bounty status is changed to PAID.

### File to create
`sphinx-tribes-frontend/cypress/e2e/11_mark_as_paid.cy.ts`
there will be no modifications to `sphinx-tribes-frontend/cypress/support/commands.ts`

### Acceptance Criteria

-  Given a user is signed in
-  Create a bounty with an assignee
-  When we create a bounty with an assignee and click on the bounty tile
-  Then asserts that we can mark a bounty as paid by clicking the `Mark As Paid ` button without selecting a badge
-  Then assert that the bounty status is changed to PAID

The `Mark As Paid` button is shown below
![image](https://i.ibb.co/6bLCXLS/Screenshot-2024-03-12-at-16-53-44.png)

- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 2 days of taking the bounty

### References
Example cypress test
`https://github.com/stakwork/sphinx-tribes-frontend/blob/master/cypress/e2e/0_create_bounty.cy.ts`

**Comment by NengakDakup** [comment]
@elraphty  Can i give this a try?

**Comment by AbdulWahab3181** [comment]
assign me?

**Comment by elraphty** [comment]
> @elraphty Can i give this a try?

Okay.

**Comment by elraphty** [comment]
> @elraphty Can i give this a try?

What's ur Sphinx username?

**Comment by NengakDakup** [comment]
> > @elraphty Can i give this a try?
> 
> What's ur Sphinx username?

Nen
