### ISSUE TITLE
[tests][cypress] Mark Bounty As UnPaid

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes-frontend#394]
### Context

Currently, we have a cypress command to [create a bounty](https://github.com/stakwork/sphinx-tribes-frontend/blob/master/cypress/support/commands.ts#L108)

but we want to assert that we can mark a bounty as unpaid using the `Mark As UnPaid` button.

So, create a bounty with an assignee, and click on the newly created bounty to view it on the bounty modal. We want to assert that when we click the `Mark As UnPaid` button for a paid bounty, the bounty status is changed to UNPAID.

### File to create
`sphinx-tribes-frontend/cypress/e2e/12_mark_as_unpaid.cy.ts`
there will be no modifications to `sphinx-tribes-frontend/cypress/support/commands.ts`

### Acceptance Criteria

-  Given a user is signed in
-  Create a bounty with an assignee
-  When we create a bounty with an assignee and click on the bounty tile
-  Then asserts that we can mark a bounty as paid by clicking the `Mark As Paid ` button without selecting a badge
-  Then assert that the bounty status is changed to PAID
-  Then assert that clicking the `Mark As Unpaid` button marks the button as unpaid

The `Mark As UnPaid` button is shown below
![image](https://i.postimg.cc/ysHK9Lf4/Screenshot-2024-03-13-at-11-02-06.png)

- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 2 days of taking the bounty

### References
Example cypress test
`https://github.com/stakwork/sphinx-tribes-frontend/blob/master/cypress/e2e/0_create_bounty.cy.ts`

**Comment by aliraza556** [comment]
HI @elraphty,
Could you assign me?

**Comment by AbdulWahab3181** [comment]
assign me?

**Comment by elraphty** [comment]
> HI @elraphty, Could you assign me?

@aliraza556 have you written a Cypress test before now?

**Comment by aliraza556** [comment]
> > HI @elraphty, Could you assign me?
> 
> @aliraza556 have you written a Cypress test before now?

Yes, not here, but there are other issues...

**Comment by aliraza556** [comment]
@elraphty, I have set up the project according to this document: https://github.com/stakwork/sphinx-tribes-frontend/blob/master/docs/setupCypressTest.md. I am just waiting for you to assign me tasks so that I can then write a unit test.
