### ISSUE TITLE
Display all coding languages in the people page

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes-frontend#40]
**Describe the bug**
Right now, not all skills are viewable on the people page:
![sphinx fri 26 jan 12 51 13](https://github.com/stakwork/sphinx-tribes-frontend/assets/32662508/49bc5235-94a7-4d47-824a-74469be64387)

**Expected behavior**
Enable the ability to view all languages

**Desktop (please complete the following information):**
 - Browser: Chrome

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a video in my PR
- [ ] I've created a component test that asserts all coding languages are viewable when I click on the filter

**Comment by ChetanKarwa** [comment]
I would like to fix this
