### ISSUE TITLE
[Test][cypress] Create And View Bounties On Profile Page

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes-frontend#402]
### Context

Currently, we have a cypress command to [create a bounty](https://github.com/stakwork/sphinx-tribes-frontend/blob/master/cypress/support/commands.ts#L108) but we want to assert that we can create a bounty on the user profile page and view them.

So what we want to do is use [Login User](https://github.com/stakwork/sphinx-tribes-frontend/blob/master/cypress/support/commands.ts#L43C1-L99C1) to create a user profile, click on the user icon, click on the Bounties tab on the user profile page, then create 2 new bounties.

### File to create
`sphinx-tribes-frontend/cypress/e2e/15_profile_create_bounties.cy.ts`
there will be modifications to `sphinx-tribes-frontend/cypress/support/commands.ts`

### Acceptance Criteria

- Given a user is signed in
- Click on the User profile icon/username, to lead you to the user profile
- Click on the Bounties ${count} tab on the user profile page 
- Click on the Post a Bounty button
- Follow the Bounty creation steps and create 2 bounties
- Then Assert that the 2 newly created bounties are visible on the user profile Bounties tab

The created bounties page is shown below

![image](https://i.ibb.co/2s4jKc9/Screenshot-2024-03-14-at-14-35-23.png)

- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 2 days of taking the bounty

### References
Example cypress test
`https://github.com/stakwork/sphinx-tribes-frontend/blob/master/cypress/e2e/0_create_bounty.cy.ts`

**Comment by AbdulWahab3181** [comment]
.

**Comment by chiragDork** [comment]
Hi @elraphty can you please assign me

**Comment by elraphty** [comment]
> @elraphty Could you please assign me?

sure @AbdulWahab3181, assigning
