### ISSUE TITLE
[tests][cypress] Create Organization Characters Restrictions On Name, And Description Fields

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes-frontend#403]
### Context

Currently, we have a cypress command to [create an organization](https://github.com/stakwork/sphinx-tribes-frontend/blob/c43ec7bdaed3e529975108e187987aaa6c5ade7d/cypress/e2e/2_create_org.cy.ts) but we want to assert that when we pass more than 20 characters for the organization title, or pass more than 120 characters for the organization description the Add Organization Button is disabled, and the title input and description textarea shows a character exceeded error.

So what we want to do is use [Login User](https://github.com/stakwork/sphinx-tribes-frontend/blob/master/cypress/support/commands.ts#L43C1-L99C1) to create a user profile, click on the user icon, click on the Add Organization button and create an organization with a title greater than 20 characters and description greater than 120 characters.

### File to create
`sphinx-tribes-frontend/cypress/e2e/16_error_creating_organizations.cy.ts`
there will be no modifications to `sphinx-tribes-frontend/cypress/support/commands.ts`

### Acceptance Criteria

- Given a user is signed in
- Click on the User profile icon/username, to lead you to the user profile
- Click on the Organizations tabs
- Click on the Add Organization button
- Create an organization with title, and description exceeding the specified character limits
- Then Assert that the Add Organization button is disabled, and title input and description text areas display an error.

The organization inputs are shown below

![image](https://i.ibb.co/PwnFdhm/Screenshot-2024-03-14-at-15-20-37.png)

- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 2 days of taking the bounty

### References
Example cypress test
`https://github.com/stakwork/sphinx-tribes-frontend/blob/master/cypress/e2e/0_create_bounty.cy.ts`

**Comment by gouravmpk** [comment]
Assign

**Comment by MirzaHanan** [comment]
@elraphty Could you please assign me?

**Comment by elraphty** [comment]
> Assign

@gouravmpk written a cypress test once? and can you deliver this within 2 days?

**Comment by elraphty** [comment]
> @elraphty Could you please assign me?

@MirzaHanan assigned
