### ISSUE TITLE
[tests][cypress] Add User To An Organization And Give The User Roles

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes-frontend#404]
### Context

Currently, we have a cypress command to [create an organization](https://github.com/stakwork/sphinx-tribes-frontend/blob/c43ec7bdaed3e529975108e187987aaa6c5ade7d/cypress/e2e/2_create_org.cy.ts) we want to assert that when we can add a user to an organization by clicking the `Add User` button and following the add user flow.

So what we want to do is use [Login User](https://github.com/stakwork/sphinx-tribes-frontend/blob/master/cypress/support/commands.ts#L43C1-L99C1) to create a user profile, click on the user icon, click on the `Add Organization `button and create an organization, then click on the `Manage` button of the newly created organization which will lead you to the `OrganizationDetails` page then click on `Add User` button to add an organization user.

### File to create
`sphinx-tribes-frontend/cypress/e2e/17_create_org_user.cy.ts`
there will be no modifications to `sphinx-tribes-frontend/cypress/support/commands.ts`

### Acceptance Criteria

- Given a user is signed in
- Click on the User profile icon/username, to lead you to the user profile
- Click on the Organizations tabs
- Click on the Add Organization button
- Create an organization 
- Click on the `Manage` button
- Click on the `Add User` button
- Search for a user by typing in a username in the search input
- Select the returned user
- Add default roles to the organization user
- Then assert that the user is on the organization user's list
- Also assert that the default roles are checked when you click on the settings icon.

The add user flow is shown below

![image](https://i.ibb.co/C18TFnW/Screenshot-2024-03-14-at-17-20-55.png)
![image](https://i.ibb.co/P6hSpYS/Screenshot-2024-03-14-at-17-21-04.png)

- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 2 days of taking the bounty

### References
Example cypress test
`https://github.com/stakwork/sphinx-tribes-frontend/blob/master/cypress/e2e/0_create_bounty.cy.ts`

**Comment by AbdulWahab3181** [comment]
,

**Comment by elraphty** [comment]
> @elraphty I have completed my first Cypress Test , I think I can take this

Okay @Vayras, successfully ran Cypress on your system?

**Comment by MahtabBukhari** [comment]
@elraphty could you assign me?

**Comment by MahtabBukhari** [comment]
@elraphty I have setup the locally and currently i have not any ticket

**Comment by Vayras** [comment]
> > @elraphty I have completed my first Cypress Test , I think I can take this
> 
> Okay @Vayras, successfully ran Cypress on your system?

Yeah I have a other windows machine, to run tests locally

**Comment by elraphty** [comment]
> > > @elraphty I have completed my first Cypress Test , I think I can take this
> > 
> > 
> > Okay @Vayras, successfully ran Cypress on your system?
> 
> Yeah I have a other windows machine, to run tests locally

okay.
