### ISSUE TITLE
[tests][cypress] Withdraw Budget From An Organization

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes-frontend#410]
### Context

Currently, we have a cypress command to [create an organization](https://github.com/stakwork/sphinx-tribes-frontend/blob/master/cypress/support/commands.ts#L252C1-L294C4)

but we want to assert that we can withdraw sats from an organization by clicking the `Withdraw` button, inputting a Ligtning Payment Requer, and paying the lightning invoice to withdraw from the organization.

So, create an organization, and click the  `Manage` button on the newly created organization to view the organization details, We want to assert that when we click the `Withdraw` button we can follow the withdraw flow and withdraw budget from the created organization.

### File to create
`sphinx-tribes-frontend/cypress/e2e/18_withdrawOrgBudget.cy.ts`
there will be no modifications to `sphinx-tribes-frontend/cypress/support/commands.ts`

### Acceptance Criteria

-  Given a user is signed in
-  Create an organization
-  Click on the created organization `Manage` button
-  Click on the `Deposit` button
-  Input the amount of sats you want to deposit 
-  Pay the Lightning invoice
-  Assert that the SATS amount was added to the organization's budget
-  Click on the Withdraw button
-  Input a Lightning invoice
-  Pay the invoice
-  Assert that the SATS amount was removed from the organization's budget

The `Withdraw` budget flow  is shown below

![image](https://i.ibb.co/N2SC8B6/Screenshot-2024-03-15-at-12-32-22.png)
![image](https://i.ibb.co/tJvHnzZ/Screenshot-2024-03-15-at-12-33-21.png)

- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 2 days of taking the bounty

### References
Example cypress test
`https://github.com/stakwork/sphinx-tribes-frontend/blob/master/cypress/e2e/0_create_bounty.cy.ts`

**Comment by aliraza556** [comment]
Hi @elraphty,
assign me

**Comment by AbdulWahab3181** [comment]
Could you please assign me?

**Comment by elraphty** [comment]
This is payment-related and requires some internal tools to generate invoices, so I will have to do this myself, but I'm creating other Cypress bounties already.
