### ISSUE TITLE
[tests][cypress] Remove Organization User Roles

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes-frontend#411]
### Context

Currently, we have a cypress command to [create an organization](https://github.com/stakwork/sphinx-tribes-frontend/blob/c43ec7bdaed3e529975108e187987aaa6c5ade7d/cypress/e2e/2_create_org.cy.ts) we want to assert that an organization admin can remove roles from a user when they click on the user `settings icon`

So what we want to do is use [Login User](https://github.com/stakwork/sphinx-tribes-frontend/blob/master/cypress/support/commands.ts#L43C1-L99C1) to create a user profile, click on the user icon, click on the `Add Organization `button and create an organization, then click on the `Manage` button of the newly created organization which will lead you to the `OrganizationDetails` page then click on `Add User` button to add an organization user, after adding the user click on the user `settings icon` and uncheck the `Withdraw from organization` permission

### File to create

`sphinx-tribes-frontend/cypress/e2e/19_manageUserRoles.cy.ts`
there will be no modifications to `sphinx-tribes-frontend/cypress/support/commands.ts`

### Acceptance Criteria

- Given a user is signed in
- Click on the User profile icon/username, to lead you to the user profile
- Click on the Organizations tabs
- Click on the Add Organization button
- Create an organization 
- Click on the `Manage` button
- Click on the `Add User` button
- Search for a user by typing in a username in the search input
- Select the returned user
- Add default roles to the organization user
- Then assert that the user is on the organization user's list
- Click on the settings icon.
- Uncheck  `Withdraw from organization` permission
- Close the Roles Modal
- Click on the settings icon.
- Assert that `Withdraw from organization` is unchecked for the user

The add user flow is shown below

![image](https://i.ibb.co/C18TFnW/Screenshot-2024-03-14-at-17-20-55.png)
![image](https://i.ibb.co/gzqqGJZ/Screenshot-2024-03-15-at-13-15-05.png)
![image](https://i.ibb.co/P6hSpYS/Screenshot-2024-03-14-at-17-21-04.png)

- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 2 days of taking the bounty

### References
Example cypress test
`https://github.com/stakwork/sphinx-tribes-frontend/blob/master/cypress/e2e/0_create_bounty.cy.ts`

**Comment by AbdulWahab3181** [comment]
Could you please assign me?

**Comment by aliraza556** [comment]
assign

**Comment by elraphty** [comment]
> Assign

@Zoe-AE-ND I will get you a good first cypress issue since you have not made any Cypress PR yet.

**Comment by elraphty** [comment]
> Could you please assign me?

Assigning
