### ISSUE TITLE
[tests][cypress] Edit Organization Characters Restrictions On Name, And Description Fields

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes-frontend#414]
### Context

Currently, we have a cypress command to [create an organization](https://github.com/stakwork/sphinx-tribes-frontend/blob/c43ec7bdaed3e529975108e187987aaa6c5ade7d/cypress/e2e/2_create_org.cy.ts) we want to assert that when we try to edit an organization. If we pass more than 20 characters for the organization title or more than 120 characters for the organization description the Edit Organization Button is disabled. The title input and description textarea show a character exceeded error.

So what we want to do is use [Login User](https://github.com/stakwork/sphinx-tribes-frontend/blob/master/cypress/support/commands.ts#L43C1-L99C1) to create a user profile, click on the user icon, click on the Add Organization button and create an organization, click on the `Manage` but on the newly created organization, click on the `Edit` button, and try to edit the organization with characters that exceed the limits.

### File to create
`sphinx-tribes-frontend/cypress/e2e/21_errorEditingOrg.cy.ts`
there will be no modifications to `sphinx-tribes-frontend/cypress/support/commands.ts`

### Acceptance Criteria

- Given a user is signed in
- Click on the User profile icon/username, to lead you to the user profile
- Click on the Organizations tabs
- Click on the Add Organization button
- Create an organization 
- Click on the `Manage` button of the newly created organization
- Click on the `Edit` button
- Pass characters that exceed the title input and description text area limit.
- Then Assert that the Edit Organization button is disabled, and title input and description text areas display an error.

The organization inputs are shown below

![image](https://i.ibb.co/s51V41M/Screenshot-2024-03-15-at-14-20-51.png)

- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 2 days of taking the bounty

### References
Example cypress test
`https://github.com/stakwork/sphinx-tribes-frontend/blob/master/cypress/e2e/0_create_bounty.cy.ts`

**Comment by chiragDork** [comment]
Assign

**Comment by MuhammadUmer44** [comment]
@elraphty,
assign me

**Comment by MahtabBukhari** [comment]
@elraphty Could you assign me?
