### ISSUE TITLE
[tests][cypress] View Bounties From OrganizationDetails Page

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes-frontend#415]
### Context

Currently, we have a cypress command to [create a bounty](https://github.com/stakwork/sphinx-tribes-frontend/blob/master/cypress/support/commands.ts#L108) but we want to assert that we can create a bounty linked to an organization, and view all the bounties created by the organization. 

So what we want to do is use [Create org](https://github.com/stakwork/sphinx-tribes-frontend/blob/master/cypress/support/commands.ts#L252) and create 4 bounties with the newly created org,  navigate to the user's profile, click on the `Manage` button of the created organization, and click on the `View Bounties` button which will redirect to the Organization's bounties page.

### File to create

`sphinx-tribes-frontend/cypress/e2e/22_viewOrgBountiesFromOrg.cy.ts`
there will be modifications to `sphinx-tribes-frontend/cypress/support/commands.ts`

### Acceptance Criteria

- Given a user is signed in and an org is created
- When we create 4 bounties attached to the same org
- Then navigate to the Organizations tab on the user's profile
- Click on the `Manage` button on the organization
- Then click on the `View Bounties` button
- Assert that the 4 bounties created and present on the Organization's Bounties list
- Assert that the Bounties created have the Organization label
- Also Assert that the Organization's name, description, and website are also visible on the page.

The `View Bounties` button is shown below.

![image](https://i.ibb.co/gzqqGJZ/Screenshot-2024-03-15-at-13-15-05.png)

- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 2 days of taking the bounty

### References
Example cypress test
`https://github.com/stakwork/sphinx-tribes-frontend/blob/master/cypress/e2e/0_create_bounty.cy.ts`

**Comment by MuhammadUmer44** [comment]
.

**Comment by AbdulWahab3181** [comment]
Could you please assign me?

**Comment by NengakDakup** [comment]
Hi @elraphty can you assign me?

**Comment by MahtabBukhari** [comment]
@elraphty Could you assign me?
