### ISSUE TITLE
Add load more button on org page to be similar to home page

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes-frontend#42]
### Context
Add load more button on org page to be similar to home page. Here is an example org: https://people-test.sphinx.chat/org/bounties/clf6qmo4nncmf23du7ng

Pagination is now available for orgs. The call is: https://people-test.sphinx.chat/organizations/bounties/{org-uuid}

### Design
This design with the button at the bottom except all bounties displayed should be from the same org.
<img width="1185" alt="Screenshot 2024-01-08 at 10 15 17 AM" src="https://github.com/stakwork/sphinx-tribes/assets/32662508/ca991910-f48b-487c-80b2-287076d8a127">

### Acceptance Criteria
- [ ] I've tested on Chrome
- [ ] I've submitted a screenshot or recording in my pr
- [ ] I've created a component test that the "load more" is visible
- [ ] When I click on the button, it makes a request

Here is an [example unit test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

**Comment by Fog3211** [comment]
can i take this?

**Comment by gouravmpk** [comment]
Assign

**Comment by ecurrencyhodler** [comment]
It's currently blocked! You can see it with the label. You can find open bounties here @adeel-ahmad-sh https://community.sphinx.chat/bounties

**Comment by MirzaHanan** [comment]
@ecurrencyhodler assign me?

**Comment by ecurrencyhodler** [comment]
This is yours mirza!

**Comment by ecurrencyhodler** [comment]
@MirzaHanan do you have an update on this issue?

**Comment by Fog3211** [comment]
> @MirzaHanan do you have an update on this issue?

Can you assign it to me if [@MirzaHanan](https://github.com/MirzaHanan) cannot complete it?

**Comment by aliraza556** [comment]
Hi @ecurrencyhodler and @Fog3211, I have completed it; just the testing remains as I encountered some errors. I will submit it today.

**Comment by MirzaHanan** [comment]
Hi @ecurrencyhodler and @Fog3211, I have completed it; just the testing remains as I encountered some errors. I will submit it today.

**Comment by MirzaHanan** [comment]
HI @ecurrencyhodler @kevkevinpal ,
Please review this PR #171
