### ISSUE TITLE
[Test][Cypress] Create org bounty from organization page.

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes-frontend#424]
### Context
Currently, we have a cypress command to [create a bounty](https://github.com/stakwork/sphinx-tribes-frontend/blob/master/cypress/support/commands.ts#L108) but we want to assert that we can create a bounty linked to an organization from the organization page.

So what we want to do is use [Create org](https://github.com/stakwork/sphinx-tribes-frontend/blob/master/cypress/support/commands.ts#L252) and create a new bounty with an org, we also want to assert that the bounty appears and it has the org label on it, then navigate to the org page and create a bounty from the org page.

### File to create
`sphinx-tribes-frontend/cypress/e2e/24_createOrgPageBounty.cy.ts`
there will be modifications to `sphinx-tribes-frontend/cypress/support/commands.ts`

### Acceptance Criteria

- Given a user is signed in and an org is created
- We create a bounty attached to the org
- Then the test asserts that the bounty tile has the org label attached and is clickable
- Click on the org label to navigate to the org page
- Click on the `Post a Bounty` button
- Assert that the organization is selected by default on the organization dropdown
- Create a bounty from the Org page
- Then assert that the bounty created from the org page is present in the org bounties list.

Org add bounty modal is shown below

![image](https://i.ibb.co/QkVRCwn/Screenshot-2024-03-18-at-15-08-41.png)

- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 2 days of taking the bounty

### References
Example cypress test
`https://github.com/stakwork/sphinx-tribes-frontend/blob/master/cypress/e2e/0_create_bounty.cy.ts`

**Comment by aliraza556** [comment]
Assign

**Comment by MahtabBukhari** [comment]
@elraphty Could you assign any cypress issue to me?
