### ISSUE TITLE
[tests][cypress] View User Assigned Bounties

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes-frontend#429]
### Context

Currently, we have a cypress command to [create a bounty](https://github.com/stakwork/sphinx-tribes-frontend/blob/master/cypress/support/commands.ts#L108) we want to assert that when a user is assigned to a bounty, the bounty is visible on the user assigned page after a bounty is created successfully.

We want to create 3 bounties assigned to the same user and then go to the people's page, search for the bounties assignee, click on the assignee, and see the 3 bounties visible on the Assigned Bounties list.

### File to create

`sphinx-tribes-frontend/cypress/e2e/28_viewAssignedBounties.cy.ts`
there will be no modifications to `sphinx-tribes-frontend/cypress/support/commands.ts`

### Acceptance Criteria

- Given a user is signed in
- When we create 3 bounties with a user assigned
- Search for the user on the peoples' page
- Click on the user which will lead to the user profile page
- Click on the `Assigned Bounties` tab
- Then assert that the created bounties are on the user-assigned bounties list

The user-assigned page is shown below

![image](https://i.ibb.co/7ys8rzx/Screenshot-2024-03-18-at-16-23-49.png)

- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 2 days of taking the bounty

### References

Example cypress test
`https://github.com/stakwork/sphinx-tribes-frontend/blob/master/cypress/e2e/0_create_bounty.cy.ts`

**Comment by AbdulWahab3181** [comment]
Could you please assign me?

**Comment by MahtabBukhari** [comment]
assign

**Comment by elraphty** [comment]
@MahtabBukhari  you can have this one

**Comment by MahtabBukhari** [comment]
> @MahtabBukhari you can have this one

Thanks

**Comment by MuhammadUmer44** [comment]
@elraphty,
Next please assign me.
