### ISSUE TITLE
[tests][cypress] Load More For Created And Assigned Bounties

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes-frontend#436]
### Context

Currently, we have a cypress command to [create a bounty](https://github.com/stakwork/sphinx-tribes-frontend/blob/master/cypress/support/commands.ts#L108) we want to assert that when a user can load more bounties when the bounties created or assigned are more than 20.

We want to create 30 bounties assigned to the same user and then go to the people's page, search for the bounties assignee, click on the assignee, and see the 20  bounties visible on the Assigned Bounties list, when we scroll down to the bottom of the page we see a `Load More` button, it reveals the remaining 10 bounties, then we click on the active user profile image and select the `Bounties` tab, we should see 20 bounties, when we go to the bottom of the page and click on the `Load More` button we should see the remaining 10 bounties.

### File to create

`sphinx-tribes-frontend/cypress/e2e/30_viewUserLoadMore.cy.ts`
there will be no modifications to `sphinx-tribes-frontend/cypress/support/commands.ts`

### Acceptance Criteria

- Given a user is signed in
- When we create 30 bounties with a user-assigned
- Search for the user on the peoples' page
- Click on the user which will lead to the user profile page
- Click on the `Assigned Bounties` tab
- Then assert that 20 bounties are visible on the assigned list
- Then we click the `Load More` button and assert that 30 bounties are now in the document.
- Then click on the login user profile image
- Click on the user `Bounties` tab
- Then assert that 20 bounties are visible on the bounties list
- Then we click the `Load More` button and assert that 30 bounties are now in the user bounties list.

The Load More buttons are shown below

![image](https://i.ibb.co/SNQwCrt/Screenshot-2024-03-19-at-14-32-11.png)
![image](https://i.ibb.co/3YdrWsB/Screenshot-2024-03-19-at-14-31-52.png)

- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 2 days of taking the bounty

### References

Example cypress test
`https://github.com/stakwork/sphinx-tribes-frontend/blob/master/cypress/e2e/0_create_bounty.cy.ts`

**Comment by MahtabBukhari** [comment]
@elraphty Could you assign me?

**Comment by elraphty** [comment]
@NengakDakup you can have this one

**Comment by MuhammadUmer44** [comment]
@elraphty next assign me

**Comment by MuhammadUmer44** [comment]
@elraphty next assign me

**Comment by elraphty** [comment]
> @NengakDakup you can have this one

@NengakDakup you have to comment on this so I can assign you.

**Comment by MuhammadUmer44** [comment]
So, @elraphty Please assign me.

**Comment by chiragDork** [comment]
Hi @elraphty can you please assign this to me

**Comment by MuhammadUmer44** [comment]
@elraphty next please assign me
