### ISSUE TITLE
[tests][cypress] Edit Bounty By Searching, Change Organization And Assignee

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes-frontend#437]
### Context

Currently, we have a cypress command to [create a bounty](https://github.com/stakwork/sphinx-tribes-frontend/blob/master/cypress/support/commands.ts#L108) but we want to assert that we can search for the bounty after creating it, change the bounty organization, amount, coding languages, and change the bounty assignee

We want to create 2 Organizations, then create a bounty select one of the organizations as the bounty organization, and assign a user. Navigate to the `Bounties` tab, and search for the bounty that was created, click on the bounty then click on the `Edit` button. We want to assert that we can change the bounty organization, coding languages, amount, and assignee.

### File to create
`sphinx-tribes-frontend/cypress/e2e/31_editBountyBySearch.cy.ts`

there will be modifications to `sphinx-tribes-frontend/cypress/support/commands.ts`

### Acceptance Criteria

- Given a user is signed in
- We create 2 Organizations
- Then we create a bounty and select one of the organizations
- Navigate to the `Bounties` page and search for the created bounty
- Click on the bounty tile
- Click on the `Edit` button
- Change the bounty organization to the second organization 
- Change the bounty assignee to a new user
- Change the bounty coding languages
- Change the bounty amount
- Then assert that the new bounty organization, coding languages, amount, and assignee match what was passed to the edit modal inputs

The edit button is shown below
![image](https://github.com/stakwork/sphinx-tribes-frontend/assets/15950706/63a12ac4-1325-4db7-876a-a1252b6c510e)

- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 2 days of taking the bounty

### References
Example cypress test
`https://github.com/stakwork/sphinx-tribes-frontend/blob/master/cypress/e2e/0_create_bounty.cy.ts`

**Comment by MahtabBukhari** [comment]
@elraphty Could you assign me?

**Comment by AbdulWahab3181** [comment]
Could you please assign me?

**Comment by elraphty** [comment]
@MuhammadUmer44 you can take this one

**Comment by MuhammadUmer44** [comment]
@elraphty assign me

**Comment by elraphty** [comment]
> @elraphty Could you assign me?

Assigned the previous one to you already

**Comment by AbdulWahab3181** [comment]
@elraphty Could you please assign next one to me?

**Comment by elraphty** [comment]
> @elraphty Could you please assign me?

@AbdulWahab3181 I will assign the next one.

**Comment by chiragDork** [comment]
Hi @elraphty if there are more issue to work on please assign one to me as well. Thanks
