### ISSUE TITLE
[tests][cypress] Homepage Bounty Modal Navigation

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes-frontend#438]
### Context

Currently, we have a cypress command to [create a bounty](https://github.com/stakwork/sphinx-tribes-frontend/blob/master/cypress/support/commands.ts#L108) but we want to assert that we can navigate to the next and previous bounty when on the bounty modal.

We want to create 8 bounties, 3 bounties should be open, 3 bounties should be assigned to a user, and the remaining 2 bounties should be assigned to a user and marked as paid by clicking the `Mark As Paid` button after creating the bounties the default bounty status is opened, click on the first open bounty and assert that you can navigate to the next and previous bounty in the right order, then change the bounty status filter to paid, and assert you can see only 2 bounties and when you click on the first bounty, assert that the next bounty takes you can go to the next paid bounty, then select all bounty statuses and assert that the bounties are in the correct order and you navigate to the next and previous bounties.

Note: the bounties are ordered by the time they were created.

### File to create

`sphinx-tribes-frontend/cypress/e2e/32_bountyModalNavigation.cy.ts`

there will be modifications to `sphinx-tribes-frontend/cypress/support/commands.ts`

### Acceptance Criteria

- Given a user is signed in
- We create 8 bounties (3 Open, 3 Assigned, and 3 markets as paid)
- Assert that the open bounties are visible
- Click on the first open bounty, and assert you can go to the next and previous pages using the navigation arrows.
- Then change the bounty status filter to paid
- Assert that the 2 Open bounties are visible, and when you click on the first bounty you can navigate to the next bounty.
- Then select all the bounty statuses
- Assert that the 8 bounties are visible
- Click on the second bounty
- Assert that you can go to the next and previous bounties in the right order using the navigation arrows on the bounty modal.

The button modal left and right navigation buttons are shown below

![image](https://i.ibb.co/RCG1DxV/Screenshot-2024-03-19-at-15-55-27.png)

- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 2 days of taking the bounty

### References
Example cypress test
`https://github.com/stakwork/sphinx-tribes-frontend/blob/master/cypress/e2e/0_create_bounty.cy.ts`

**Comment by Vayras** [comment]
Assign

**Comment by elraphty** [comment]
> @elraphty can you please assign this to me, Thanks

I have to assign this one to @AbdulWahab3181
