### ISSUE TITLE
[tests][cypress] Organization Page Bounty Filter Statuses

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes-frontend#439]
### Context

Currently, we have a cypress command to [create a bounty](https://github.com/stakwork/sphinx-tribes-frontend/blob/master/cypress/support/commands.ts#L108) but we want to assert that we can view an organization's bounties based on the status we select.

We want to create an organization, and then create 8 bounties attached to the organization, 3 bounties should be open, 3 bounties should be assigned to a user, and the remaining 2 bounties should be assigned to a user and marked as paid by clicking the `Mark As Paid` button after creating the bounties the default bounty status is all (which selects all the bounties), we want to select the statuses on the bounty filter status one at a time, and assert that the right bounties are displayed.

### File to create

`sphinx-tribes-frontend/cypress/e2e/33_orgBountyStatusFilter.cy.ts`

there will be modifications to `sphinx-tribes-frontend/cypress/support/commands.ts`

### Acceptance Criteria

- Given a user is signed in
- Create an organization
- We create 8 bounties attached to the created organization (3 Open, 3 Assigned, and 3 markets as paid)
- Click on the organization label on one of the bounties and navigate to the organization's bounties page
- Assert that the 8 bounties are visible by default
- Select only `Open` status on the bounty status filter
- Assert that only opened bounties are displayed
- Select only `Assigned` status on the bounty status filter
- Assert that only assigned bounties are on the bounties list
- Select only `Paid` status on the bounty filter
- Assert that only paid bounties are visible.

The organization bounty status filter is shown below

![image](https://i.ibb.co/BTsKX0z/Screenshot-2024-03-19-at-15-48-32.png)

- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 2 days of taking the bounty

### References
Example cypress test
`https://github.com/stakwork/sphinx-tribes-frontend/blob/master/cypress/e2e/0_create_bounty.cy.ts`

**Comment by aliraza556** [comment]
.

**Comment by Vayras** [comment]
Assign

**Comment by chiragDork** [comment]
@elraphty  Can you please assign this to me

**Comment by saithsab877** [comment]
@elraphty,
Please assign me next.
