### ISSUE TITLE
Cross Icon Appears Above Text in Search Bar Across `Tribes`, `People` and `Bots` When Typing Long Inputs

### ISSUE THREAD

**Issue by aliraza556** [stakwork/sphinx-tribes-frontend#443]
**Describe the bug**
- When we type something long in the search bar, a cross icon appears above the text across all routes like `Tribes`, `People` and `Bots`.

- Additionally, people often search pages so quickly that they do not write a string in the proper way; after 3 or 4 words, they start searching.

**Bug Demo:** https://www.loom.com/share/71a002533a134d01bcb5e632827c4b21

**To Reproduce**
1. Go to 'https://community.sphinx.chat/t' , 'https://community.sphinx.chat/p' and 'https://community.sphinx.chat/b'
2. Click on 'Search Input'
3. Type something as a long string
4. Observe the error that appears

**Expected behavior**
When a user types something lengthy in the search bar, the cross icon should not obstruct the text. Instead, it should appear in a position that does not cover the text, ensuring all routes like `Tribes`, `People` and `Bots` are accessible and the user experience remains intuitive and unobstructed.

https://www.loom.com/share/da81c4b9fc53491e93d3e03262c06d98

**Desktop (please complete the following information):**

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a screenshot or video in my PR
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 2 days of taking the bounty

**Comment by aliraza556** [comment]
Hi @elraphty,
Please assign me.

**Comment by chiragDork** [comment]
Hi @elraphty can you please assign this one to me or the next one.

**Comment by AshokChoudhary11** [comment]
@elraphty Wanted to work on this issue. Could you assign this to me.
