### ISSUE TITLE
Default Photo Not Showing in `Assigned`, `Bounties` and `Leaderboard` on Mobile and Desktop

### ISSUE THREAD

**Issue by aliraza556** [stakwork/sphinx-tribes-frontend#447]
**Describe the bug**
Default Photo Not Showing in `Assigned`, `Bounties` and `Leaderboard` on Mobile and Desktop

**Bug Demo**
https://www.loom.com/share/bdf004f3d57e4adea0f8475a7e261ddd

**To Reproduce**
1. Go to 
- 'https://community.sphinx.chat/p/cd9dm5ua5fdtsj2c2n9g/bounties' , 
- 'https://community.sphinx.chat/p/cnbojkatu2rqjkh3a80g/assigned',
- 'https://community.sphinx.chat/leaderboard'
2. Observe the error that appears

**Expected behavior**
The default profile face picture should also be displayed. Implement this on desktop and mobile.
https://www.loom.com/share/1c73155ce7164bc78ce2ef7257e0a52a

**Desktop (please complete the following information):**

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a screenshot or video in my PR
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 2 days of taking the bounty

**Comment by aliraza556** [comment]
Hi @elraphty,
assign me

**Comment by MuhammadUmer44** [comment]
Hi @elraphty,
Can you please assign this to me

**Comment by chiragDork** [comment]
Hi @elraphty can you please assign this to me.
