### ISSUE TITLE
[Test][cypress][Signed Out] Post Bounty Flow

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes-frontend#448]
### Context

Currently, we have a cypress command to [create a bounty](https://github.com/stakwork/sphinx-tribes-frontend/blob/master/cypress/support/commands.ts#L108)

but we want to assert that when a user is signed out, and they try to post a bounty, they have to sign in before they can post a bounty.

So, go to the bounties homepage without signing in, click on the `Post Bounty` button, a modal should pop up for sign in, click on the `I Have Sphinx` button then sign in as a user and create a bounty. 

### File to create
`sphinx-tribes-frontend/cypress/e2e/34_signoutPostBounty.cy.ts`

there will be modifications to `sphinx-tribes-frontend/cypress/support/commands.ts`

### Acceptance Criteria

-  Given a user is not signed in
-  Go to the Bounties Homepage
-  Click on  ` 'Post Bounty' button
-  Click on `I have sphinx` button
-  Sign in a user
-  Create a bounty
-  Assert that the bounty created is visible
-  Sign out the user.

The Post Bounty Signout fLow is shown below

![image](https://i.ibb.co/fQyB7Hz/Screenshot-2024-03-21-at-10-24-52.png)
![image](https://i.ibb.co/qmyVrf5/Screenshot-2024-03-21-at-10-25-05.png)

- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 2 days of taking the bounty

### References
Example cypress test
`https://github.com/stakwork/sphinx-tribes-frontend/blob/master/cypress/e2e/0_create_bounty.cy.ts`

**Comment by MahtabBukhari** [comment]
sdf

**Comment by aliraza556** [comment]
HI @elraphty,
assign me next

**Comment by Vayras** [comment]
Assign
