### ISSUE TITLE
[Test][cypress][Signed Out] Connection Codes Flow

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes-frontend#449]
### Context

Currently, we have a cypress command to [create a bounty](https://github.com/stakwork/sphinx-tribes-frontend/blob/master/cypress/support/commands.ts#L108)

but we want to assert that when a user is signed out, and they try to post a bounty, they have to sign in using the connection codes.

So, go to the bounties homepage without signing in, click on the `Post Bounty` button, a modal should pop up for sign in, click on the `Get Sphinx` button then click on the `Reveal Connection Code` button, then you should see a `We are out of connection codes` msg

### File to create
`sphinx-tribes-frontend/cypress/e2e/35_signoutConnectionCodes.cy.ts`

there will be no modifications to `sphinx-tribes-frontend/cypress/support/commands.ts`

### Acceptance Criteria

-  Given a user is not signed in
-  Go to the Bounties Homepage
-  Click on  ` 'Post Bounty' button
-  Click on the `Get Sphinx` button
-  Click on the `Reveal Connection Code` button
-  Assert that you see a `There are no connection codes` message

The Connection code flow is shown below

![image](https://i.ibb.co/fQyB7Hz/Screenshot-2024-03-21-at-10-24-52.png)
![image](https://i.ibb.co/Csbvwjf/Screenshot-2024-03-21-at-12-17-10.png)
![image](https://i.ibb.co/bNSPNx4/Screenshot-2024-03-21-at-12-16-57.png)

- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 2 days of taking the bounty

### References
Example cypress test
`https://github.com/stakwork/sphinx-tribes-frontend/blob/master/cypress/e2e/0_create_bounty.cy.ts`

**Comment by aliraza556** [comment]
Hi @elraphty can you please assign this one to me

**Comment by chiragDork** [comment]
Assign

**Comment by elraphty** [comment]
> Hi @elraphty can you please assign this one to me

Ali work on the other 2 issues for now

**Comment by MuhammadUmer44** [comment]
@elraphty next assign to me

**Comment by Vayras** [comment]
@elraphty can you assign this one to me
