### ISSUE TITLE
[Test][cypress] I Can Help Flow

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes-frontend#450]
### Context

Currently, we have a cypress command to [create a bounty](https://github.com/stakwork/sphinx-tribes-frontend/blob/master/cypress/support/commands.ts#L108)

but we want to assert that when a user is signed out, they must sign in to connect with the Bounty Creator.

So we want to go to the bounties homepage sign in as `Alice` create 3 bounties and sign out.  Click on the 'I can help' button and a Signup modal pops up,  then login as `Carol` and click on the `I can help` button, and assert that when Carol clicks on I can help they can see the user connection Modal and QR code to Alice.

### File to create
`sphinx-tribes-frontend/cypress/e2e/36_icanhelpFLow.cy.ts`

there will be no modifications to `sphinx-tribes-frontend/cypress/support/commands.ts`

### Acceptance Criteria

-  Given Alice is signed in
-  Create 3 bounties
-  Log Alice out
-  Click on I can help when signed out
-  See the Sign up modal
-  Login as Carol
-  Click on the `I can help` button
- Assert you can see Alice's Connect Modal QRcode
- Logout

The `I can help flow` is shown below

![image](https://i.ibb.co/wpmN6fY/Screenshot-2024-03-21-at-12-54-12.png)
![image](https://i.ibb.co/ZHQg7z3/Screenshot-2024-03-21-at-13-10-48.png)
![image](https://i.ibb.co/T2pTnLg/Screenshot-2024-03-21-at-12-55-08.png)

- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 2 days of taking the bounty

### References
Example cypress test
`https://github.com/stakwork/sphinx-tribes-frontend/blob/master/cypress/e2e/0_create_bounty.cy.ts`

**Comment by MuhammadUmer44** [comment]
Hi @elraphty please assign  me

**Comment by AbdulWahab3181** [comment]
Could you please assign me?

**Comment by MirzaHanan** [comment]
Hi @elraphty can you please assign this one or the next one to me

**Comment by Vayras** [comment]
@elraphty can I get this one?
