### ISSUE TITLE
[Test][cypress] Homepage Bounties Filter

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes-frontend#452]
### Context

Currently, we have a cypress command to [create a bounty](https://github.com/stakwork/sphinx-tribes-frontend/blob/master/cypress/support/commands.ts#L108)

but we want to assert that we can filter a bounty by Status, and Coding Languages.

So we want to go to the bounties homepage and sign in as `Alice` and create 8 bounties, 3 assigned, 3 Open, and 2 Marked as Paid They should have different combinations of coding languages on the Coding Language filter and sign out. Click on the Filter to pop up the Filter Modal, and click on Open to assert and assert that only assigned bounties are visible. Click on Typescript and assert that only assigned bounties with Typescript are visible, then Select Lightning and assert that Typescript and Lightning bounties are visible. 

### File to create
`sphinx-tribes-frontend/cypress/e2e/37_bountyFilters.cy.ts`

there will be no modifications to `sphinx-tribes-frontend/cypress/support/commands.ts`

### Acceptance Criteria

-  Given Alice is signed in
-  Create 8 bounties (3 assigned, 3 Open, and 2 Marked as Paid They should have different combinations of coding languages )
-  Log Alice out
-  Click on the Filter
-  Select Assigned
-  Assert that only assigned bounties are visible
-  Select Typescript
-  Assert that on Typescript Bounties are visible
-  Select Lightning
-  Assert that only assigned bounties with Typecript, and Lightning are visible.
-  Logout

The Filter modal is shown below

![image](https://i.ibb.co/0cJqGFp/Screenshot-2024-03-21-at-13-25-27.png)

- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 2 days of taking the bounty

### References
Example cypress test
`https://github.com/stakwork/sphinx-tribes-frontend/blob/master/cypress/e2e/0_create_bounty.cy.ts`

**Comment by AbdulWahab3181** [comment]
Could you please assign me?

**Comment by MirzaHanan** [comment]
Hi @elraphty can you please assign this one

**Comment by saithsab877** [comment]
@elraphty Could you please assign me this one or may be next one?

**Comment by elraphty** [comment]
> Hi @elraphty can you please assign this one

You can have the next one
