### ISSUE TITLE
[Test][cypress] People List And Search

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes-frontend#453]
### Context

When we run the Cypress tests six (6) users are created (Alice, Carol, Bob, Dave, virtualNode0, and virtualNode1)

we want to assert that we see all users, and search for specific users.

So we want to go to the people homepage and assert that 6 users are visible, search for Carol and assert that only Carol is visible, search for Bob, and assert that only Bob is visible, click on Bob and assert that it takes you to Bob's profile page. On Bob's Profile page Search for Dave and assert that only Dave is visible on the list, click on Dave and assert that it takes you to Dave's profile.

### File to create

`sphinx-tribes-frontend/cypress/e2e/38_peoplePageAndSearch.cy.ts`

there will be no modifications to `sphinx-tribes-frontend/cypress/support/commands.ts`

### Acceptance Criteria

-  Go to the People Tab
-  Assert that 6 users are visible (Alice, Carol, Bob, Dave, virtualNode0, and virtualNode1))
-  Search for Carol, and assert that Carol is visible.
-  Search for Bob, and assert that Bob is visible.
-  Click on Bob and assert that it takes you to Bob's Profile Page
-  On Bob's Profile page Search for Dave and assert that only Dave is on the Search result
-  Click on Dave and assert that it takes you to Dave's profile
-  Logout

The Filter modal is shown below

![image](https://i.ibb.co/RQTvrvj/Screenshot-2024-03-21-at-13-49-08.png)
![image](https://i.ibb.co/2sCQp0z/Screenshot-2024-03-21-at-14-05-38.png)

- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 2 days of taking the bounty

### References
Example cypress test
`https://github.com/stakwork/sphinx-tribes-frontend/blob/master/cypress/e2e/0_create_bounty.cy.ts`

**Comment by AbdulWahab3181** [comment]
Could you please assign me this one or may be next one?

**Comment by MirzaHanan** [comment]
Hi @elraphty can you please assign this one
