### ISSUE TITLE
Incorrect Readme Instructions

### ISSUE THREAD

**Issue by fvalentiner** [stakwork/sphinx-tribes-frontend#455]
**Describe the bug**
On the readme file in https://github.com/stakwork/sphinx-tribes-frontend/blob/master/README.md#running-frontend-against-peoplesphinxchat-locally-

It specifies:
Modify line 6 in src/config/host.ts:
Change return host; to return 'people-test.sphinx.chat';

Should be line 10.

**Comment by bilalshaikh292** [comment]
heyy I have also noticed the same I would like to contribute.
