### ISSUE TITLE
[Test][cypress] [User Roles] View Transaction History

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes-frontend#461]
### Context

Currently, we have a cypress command to [create an organization](https://github.com/stakwork/sphinx-tribes-frontend/blob/master/cypress/support/commands.ts#L375C1-L395C1)

but we want to assert that when we assign a `View History` role to a user, the user can log in and view the organization's transaction history.

We want to Sign in as Alice, create an organization, add Carol to the organization, give Carol a `View Transaction History` role, then sign Alice out, Sign in as Carol, go to Carol's organization, and assert that the newly created organization is in Carol's list, click on the Organization's `Manage` button, in the OrganizationDetails assert that the History button is not disabled, then click on the History button and assert that you can see the Payments, Deposit, and Withdrawal checkboxes.

### File to create

`sphinx-tribes-frontend/cypress/e2e/39_rolesViewHistory.cy.ts`

there will be no modifications to `sphinx-tribes-frontend/cypress/support/commands.ts`

### Acceptance Criteria

-  Sign in as Alice
-  Click on the Alice's profile to go to the organization's tab
-  Create an organization
-  Add Carol to the Organization
-  Give Carol `View Transaction History role
-  Logout Alice
-  Sign in Carol
-  Go to Carol's organization tab
-  Assert that the new organization is on Carol's list
-  Click on the Manage button 
-  Assert that the History button is not disabled
-  Click on the History button 
-  Assert that Withdrawal, Deposit,  and Payments  checkboxes are visible 
-  Logout Carol

The View transaction history flow is shown below

![image](https://i.ibb.co/2qwkQQz/Screenshot-2024-03-25-at-10-13-38.png)
![image](https://i.ibb.co/JcC2JVc/Screenshot-2024-03-25-at-11-36-45.png)
![image](https://i.ibb.co/j6r0MCr/Screenshot-2024-03-25-at-10-13-17.png)
![image](https://i.ibb.co/1X5Nf8j/Screenshot-2024-03-25-at-10-13-29.png)

- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 2 days of taking the bounty

### References
Example cypress test
`https://github.com/stakwork/sphinx-tribes-frontend/blob/master/cypress/e2e/0_create_bounty.cy.ts`

**Comment by MahtabBukhari** [comment]
sdf

**Comment by Vayras** [comment]
Assign

**Comment by aliraza556** [comment]
@elraphty Please next to assign me

**Comment by elraphty** [comment]
> Assign
@Vayras you get the next one

**Comment by Vayras** [comment]
> > Assign
> @Vayras you get the next one

Okay, Thanks @elraphty

**Comment by AbdulWahab3181** [comment]
Could you please assign me this one or may be the next one?

**Comment by chiragDork** [comment]
Hi @elraphty can you please assign the next one to me.
