### ISSUE TITLE
[Test][cypress] [User Roles] Update Members

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes-frontend#462]
### Context

Currently, we have a cypress command to [create an organization](https://github.com/stakwork/sphinx-tribes-frontend/blob/master/cypress/support/commands.ts#L375C1-L395C1)

but we want to assert that when we assign an `Update Members` role to a user, the user can add users, and delete users from the organization

We want to Sign in as Alice, create an organization, add Carol to the organization, give Carol an `Update Members` role, then sign Alice out, Sign in as Carol, go to Carol's organization, and assert that the newly created organization is in Carol's list, click on the Organization's `Manage` button, in the OrganizationDetails assert that the `Add User button` is not disabled, then click on the `Add User` button and add Bob as a user to the organization, and assert that Bob is on the organization's users list

### File to create

`sphinx-tribes-frontend/cypress/e2e/40_rolesupdateMembers.cy.ts`

there will be no modifications to `sphinx-tribes-frontend/cypress/support/commands.ts`

### Acceptance Criteria

-  Sign in as Alice
-  Click on the Alice's profile to go to the organization's tab
-  Create an organization
-  Add Carol to the Organization
-  Give Carol `Update Members`role
-  Logout Alice
-  Sign in Carol
-  Go to Carol's organization tab
-  Assert that the new organization is on Carol's list
-  Click on the Manage button 
-  Assert that the `Add User` button is not disabled
-  Click on the `Add User` button 
-  Add Bob to the organization
-  Assert that Bob was added to the organization
-  Logout Carol

The Update members flow is shown below

![image](https://i.ibb.co/2qwkQQz/Screenshot-2024-03-25-at-10-13-38.png)
![image](https://i.ibb.co/JcC2JVc/Screenshot-2024-03-25-at-11-36-45.png)
![image](https://i.ibb.co/j6r0MCr/Screenshot-2024-03-25-at-10-13-17.png)

- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 2 days of taking the bounty

### References
Example cypress test
`https://github.com/stakwork/sphinx-tribes-frontend/blob/master/cypress/e2e/0_create_bounty.cy.ts`

**Comment by elraphty** [comment]
@Vayras comment on this so I can assign

**Comment by aliraza556** [comment]
Hi @elraphty can you please assign this and the next one to me.

**Comment by Vayras** [comment]
> @Vayras comment on this so I can assign

Assign

**Comment by NengakDakup** [comment]
Hi @elraphty Can i take any of the next tests?

**Comment by AbdulWahab3181** [comment]
Could you please assign me this one or may be the next one?
