### ISSUE TITLE
[Test][cypress] [User Roles] Manage Organization

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes-frontend#463]
### Context

Currently, we have a cypress command to [create an organization](https://github.com/stakwork/sphinx-tribes-frontend/blob/master/cypress/support/commands.ts#L375C1-L395C1)

but we want to assert that when we assign a `Manage Organization` role to a user, the user can edit the organization details.

We want to Sign in as Alice, create an organization, add Carol to the organization, give Carol a `Manage Organization` role, then sign Alice out, Sign in as Carol, go to Carol's organization, and assert that the newly created organization is in Carol's list, click on the Organization's `Manage` button, in the OrganizationDetails assert that the `Edit` button is not disabled, then click on the `Edit` button and add update the organization description, assert that the new organization description matches Carol's description.

### File to create

`sphinx-tribes-frontend/cypress/e2e/41_rolesManageOrganization.cy.ts`

there will be no modifications to `sphinx-tribes-frontend/cypress/support/commands.ts`

### Acceptance Criteria

-  Sign in as Alice
-  Click on the Alice's profile to go to the organization's tab
-  Create an organization
-  Add Carol to the Organization
-  Give Carol `Update Members`role
-  Logout Alice
-  Sign in Carol
-  Go to Carol's organization tab
-  Assert that the new organization is on Carol's list
-  Click on the Manage button 
-  Assert that the `Edit` button is not disabled
-  Click on the `Edit` button 
-  Update the organization description
-  Assert that the organization changes to the updated description of Carol
-  Logout Carol

The Manage Organization flow is shown below

![image](https://i.ibb.co/2qwkQQz/Screenshot-2024-03-25-at-10-13-38.png)
![image](https://i.ibb.co/JcC2JVc/Screenshot-2024-03-25-at-11-36-45.png)
![image](https://i.ibb.co/j6r0MCr/Screenshot-2024-03-25-at-10-13-17.png)
![image](https://i.ibb.co/0YxPm62/Screenshot-2024-03-25-at-15-03-32.png)

- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 2 days of taking the bounty

### References
Example cypress test
`https://github.com/stakwork/sphinx-tribes-frontend/blob/master/cypress/e2e/0_create_bounty.cy.ts`

**Comment by aliraza556** [comment]
j

**Comment by NengakDakup** [comment]
Hi @elraphty can i take this?

**Comment by MirzaHanan** [comment]
Hi @elraphty can you please assign this and the next one to me.
