### ISSUE TITLE
[Test][cypress] [User Roles] Withdraw From Organization

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes-frontend#464]
### Context

Currently, we have a cypress command to [create an organization](https://github.com/stakwork/sphinx-tribes-frontend/blob/master/cypress/support/commands.ts#L375C1-L395C1)

but we want to assert that when we assign a `Withdraw From Organization` role to a user, the user can withdraw from the organization.

We want to Sign in as Alice, create an organization, add Carol to the organization, give Carol a `Withdraw From Organization` role, then sign Alice out, Sign in as Carol, go to Carol's organization, and assert that the newly created organization is in Carol's list, click on the Organization's `Manage` button, in the OrganizationDetails assert that the `Withdraw` button is not disabled, then click on the `Withdraw` button, and assert that the withdraw modal pops up.

### File to create

`sphinx-tribes-frontend/cypress/e2e/42_rolesWithdrawOrganization.cy.ts`

there will be no modifications to `sphinx-tribes-frontend/cypress/support/commands.ts`

### Acceptance Criteria

-  Sign in as Alice
-  Click on the Alice's profile to go to the organization's tab
-  Create an organization
-  Add Carol to the Organization
-  Give Carol `Withdraw From Organization`role
-  Logout Alice
-  Sign in Carol
-  Go to Carol's organization tab
-  Assert that the new organization is on Carol's list
-  Click on the Manage button 
-  Assert that the `Withdraw` button is not disabled
-  Click on the `Withdraw` button 
-  Assert that the withdraw modal pops up
-  Assert that 'Past your invoice' is visible
-  Logout Carol

The Withdraw flow is shown below

![image](https://i.ibb.co/2qwkQQz/Screenshot-2024-03-25-at-10-13-38.png)
![image](https://i.ibb.co/JcC2JVc/Screenshot-2024-03-25-at-11-36-45.png)
![image](https://i.ibb.co/j6r0MCr/Screenshot-2024-03-25-at-10-13-17.png)
![image](https://i.ibb.co/V2MsCc2/Screenshot-2024-03-25-at-16-13-19.png)

- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 2 days of taking the bounty

### References
Example cypress test
`https://github.com/stakwork/sphinx-tribes-frontend/blob/master/cypress/e2e/0_create_bounty.cy.ts`

**Comment by elraphty** [comment]
@aliraza556 comment on this

**Comment by aliraza556** [comment]
assign

**Comment by MirzaHanan** [comment]
Hi @elraphty can you please assign me https://github.com/stakwork/sphinx-tribes-frontend/issues/462#issuecomment-2018008980

**Comment by MuhammadUmer44** [comment]
Hi @elraphty,
Please assign me

**Comment by AbdulWahab3181** [comment]
Could you please assign me the next one?
