### ISSUE TITLE
[Test][cypress] [User Roles] Fund Organization

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes-frontend#465]
### Context

Currently, we have a cypress command to [create an organization](https://github.com/stakwork/sphinx-tribes-frontend/blob/master/cypress/support/commands.ts#L375C1-L395C1)

but we want to assert that when we assign a `Fund Organization` role to a user, the user can Deposit to an organization.

We want to Sign in as Alice, create an organization, add Carol to the organization, give Carol a `Fund Organization` role, then sign Alice out, Sign in as Carol, go to Carol's organization, and assert that the newly created organization is in Carol's list, click on the Organization's `Manage` button, in the OrganizationDetails assert that the `Deposit` button is not disabled, then click on the `Deposit` button, and assert that the Deposit modal pops up.

### File to create

`sphinx-tribes-frontend/cypress/e2e/43_rolesFundOrganization.cy.ts`

there will be no modifications to `sphinx-tribes-frontend/cypress/support/commands.ts`

### Acceptance Criteria

-  Sign in as Alice
-  Click on the Alice's profile to go to the organization's tab
-  Create an organization
-  Add Carol to the Organization
-  Give Carol `Withdraw From Organization`role
-  Logout Alice
-  Sign in Carol
-  Go to Carol's organization tab
-  Assert that the new organization is on Carol's list
-  Click on the Manage button 
-  Assert that the `Deposit` button is not disabled
-  Click on the `Deposit` button 
-  Assert that the Deposit modal pops up
-  Assert that 'Amount (in sats)' is visible
-  Assert that 'Deposit' is visible
-  Logout Carol

The Deposit flow is shown below

![image](https://i.ibb.co/2qwkQQz/Screenshot-2024-03-25-at-10-13-38.png)
![image](https://i.ibb.co/JcC2JVc/Screenshot-2024-03-25-at-11-36-45.png)
![image](https://i.ibb.co/j6r0MCr/Screenshot-2024-03-25-at-10-13-17.png)
![image](https://i.ibb.co/BKwdQHk/Screenshot-2024-03-25-at-16-55-52.png)

- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 2 days of taking the bounty

### References
Example cypress test
`https://github.com/stakwork/sphinx-tribes-frontend/blob/master/cypress/e2e/0_create_bounty.cy.ts`

**Comment by elraphty** [comment]
@MirzaHanan comment on this

**Comment by AbdulWahab3181** [comment]
Could you please assign me this one, or maybe the next one?

**Comment by MirzaHanan** [comment]
Hi @elraphty can you please assign me

**Comment by chiragDork** [comment]
@elraphty can you please assign me this one or the next

**Comment by MuhammadUmer44** [comment]
Hi @elraphty can you please assign me https://github.com/stakwork/sphinx-tribes-frontend/issues/464#issuecomment-2018279536
