### ISSUE TITLE
[Test][cypress] [User Roles] Manage Bounties

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes-frontend#472]
### Context

Currently, we have a cypress command to [create an organization](https://github.com/stakwork/sphinx-tribes-frontend/blob/master/cypress/support/commands.ts#L375C1-L395C1)

but we want to assert that when we assign a `Manage Bounties` role to a user, the user can create a bounty for an organization.

We want to Sign in as Alice, create an organization, add Carol to the organization, give Carol a `Manage Bounties` role, then sign Alice out, Sign in as Carol, go to Carol's organization, and assert that the newly created organization is in Carol's list, click on the 
Bounties tab to create a bounty, assert that the organization is in the organization drop-down and create a bounty, and after the bounty is created click on the bounty tile,  assert that the 'Pay Bounty' button is visible

### File to create

`sphinx-tribes-frontend/cypress/e2e/44_rolesManageBounties.cy.ts`

there will be no modifications to `sphinx-tribes-frontend/cypress/support/commands.ts`

### Acceptance Criteria

-  Sign in as Alice
-  Click on the Alice's profile to go to the organization's tab
-  Create an organization
-  Add Carol to the Organization
-  Give Carol the `Manage Bounties`role
-  Logout Alice
-  Sign in Carol
-  Go to Carol's organization tab
-  Assert that the new organization is on Carol's list
-  Click on the Bounties tab
-  Click on the `Post Bounty` button
-  Assert that the Organization is in the organization dropdown
-  Carol creates a bounty
-  Click on the newly created bounty tile
-  Assert that the `Pay Bounty` button is visible
-  Logout Carol

The Manage Bounties  flow is shown below

![image](https://i.ibb.co/2qwkQQz/Screenshot-2024-03-25-at-10-13-38.png)
![image](https://i.ibb.co/JcC2JVc/Screenshot-2024-03-25-at-11-36-45.png)
![image](https://i.ibb.co/Dps1YRB/Screenshot-2024-03-26-at-15-16-25.png)
![image](https://i.ibb.co/kgGV2dP/Screenshot-2024-03-26-at-15-16-38.png)

- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 2 days of taking the bounty

### References
Example cypress test
`https://github.com/stakwork/sphinx-tribes-frontend/blob/master/cypress/e2e/0_create_bounty.cy.ts`

**Comment by AbdulWahab3181** [comment]
hd

**Comment by aliraza556** [comment]
f

**Comment by Vayras** [comment]
Assign

**Comment by Ekep-Obasi** [comment]
@elraphty please assign me

**Comment by elraphty** [comment]
> Hi @elraphty can you please assign me next?

@aliraza556 You get the next one
