### ISSUE TITLE
[Test][cypress] [Super Admin]  Bounty List

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes-frontend#473]
### Context

Currently, we have a cypress command to [create a bounty](https://github.com/stakwork/sphinx-tribes-frontend/blob/master/cypress/support/commands.ts#L375C1-L395C1)

but we want to assert that when bounties are created they are visible in the admin page by date range (Default 7 days).

We want to Sign in as Alice and create 5 bounties, then navigate to the admin tab, assert that the 5 bounties are on the 7-day bounties list timeframe, then change the date to `30 days` and assert that the bounties are on the bounties list, finally change the date to `90` days, and assert that the bounties are still on the bounties list.

### File to create

`sphinx-tribes-frontend/cypress/e2e/45_adminBountyList.cy.ts`

there will be no modifications to `sphinx-tribes-frontend/cypress/support/commands.ts`

### Acceptance Criteria

-  Sign in as Alice
-  Create 5 bounties
-  Navigate to the Admin page
-  Assert that the bounties are on the bounties list
-  Change the date to 30 days
-  Assert that the bounties are on the bounties list
-  Change the date to 90 days
-  Assert that the bounties are still  visible in the 90 day timeframe
-  Logout Alice

The Admin page  flow is shown below

![image](https://i.ibb.co/cX8TRM7/Screenshot-2024-03-26-at-16-04-27.png)

- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 2 days of taking the bounty

### References
Example cypress test
`https://github.com/stakwork/sphinx-tribes-frontend/blob/master/cypress/e2e/0_create_bounty.cy.ts`

**Comment by MirzaHanan** [comment]
@elraphty can you assign this or the next one

**Comment by elraphty** [comment]
@aliraza556  comment on this

**Comment by AbdulWahab3181** [comment]
Y

**Comment by MahtabBukhari** [comment]
sdf

**Comment by MuhammadUmer44** [comment]
Please assign me

**Comment by MahtabBukhari** [comment]
@elraphty Could you assine me next?

**Comment by MahtabBukhari** [comment]
@elraphty is there any next bounty?
