### ISSUE TITLE
[Test][cypress] [Super Admin]  Bounty Filter Status Dropdown

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes-frontend#474]
### Context

Currently, we have a cypress command to [create a bounty](https://github.com/stakwork/sphinx-tribes-frontend/blob/master/cypress/support/commands.ts#L375C1-L395C1)

but we want to assert that when we change the bounties filter status, only those with that status should be visible.

We want to Sign in as Alice and create 6 bounties (2 open, 2 assigned, and 2 marked as paid), then navigate to the admin tab, assert that the 6 bounties are on the 7-day bounties list timeframe, then change the status to open and assert that only open bounties are visible, change the status to assigned and assert that only assigned bounties are visible, finally change the filter status to paid and assert that only paid bounties are visible.

### File to create

`sphinx-tribes-frontend/cypress/e2e/46_adminFIlterStatus.cy.ts`

there will be no modifications to `sphinx-tribes-frontend/cypress/support/commands.ts`

### Acceptance Criteria

-  Sign in as Alice
-  Create 6 bounties  (2 open, 2 assigned, and 2 marked as paid)
-  Navigate to the Admin page
-  Assert that the bounties are on the bounties list
-  Change the status to open
-  Assert that only open bounties are visible
-  Change the status to assigned
-  Assert that only assigned  bounties are visible
-  Change the status to paid 
-  Assert that only paid bounties are visible 
-  Logout Alice

The Bounties filter status flow is shown below

![image](https://i.ibb.co/cX8TRM7/Screenshot-2024-03-26-at-16-04-27.png)
![image](https://i.ibb.co/zs7kVCk/Screenshot-2024-03-26-at-16-40-11.png)

- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 2 days of taking the bounty

### References
Example cypress test
`https://github.com/stakwork/sphinx-tribes-frontend/blob/master/cypress/e2e/0_create_bounty.cy.ts`

**Comment by MahtabBukhari** [comment]
f

**Comment by MirzaHanan** [comment]
@elraphty assign me this one

**Comment by AbdulWahab3181** [comment]
Could you please assign me?

**Comment by chiragDork** [comment]
Hi @elraphty can you please assign this one or the next one to me please
