### ISSUE TITLE
[Test][cypress] [Super Admin]  Bounty Filter SortBy

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes-frontend#475]
### Context

Currently, we have a cypress command to [create a bounty](https://github.com/stakwork/sphinx-tribes-frontend/blob/master/cypress/support/commands.ts#L375C1-L395C1)

but we want to assert that when we change the bounties filter sort by (it sorts by descending by default i.e. `Newest`), it changes the sorting direction of the bounties.

We want to Sign in as Alice and create 6 bounties, then navigate to the admin tab, assert that the 6 bounties are on the 7-day bounties list timeframe, then assert that the bounties are in chronologically descending order, then change the sortBy status to `Oldest` and assert that the bounties are ordered in ascending order (oldest first).

### File to create

`sphinx-tribes-frontend/cypress/e2e/47_adminFIlterSortBy.cy.ts`

there will be no modifications to `sphinx-tribes-frontend/cypress/support/commands.ts`

### Acceptance Criteria

-  Sign in as Alice
-  Create 6 bounties  
-  Navigate to the Admin page
-  Assert that the bounties are on the bounties list order in Descending order
-  Change the filter Sort By to `Oldest`
-  Assert that the new bounties are sorted in reversed Ascending order
-  Logout Alice

The Bounties filter Sort by flow is shown below

![image](https://i.ibb.co/cX8TRM7/Screenshot-2024-03-26-at-16-04-27.png)
![image](https://i.ibb.co/k88YyVY/Screenshot-2024-03-26-at-19-16-28.png)

- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 2 days of taking the bounty

### References
Example cypress test
`https://github.com/stakwork/sphinx-tribes-frontend/blob/master/cypress/e2e/0_create_bounty.cy.ts`

**Comment by MirzaHanan** [comment]
m

**Comment by AbdulWahab3181** [comment]
Could you please assign me?

**Comment by saithsab877** [comment]
Hi @elraphty can you please assign this one or the next one to me please

**Comment by elraphty** [comment]
> @elraphty can you assign this or the next one. I've configured the project and ready for writing a unit test.

Assigning the next one

**Comment by elraphty** [comment]
> ninja-programer

@ninja-programer please make your GitHub profile public
