### ISSUE TITLE
[Test][cypress] [Super Admin]  Bounty Click

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes-frontend#476]
### Context

Currently, we have a cypress command to [create a bounty](https://github.com/stakwork/sphinx-tribes-frontend/blob/master/cypress/support/commands.ts#L375C1-L395C1)

but we want to assert that when we click on a bounty tile on the admin bounties list, it opens a new bounty tab, and the bounty details are visible.

We want to Sign in as Alice and create 6 bounties, then navigate to the admin tab, and assert that the 6 bounties are on the 7-day bounties list timeframe, then click on the second bounty and assert that it opens a new tab with the bounty in display and assert that the bounty's details match the details of the second bounty created.

### File to create

`sphinx-tribes-frontend/cypress/e2e/48_adminBountyClick.cy.ts`

there will be no modifications to `sphinx-tribes-frontend/cypress/support/commands.ts`

### Acceptance Criteria

-  Sign in as Alice
-  Create 6 bounties  
-  Navigate to the Admin page
-  Click on the second bounty
-  Assert that a new bounty page is opened and in display
-  Assert that the details of the bounty in display matches the details of the second bounty created
-  Logout Alice

The Admin bounties list is  shown below

![image](https://i.ibb.co/cX8TRM7/Screenshot-2024-03-26-at-16-04-27.png)

- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 2 days of taking the bounty

### References
Example cypress test
`https://github.com/stakwork/sphinx-tribes-frontend/blob/master/cypress/e2e/0_create_bounty.cy.ts`

**Comment by saithsab877** [comment]
asss

**Comment by MuhammadUmer44** [comment]
HI @elraphty,
assign me

**Comment by AbdulWahab3181** [comment]
Could you please assign me the next one?

**Comment by chiragDork** [comment]
Hi @elraphty can you please assign me the next one
