### ISSUE TITLE
[Test][cypress] [Super Admin]  Bounty Pagination Number Click

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes-frontend#479]
### Context

Currently, we have a cypress command to [create a bounty](https://github.com/stakwork/sphinx-tribes-frontend/blob/master/cypress/support/commands.ts#L375C1-L395C1)

but we want to assert that when we click on a pagination number on the admin bounties list, it shows all the bounties on the paginated page.

We want to Sign in as Alice and create 25 bounties, then navigate to the admin tab, assert that the 20 bounties are on the 7-day bounties list timeframe, then click on the pagination page 2 then assert that the remaining 5 bounties are visible in page 2.

### File to create

`sphinx-tribes-frontend/cypress/e2e/49_adminPaginationNumber.cy.ts`

there will be no modifications to `sphinx-tribes-frontend/cypress/support/commands.ts`

### Acceptance Criteria

-  Sign in as Alice
-  Create 25 bounties  
-  Navigate to the Admin page
-  Assert that 20 bounties are visible
-  Click on Pagination Page number 2
-  Assert that 5 bounties are visible on page 2
-  Logout Alice

The Bounties Pagination number is shown below

![image](https://i.ibb.co/txdmJmr/Screenshot-2024-03-27-at-13-13-40.png)

- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 2 days of taking the bounty

### References
Example cypress test
`https://github.com/stakwork/sphinx-tribes-frontend/blob/master/cypress/e2e/0_create_bounty.cy.ts`

**Comment by AbdulWahab3181** [comment]
j

**Comment by elraphty** [comment]
> ninja-programer

you have no track record on your Github, I can't assign

**Comment by AhsanFarooqDev** [comment]
@elraphty assign me?

**Comment by MuhammadUmer44** [comment]
Hi @elraphty next please assign me

**Comment by chiragDork** [comment]
Hi @elraphty can you please assign me this one or the next one.

**Comment by Vayras** [comment]
> > ninja-programer
> 
> you have no track record on your Github, I can't assign

@elraphty can you assign me the next task?

**Comment by MuhammadUmer44** [comment]
Hi @ninja-programer, @elraphty
I work on various projects, such as Cypress and others, which you can see on my profile.
https://community.sphinx.chat/p/cnbojkatu2rqjkh3a80g/assigned

**Comment by MuhammadUmer44** [comment]
@ninja-programmer, but your profile is new and not commit history; please don't waste my time.
