### ISSUE TITLE
[Test][cypress] [Super Admin]  Admin Statistics Custom Date Range

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes-frontend#481]
### Context

Currently, we have a cypress command to [create a bounty](https://github.com/stakwork/sphinx-tribes-frontend/blob/master/cypress/support/commands.ts#L375C1-L395C1)

but we want to assert that when we click on the custom date we can select a date range by clicking the date calender.

We want to Sign in as Alice and create 25 bounties, then navigate to the admin tab, assert that the 20 bounties are on the 7-day and the bounties count shows 25 bounties, click on the date dropdown, and select `Custom` and select the start date as the beginning of the month and the end date as the current date, then assert that 25 bounties is still the bounties count, the screen's date range at the top left side matches the selected date.

### File to create

`sphinx-tribes-frontend/cypress/e2e/50_adminCustomDateSelect.cy.ts`

there will be no modifications to `sphinx-tribes-frontend/cypress/support/commands.ts`

### Acceptance Criteria

-  Sign in as Alice
-  Create 25 bounties  
-  Navigate to the Admin page
-  Assert that 20 bounties are visible
-  Assert that the bounties  count is 25
-  Click on the date dropdown
-  Select Custom
-  Click on the calendar and select the start of the month as the start date
-  Click on the calendar and select the current date as the end date
-  Assert that 25 bounties is still the bounties count
-  Assert that the screen's date range at the top left side matches the selected date.
-  Logout Alice

The Custom Date flow is shown below

![image](https://i.ibb.co/yN8Yv2F/Screenshot-2024-03-27-at-13-44-45.png)

- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 2 days of taking the bounty

### References
Example cypress test
`https://github.com/stakwork/sphinx-tribes-frontend/blob/master/cypress/e2e/0_create_bounty.cy.ts`

**Comment by AbdulWahab3181** [comment]
d

**Comment by MahtabBukhari** [comment]
sdf

**Comment by aliraza556** [comment]
asa

**Comment by chiragDork** [comment]
Hi @elraphty can you please assign one to me.

**Comment by MirzaHanan** [comment]
Hi @elraphty, Could you please assign me this one or may be the next one?

**Comment by NengakDakup** [comment]
Hi @elraphty been a while i worked on one. Can i take the next one?
