### ISSUE TITLE
[Test][cypress] [Super Admin]  Admin Statistics Custom Date Range Inputs

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes-frontend#486]
### Context

Currently, we have a cypress command to [create a bounty](https://github.com/stakwork/sphinx-tribes-frontend/blob/master/cypress/support/commands.ts#L375C1-L395C1)

but we want to assert that when we click on the custom date we can type the dates manually in the date inputs.

We want to Sign in as Alice and create 22 bounties, then navigate to the admin tab, assert that the 20 bounties are on the 7-day and the bounties count shows 22 bounties, click on the date dropdown, and select `Custom` and input the start date as the beginning of the month and the end date as the current date, then assert that 22 bounties is still the bounties count, the screen's date range at the top left side matches the selected date.

Note: the dates should be dynamic and not static i.e. the start date should be the first day of the month the bounty was created and the end date should be the last day of the month

### File to create

`sphinx-tribes-frontend/cypress/e2e/51_adminCustomDateInput.cy.ts`

there will be no modifications to `sphinx-tribes-frontend/cypress/support/commands.ts`

### Acceptance Criteria

-  Sign in as Alice
-  Create 22 bounties  
-  Navigate to the Admin page
-  Assert that 20 bounties are visible
-  Assert that the bounties  count is 22
-  Click on the date dropdown
-  Select Custom
-  Input the start date
-  Input the end date
-  Click on `Save`
-  Assert that 22 bounties is still the bounties count
-  Assert that the screen's date range at the top left side matches the selected date.
-  Logout Alice

The Custom Date Input flow is shown below

![image](https://i.ibb.co/yN8Yv2F/Screenshot-2024-03-27-at-13-44-45.png)

- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 2 days of taking the bounty

### References
Example cypress test
`https://github.com/stakwork/sphinx-tribes-frontend/blob/master/cypress/e2e/0_create_bounty.cy.ts`

**Comment by Vayras** [comment]
Assign

**Comment by AbdulWahab3181** [comment]
sf

**Comment by chiragDork** [comment]
Hi @elraphty can you please assign me the next one, been a while since I worked on one.
