### ISSUE TITLE
[BUG] Fix Load More Bounties on Assigned and Bounties Pages

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes-frontend#499]
## Describe the bug

Currently, when we click on the `Load More` button on the Assigned/Created bounties on the user profile page, it loads new bounties but does not retain bounties from the previous page.

We want to load more bounties and retain the bounties from the previous page, so store the bounties in a Javascript array, and when `Load More` is clicked append the new bounties to the Array.

## Steps To Reproduce

- Go to the user's page
- Click on the Assigned Bounties / Bounties tabs
- Click on  the `Load More` button

Loom Video

https://www.loom.com/share/7118bdcfd85543799b45c8b23de5e33c

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a screenshot or video in my PR
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 2 days of taking the bounty

Here is an [example unit test](https://github.com/stakwork/sphinx-tribes/blob/master/frontend/app/src/helpers/__test__/helpers.spec.ts)
Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

**Comment by elraphty** [comment]
@aliraza556 comment on this

**Comment by aliraza556** [comment]
@elraphty,
Please assign me
