### ISSUE TITLE
[BUG] Fix Page Redirect To /bounties on Connect Card

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes-frontend#508]
## Describe the bug

Currently, when we click on the `Connect` button on a user card the people page and the modal pop up, then click outside the user connect modal, it redirects to the `/bounties` route.

We want the user to remain on the people page `/p` after clicking out of the user modal, update the overlayClick on the connect modal to stay on the people page `/p`, rather than going back with `history.goBack()`.

```sh
 overlayClick={() => {
          props.dismiss();
          history.goBack();
 }}
```

## Steps To Reproduce

- Go to the peoples' page `/p`
- Click on the `Connect` button on any user card
- Click on  outside the connect modal  (the modal overlay)

Loom Video

 https://www.loom.com/share/076247dce7bd4702b90222dc41827782

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a screenshot or video in my PR
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 2 days of taking the bounty

Here is an [example unit test](https://github.com/stakwork/sphinx-tribes/blob/master/frontend/app/src/helpers/__test__/helpers.spec.ts)
Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

**Comment by elraphty** [comment]
@aliraza556 comment on this so I can assigned

**Comment by aliraza556** [comment]
@elraphty,
assign me
