### ISSUE TITLE
Add Features to Workspace

### ISSUE THREAD

**Issue by fvalentiner** [stakwork/sphinx-tribes-frontend#509]
### Context

A new page has been recently added for /workspace/{uuid} for now you can create a new workspace and navigate to the page manually.

There needs to be a functionality to manage Features inside workspaces. Each workspace is going to have a list of features.

### Design

Overall Workspace page design
![image](https://github.com/stakwork/sphinx-tribes-frontend/assets/54907697/4c33788e-1012-4b89-a586-f806c3bcc245)

And here is the details for this particular ticket

![image](https://github.com/stakwork/sphinx-tribes-frontend/assets/54907697/35fc23c6-7a67-4ec8-b154-c5af7d4b253a)

Please remember to use Elastic UI Components

Modifications:
- modify workspace/{uuid}
- - Add list of features
- - Add button for [Add Feature] 
- add feature/{uuid}
- - add link to return to workspace
- - add title of the feature
- create a cypress test to test this functionality

### Acceptance Criteria
- [ ] I've tested on Chrome
- [ ] I've submitted a screenshot or recording in my pr
- [ ] I've created a test that...
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a pr within 2 days of taking the bounty

Here is an [example unit test](https://github.com/stakwork/sphinx-tribes/blob/master/frontend/app/src/helpers/__test__/helpers.spec.ts)

Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

**Comment by Vayras** [comment]
Assign
