### ISSUE TITLE
Enable "no results" state for filters when appropriate for People Page

### ISSUE THREAD

**Issue by ChetanKarwa** [stakwork/sphinx-tribes-frontend#51]
**Describe the bug**
Currently when a filter is selected that has no results, a pending circle appears indefinitely.
<img width="1470" alt="image" src="https://github.com/stakwork/sphinx-tribes-frontend/assets/46815976/d722dffe-62e4-40ef-a2d3-9a94635166a1">

**Expected behavior**
Let's display a "no results" text instead.
<img width="1471" alt="image" src="https://github.com/stakwork/sphinx-tribes-frontend/assets/46815976/5e55e356-b7f0-45b9-8517-da8e67ac29e5">

** Desktop (please complete the following information):**
 - Browser: Chrome

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a screenshot PR
- [ ] I have created a test that asserts the no results text will be displayed if there are no people that meet that criteria

**Comment by ChetanKarwa** [comment]
@ecurrencyhodler I will like to pick and resolve this issue

**Comment by adeel-ahmad-sh** [comment]
@ecurrencyhodler, Is this one available?

**Comment by ecurrencyhodler** [comment]
Hi @adeel-ahmad-sh ! This one belongs to chetan because he found the bug and asked to work on it. 

But there are plenty of bounties to choose from: https://community.sphinx.chat/bounties

Are you on sphinx chat? It's how we pay out in bitcoin bounties.

Also how did you hear about this project?

**Comment by adeel-ahmad-sh** [comment]
No I am not on sphinx chat. @MahtabBukhari tell me about this project.

**Comment by ecurrencyhodler** [comment]
Sign up by following instructions from our [FAQ](https://docs.google.com/document/d/16NQ4SM4ptP4Lz5JKERAagdNw3GFRVv9eshMZ_oU-MVw/edit?usp=sharing). 

Here is your sphinx code: 
connect::relay.swarm4.sphinx.chat::03e9328f3b472abb60fff6b02a0a2fca2dc52b3b93ac57caf84fa4a765eedd76a8

**Comment by ecurrencyhodler** [comment]
Can you also reply back with your sphinx alias too?

**Comment by adeel-ahmad-sh** [comment]
@ecurrencyhodler , this is my sphinx name Adeel Ahmad

**Comment by ecurrencyhodler** [comment]
Can you sign in here? https://community.sphinx.chat/bounties

**Comment by ecurrencyhodler** [comment]
You'll also see open bounties on that site.

**Comment by ecurrencyhodler** [comment]
created bounty for you chetan: https://community.sphinx.chat/bounty/1302
