### ISSUE TITLE
Add Brief field to Feature screen

### ISSUE THREAD

**Issue by fvalentiner** [stakwork/sphinx-tribes-frontend#512]
### Context

There is a new page for Feature. A Feature is part of a Workplace and can be compared to an agile epic.

A workspace will have a list of features.

### Design

Remember to use the components from Elastic UI when ever posible https://eui.elastic.co/

This will be the full feature page
![image](https://github.com/stakwork/sphinx-tribes-frontend/assets/54907697/cbba2349-1855-408a-b227-41c46cfadc4a)

Your job for this bounty is to create the 'Feature Brief' field. Here are the specifics.
page: /feature/{feature_uuid}

![image](https://github.com/stakwork/sphinx-tribes-frontend/assets/54907697/c7794573-8538-41bf-aea6-4d0c47cdc269)

- The field will first display as a label. 
- When showing the label, replace \n with <br/> so that new lines are displayed property.
- When clicking Edit on the side menu, a text area appear with the value of the field.
- There will also be two buttons 
- Cancel -> Go back to the label display, 
- Update -> Call endpoint to update value and show label with updated value

Backend Endpoints:

GET /feature/{uuid}

POST /feature
{
	uuid: '{feature_uuid}',
	brief: 'value inside brief text area'
}

### Acceptance Criteria
- [ ] I've tested on Chrome
- [ ] I've submitted a screenshot or recording in my pr
- [ ] I've created a test that clicks on edit, changes the text area value, clicks update and refresh the page to find the new value
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a pr within 2 days of taking the bounty

Here is an [example unit test](https://github.com/stakwork/sphinx-tribes/blob/master/frontend/app/src/helpers/__test__/helpers.spec.ts)

Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

**Comment by Vayras** [comment]
Assign

**Comment by aliraza556** [comment]
Hi @fvalentiner,
assign me?

**Comment by vishnu552** [comment]
@fvalentiner can you please assign me

**Comment by AbdulWahab3181** [comment]
@fvalentiner Could you please assign me?

**Comment by AbdulWahab3181** [comment]
@fvalentiner Could you please assign this task to me if @aliraza556 doesn't want to continue with it.

**Comment by aliraza556** [comment]
Hi @AbdulWahab3181, I am working on this issue and have almost completed it.
