### ISSUE TITLE
Add Current month to date range options in admin

### ISSUE THREAD

**Issue by fvalentiner** [stakwork/sphinx-tribes-frontend#513]
### Context
On the admin page of the bounties platform there is a date range field.

That field has the following values:
7 days
30 days
90 days
[Custom button]

We will like to add Current Month so that the list will be

7 days
30 days
90 days
Current Month
[Custom button]

The current month is off course from the 1st day of the month untill the last. So if we are on may it will be from 05/01/2024 - 05/31/2024

### Design

Old
![image](https://github.com/stakwork/sphinx-tribes-frontend/assets/54907697/627206f1-badb-44f7-b44e-1c6f70f3cf17)

New
![image](https://github.com/stakwork/sphinx-tribes-frontend/assets/54907697/e436f1eb-2a5d-431f-b572-7bfd863a0f3c)

### Acceptance Criteria
- [ ] I've tested on Chrome
- [ ] I've submitted a screenshot or recording in my pr
- [ ] I've created a test that...
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a pr within 2 days of taking the bounty

Here is an [example unit test](https://github.com/stakwork/sphinx-tribes/blob/master/frontend/app/src/helpers/__test__/helpers.spec.ts)

Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

**Comment by Vayras** [comment]
@fvalentiner can you please assign this one to me?

**Comment by fvalentiner** [comment]
Thank you @Vayras! it has been assigned

**Comment by Vayras** [comment]
@fvalentiner Thanks 🚀
