### ISSUE TITLE
Add Requirements to Feature [feature-add-requirements-to-feature]

### ISSUE THREAD

**Issue by fvalentiner** [stakwork/sphinx-tribes-frontend#517]
### Context

There is a new page for Feature. A Feature is part of a Workplace and can be compared to an agile epic.

A workspace will have a list of features.

Bounty: https://community.sphinx.chat/bounty/1937

### Design

Clone this branch https://github.com/stakwork/sphinx-tribes-frontend/tree/feature-add-requirements-to-feature

Remember to use the components from Elastic UI when ever posible https://eui.elastic.co/

This will be the full feature page
![image](https://github.com/stakwork/sphinx-tribes-frontend/assets/54907697/cbba2349-1855-408a-b227-41c46cfadc4a)

Your job for this bounty is to create the 'Requirements' field. Here are the specifics.
page: /feature/{feature_uuid}

![image](https://github.com/stakwork/sphinx-tribes-frontend/assets/54907697/c4080a22-44cf-4467-ad45-0c1e5103b101)

- The field will first display as a label. 
- When showing the label, replace \n with <br/> so that new lines are displayed property.
- When clicking Edit on the side menu, the label will be hidden and a text area will appear with the value of the field.
- There will also be two buttons 
- Cancel -> Hide the text area and buttons and go back to the label display, 
- Update -> Call endpoint to update value, hide text area and buttons and show label with updated value

Backend Endpoints:

GET /feature/{uuid}

POST /feature
{
	uuid: '{feature_uuid}',
	requirements: 'value inside brief text area'
}

### Acceptance Criteria
- [ ] I've tested on Chrome
- [ ] I've submitted a screenshot or recording in my pr
- [ ] I've created a test that clicks on edit, changes the text area value, clicks update and refresh the page to find the new value
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a pr within 2 days of taking the bounty

Here is an [example unit test](https://github.com/stakwork/sphinx-tribes/blob/master/frontend/app/src/helpers/__test__/helpers.spec.ts)

Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

**Comment by saithsab877** [comment]
.

**Comment by Shoaibdev7** [comment]
Hi @fvalentiner, Please assign me?

**Comment by AbdulWahab3181** [comment]
@fvalentiner Could you please assign me?

**Comment by Ekep-Obasi** [comment]
@fvalentiner Please assign me

**Comment by AbdulWahab3181** [comment]
@fvalentiner Could you please assign this task to me if @Ekep-Obasi doesn't want to continue with it.

**Comment by Ekep-Obasi** [comment]
> @fvalentiner Could you please assign this task to me if @Ekep-Obasi doesn't want to continue with it.

hey @AbdulWahab3181, I'm on it
