### ISSUE TITLE
Add Repositories to Workspace [feature-add-repos-to-workspace]

### ISSUE THREAD

**Issue by fvalentiner** [stakwork/sphinx-tribes-frontend#519]
### Context

In the recently created Workspace page we need to add a list of repositories.

Bounty: https://community.sphinx.chat/bounty/1945

### Design

Clone this branch https://github.com/stakwork/sphinx-tribes-frontend/tree/feature-add-repos-to-workspace

Remember to use the components from Elastic UI when ever posible https://eui.elastic.co/. In particular for this issue, the Elastic UI tooltip should be used https://eui.elastic.co/#/display/tooltip

This will be the full Workspace page

![image](https://github.com/stakwork/sphinx-tribes-frontend/assets/54907697/a1f5325f-00ae-40ea-a27e-89dd021bbd0b)

Your job for this issue is to create the 'Repositories' part of the page. Here are the specifics.
page: /workspaces/{workspace_uuid}

![image](https://github.com/stakwork/sphinx-tribes-frontend/assets/54907697/6cc03458-5e14-456a-bffd-f3421497cdae)

This example shows what to do when the url is too long to fit in the component

![image](https://github.com/stakwork/sphinx-tribes-frontend/assets/54907697/c28bdb69-6478-4061-87ba-99fa9b4b2943)

Here you can see how to edit or delete a Repository from the list

![image](https://github.com/stakwork/sphinx-tribes-frontend/assets/54907697/4da56d3e-8232-464c-bdf7-997af9396bd4)

Backend Endpoints:

Get list of repositories
GET /workspaces/repositories/{workspace_uuid} //Gets the list of repositories for the workspace

Create or Update Repository
POST /workspaces/repositories
{
	workspace_uuid: '{uuid}',
        name: '{repo name}',
        url: '{repo url}'
}

Get Repository
GET /workspaces/{workspace_uuid}/repository/{repository_uuid}

Delete Repository
DELETE /workspaces/{workspace_uuid}/repository/{repository_uuid}

### Acceptance Criteria
- [ ] I've tested on Chrome
- [ ] I've submitted a screenshot or recording in my pr
- [ ] I've created a test that creates a new repository, edits the repository and deletes the repository
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a pr within 2 days of taking the bounty

Here is an [example unit test](https://github.com/stakwork/sphinx-tribes/blob/master/frontend/app/src/helpers/__test__/helpers.spec.ts)

Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

**Comment by Vayras** [comment]
@fvalentiner can you please assign me to this

**Comment by MuhammadUmer44** [comment]
@fvalentiner assign me?

**Comment by MahtabBukhari** [comment]
@fvalentiner Could you assign me?

**Comment by saithsab877** [comment]
Hi @fvalentiner, Please assign me https://github.com/stakwork/sphinx-tribes-frontend/issues/517#issuecomment-2108022934

**Comment by Vayras** [comment]
hey @fvalentiner I'm  facing an issue, can you please help me with this

Get Repository
GET /workspaces/{workspace_uuid}/repository/{repository_uuid}

Delete Repository
DELETE /workspaces/{workspace_uuid}/repository/{repository_uuid}

Both of these endpoints are returning 404 status code for me
