### ISSUE TITLE
Fix copy link button in tribe details section

### ISSUE THREAD

**Issue by ChetanKarwa** [stakwork/sphinx-tribes-frontend#53]
**Describe the bug**
The Copy link button, the text should not go outside the box.
<img width="1476" alt="image" src="https://github.com/stakwork/sphinx-tribes-frontend/assets/46815976/b79b290f-5c0b-480f-b1f6-0787e784fdf1">

**To Reproduce**
1. Go to 'https://community.sphinx.chat/t/bountyhuntersjobboard'
2. See error

**Expected behavior**
The Text should not overflow outside the button.

**Desktop (please complete the following information):**
 - Browser: Chrome

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a screenshot in my PR
- [ ] I've created a test that asserts the text "copy link" doesn't overflow

**Comment by ChetanKarwa** [comment]
@ecurrencyhodler Can you assign this one to me

**Comment by adeel-ahmad-sh** [comment]
@ecurrencyhodler can i take this one?

**Comment by ecurrencyhodler** [comment]
This is for ketan as he found a bug and asked to take it as a bounty. I'll let you know if anything changes.

**Comment by ecurrencyhodler** [comment]
Okay remove the word "link" and have the button aligned left to the QR code.

Add a test that when the copy link is clicked, a link is copied. You'll have to provide mockdata for the link.

Here's what the copy button should look like below:

![image](https://github.com/stakwork/sphinx-tribes-frontend/assets/32662508/cfac7091-9005-4a29-ae7c-39a2e8de9f6d)

**Comment by AbdulWahab3181** [comment]
@ecurrencyhodler Could you please assign me?

**Comment by AbdulWahab3181** [comment]
@ecurrencyhodler Could you please review this PR https://github.com/stakwork/sphinx-tribes-frontend/pull/230
