### ISSUE TITLE
Manage Feature Priority inside Workspace

### ISSUE THREAD

**Issue by fvalentiner** [stakwork/sphinx-tribes-frontend#531]
### Context

There is a section on the workspace/{workspace_uuid} page to list the workspaces features.

![image](https://github.com/stakwork/sphinx-tribes-frontend/assets/54907697/2ff7b7c5-e1b9-4123-b9f7-cdecaca8a3e3)

### Design

The job is to add functionality to manage feature priority.

![image](https://github.com/stakwork/sphinx-tribes-frontend/assets/54907697/de8015cb-cff8-4355-97d2-6d0356410e97)

- Add an icon to increate the feature priority on each feature
- Add an icon to decrease the feature priority on each feature

The feature priority is an integer value. The feature with the lowest priority (0) is first on the list.
- When increasing a feature priority, the priority must be swapped with the feature just on top of it.
- When decreasing a feature priority, the priority must be swapped with the feature just below it.

- The feature at top, with the lowest priority must not have an icon to increase priority.
- The feature at the bottom, with the lowest priority must not have an icon to decrease priority.

- Make sure the functionality does not break when changing pages on the list.

The endpoint to call to update feature priority is:
POST /features
body: {
 uuid: '{feature_uuid}',
 priority: new_priority,
}

### Acceptance Criteria
- [ ] I've tested on Chrome
- [ ] I've submitted a screenshot or recording in my pr
- [ ] I've created a test that increases a feature priority
- [ ] I've created a test that decreases a feature priority
- [ ] I've created a test that removes the user from the workspace
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a pr within 2 days of taking the bounty

**********
If a PR is not submitted within two days, we will assign the bounty to someone else
Bounty https://community.sphinx.chat/bounty/1983
**********

Here is an [example unit test](https://github.com/stakwork/sphinx-tribes/blob/master/frontend/app/src/helpers/__test__/helpers.spec.ts)

Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

**Comment by AbdulWahab3181** [comment]
@fvalentiner Could you please assign me?

**Comment by MahtabBukhari** [comment]
@fvalentiner assign me please?

**Comment by AbdulWahab3181** [comment]
@fvalentiner Could You please assign me?
