### ISSUE TITLE
Upload image to Feature fields

### ISSUE THREAD

**Issue by fvalentiner** [stakwork/sphinx-tribes-frontend#536]
### Context

We need to add an image upload functionality into some of the fields in the feature page.
feature/{feature_uuid}

Here is a video demonstrating how this functionality works today on github issues.
https://www.loom.com/share/cca486fdf1544747afba85459f494b5b?sid=0645d0d1-b8b5-4c2a-8595-0536193e0bac

### Design

Add the upload image functionality to the fields [Feature Brief], [Requirements] and [Architecture] of the feature/{feature_uuid] screen.

- Make sure you handled copied screen captures and copied image files.
- Make sure it works both on windows and mac.

The endpoint to call for image upload and name retrieval is:
/meme_upload endpoint

You can see examples in the Edit Workspace screen and in /workspace/{workspace_uuid} on the edit schematic.

Take your best shot at creating the cypress test for it but it is not necessary. 

### Acceptance Criteria
- [ ] I've tested on Chrome
- [ ] I've submitted a screenshot or recording in my pr
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a pr within 2 days of taking the bounty

**********
If a PR is not submitted within two days, we will assign the bounty to someone else
Bounty ??
**********

Here is an [example unit test](https://github.com/stakwork/sphinx-tribes/blob/master/frontend/app/src/helpers/__test__/helpers.spec.ts)

Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

**Comment by aliraza556** [comment]
.

**Comment by saithsab877** [comment]
.

**Comment by AbdulWahab3181** [comment]
@fvalentiner Could you please assign me?
