### ISSUE TITLE
[Bug] Bounty status different in list vs details

### ISSUE THREAD

**Issue by fvalentiner** [stakwork/sphinx-tribes-frontend#537]
### Context
If you Navigate to Profile -> Bounties you will see a list similar to this
<img width="1970" alt="image" src="https://github.com/stakwork/sphinx-tribes-frontend/assets/54907697/aba6d0c4-554f-4b43-bd43-3d57b7d32823">

If you don't have any bounties you can create a new one on https://people-test.sphinx.chat/

If you assign a bounty and then set it to completed, the status on the list will be different from the status in the details.

List
<img width="313" alt="image" src="https://github.com/stakwork/sphinx-tribes-frontend/assets/54907697/6b47244d-8f97-469a-874e-8fd88d72ad1f">

Details
<img width="858" alt="image" src="https://github.com/stakwork/sphinx-tribes-frontend/assets/54907697/f81ccfea-7cec-4b78-a51c-68a719ba6f5b">

As you can see on the list it states Assigned and on the details its Completed.

### Acceptance Criteria
- [ ] I've tested on Chrome
- [ ] I've submitted a screenshot or recording in my pr
- [ ] I've created a test that: Creates a bounty, assigns the bounty and checks that the status on the list is the same as on the details  
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a pr within 2 days of taking the bounty

**********
If a PR is not submitted within two days, we will assign the bounty to someone else
Bounty https://community.sphinx.chat/bounty/1995
**********

Here is an [example cypress test](https://github.com/stakwork/sphinx-tribes-frontend/tree/master/cypress/e2e)

**Comment by Ekep-Obasi** [comment]
A

**Comment by aliraza556** [comment]
b

**Comment by AbdulWahab3181** [comment]
a
