### ISSUE TITLE
[Draft] Move workspace budget section into a component and use it in new Workspace page

### ISSUE THREAD

**Issue by fvalentiner** [stakwork/sphinx-tribes-frontend#544]
### Context

The Workspace Balance is currently in https://github.com/stakwork/sphinx-tribes-frontend/blob/571c2595fb888c9ffffb6c34d720f595e90e443f/src/people/widgetViews/WorkspaceDetails.tsx, We want to component of its own, and move it to a new page.

### Design

So we want to copy the workspace budget design into a new child component, make a call to get the workspace budget

```sh
  const getWorkspaceBudget = useCallback(async () => {
    if (!viewReportDisabled) {
      const workspaceBudget = await main.getWorkspaceBudget(uuid);
      setWorkspaceBudget(workspaceBudget);
    }
  }, [main, uuid, viewReportDisabled]);
```

also make a call to get the active user roles, to ascertain if the user has access to view the Workspace budget

```sh
const getUserRoles = useCallback(
    async (user: any) => {
      const pubkey = user.owner_pubkey;
      if (uuid && pubkey) {
        const userRoles = await main.getUserRoles(uuid, pubkey);
        setUserRoles(userRoles);
      }
    },
    [uuid, main]
  );

 const viewReportDisabled =
    !isWorkspaceAdmin && !userHasRole(main.bountyRoles, userRoles, 'VIEW REPORT');
```

![Balance Image](https://i.ibb.co/K2VHhGq/Screenshot-2024-05-27-at-11-05-11.png)

If the User has no role in viewing a budget, the no access component and message should be displayed

```sh
 {viewReportDisabled ? (
          <NoBudgetWrap>
            <MaterialIcon
              icon={'lock'}
              style={{
                fontSize: 30,
                cursor: 'pointer',
                color: '#ccc'
              }}
            />
            <NoBudgetText>
              You have restricted permissions and are unable to view the budget. Reach out to the
              workspace admin to get them updated.
            </NoBudgetText>
          </NoBudgetWrap>
        )
```

### Acceptance Criteria
- [ ] I've tested on Chrome
- [ ] I've submitted a screenshot or recording in my pr
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 6 hours of taking the bounty

Here is an [example unit test](https://github.com/stakwork/sphinx-tribes/blob/master/frontend/app/src/helpers/__test__/helpers.spec.ts)

Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

**Comment by MirzaHanan** [comment]
@fvalentiner please assign me?
