### ISSUE TITLE
Add Bounties to Phases

### ISSUE THREAD

**Issue by fvalentiner** [stakwork/sphinx-tribes-frontend#545]
### Context
We need to add functionality to the page  feature/{feature_uuid} to manage bounties inside Feature Phases.

### Design

Figma url: https://www.figma.com/design/1aL3lgG5Rpkti4b0j42fwf/Bounties---FINAL-DESIGNS?node-id=11865-1033

![image](https://github.com/stakwork/sphinx-tribes-frontend/assets/54907697/b8e21757-34c7-49a1-a14e-7dc71751c5c1)

1- Modify the Tab section to match the design.
3- To add a bounty to a phase you can use the same Modal as in the [Post a Bounty Button] in /bounties. Make sure you add functionality to pass the phase_uuid to the create bounty component so that you can pass the phase_uuid when calling the add bounty endpoint in:
POST /gobounties/ with the body including the phase_uuid. 

If no phase_uuid is specified then the bounty will not be related to the phase.

4- Use the component src/people/widgetViews/WidgetSwitchViewer.tsx to display the list of bounties for a phase. It contains all the logic for displaying bounties on a list.

You can see how this component is used in src/pages/tickets/Tickets.tsx
![image](https://github.com/stakwork/sphinx-tribes-frontend/assets/54907697/5fd706af-bf88-4df2-b644-e2d1aa3e150b)

We need only the get people bounties APi call  to populate the bounties data
```sh
main.getPeopleBounties({
        page: 1,
        resetPage: true,
        ...checkboxIdToSelectedMap,
        languages: languageString });
```

5- The list of bounties to pass to the component related to the phase_uuid can be obtained in:
GET /features/{feature_uuid}/phase/{phase_uuid}/bounty

**********
No need to create a cypress test for this bounty.
**********

### Acceptance Criteria
- [ ] I've tested on Chrome
- [ ] I can create a new bounty and it is assigned to the list of bounties for the phase
- [ ] I have moved the bounties through different status: open, assigned and paid and check that the bounty displays the correct status and UI in the list. Use the Figma provided to view the UI of a bounty in different stages. Open, Assigned and Paid
- [ ] The list of bounties is updated when: New bounty is created, bounty changes status, bounty deleted
- [ ] I've submitted a screenshot or recording in my pr
- [ ] I have tested locally before submitting my PR
- [ ] I can submit a pr within 10 hours of taking the bounty

Here is an [example unit test](https://github.com/stakwork/sphinx-tribes/blob/master/frontend/app/src/helpers/__test__/helpers.spec.ts)

Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

**Comment by AbdulWahab3181** [comment]
@fvalentiner Could you please assign me?

**Comment by MirzaHanan** [comment]
@fvalentiner please assign me?

**Comment by MirzaHanan** [comment]
@fvalentiner, Please assign this issue to me because the deadline has passed.
![image](https://github.com/stakwork/sphinx-tribes-frontend/assets/100023456/0ecff3f3-d4a6-4c7d-9b29-1909792c75b8)

**Comment by aliraza556** [comment]
Hi @fvalentiner, Please assign me?
