### ISSUE TITLE
Workspace Budget - Move into component and copy to new Workspace screen

### ISSUE THREAD

**Issue by fvalentiner** [stakwork/sphinx-tribes-frontend#547]
### Context

Bounty: https://community.sphinx.chat/bounty/2011

On the Manage Workspace page
<img width="1772" alt="image" src="https://github.com/stakwork/sphinx-tribes-frontend/assets/54907697/eb55e34d-4b00-4e37-8293-58a591f9669a">

There is a section for Workspace Budget

![image](https://github.com/stakwork/sphinx-tribes-frontend/assets/54907697/ed0843f2-cec2-43a2-825c-559be2d530b8)

The job for this ticket is:
1- Move the design and functionality of the budget section in Manage Workspace into a component. 
2- Use the component in the same Manage Workspace page in order to keep the original functionality.
2- Add the component to the workspace/{workspace_uuid} page in WorkspaceMission.tsx
Both the Manage Workspace page and the workspaces/{workspace_uuid} page will have the same Budget component. 

### Design

1- Go to the file src/people/widgetViews/WorkspaceDetails.tsx

![image](https://github.com/stakwork/sphinx-tribes-frontend/assets/54907697/8f70647f-d34c-447c-b0d8-4d7187add800)

2- Create a new component src/workspace/budget/WorkspaceBudgetViewer.tsx

3- Move everything inside the BudgetWrap tag in src/people/widgetViews/WorkspaceDetails.tsx  and its related javascript  to the new component.

4- Replace the BudgetWrap tag in WorkspaceDetails.tsx with the name of the component WorkspaceBudgetViewer as to keep the original functionality.

5- Include the new component WorkspaceBudgetViewer in the page src/people/widgetViews/WorkspaceMission.tsx just before the features FieldWrap.
![image](https://github.com/stakwork/sphinx-tribes-frontend/assets/54907697/89855a28-34c3-4090-b808-13da781e9356)

6- After adding the component to the WorkspaceMission.tsx file, the page /workspace/{workspace_uuid} should have this design

https://www.figma.com/design/1aL3lgG5Rpkti4b0j42fwf/Bounties---FINAL-DESIGNS?node-id=11853-36656&t=mr8zUyTugKiBQF1f-0

![image](https://github.com/stakwork/sphinx-tribes-frontend/assets/54907697/64c41d5b-8194-40cc-8a52-bf8d54d9fa1a)

 

### Acceptance Criteria
- [ ] I've tested on Chrome
- [ ] I've ran and verified that all cypress tests pass by running `yarn run cypress:run` as specified in docs/setupCypressTest.md 
- [ ] I've submitted a screenshot or recording in my pr
- [ ] I can submit a pr within 6 hours of taking the bounty

**Comment by Ekep-Obasi** [comment]
Please assign me

**Comment by Vayras** [comment]
@fvalentiner can you please assign me to this, Thanks
