### ISSUE TITLE
User Stories UI Changes and manage User Story priority

### ISSUE THREAD

**Issue by fvalentiner** [stakwork/sphinx-tribes-frontend#553]
### Context

This is the current design for User Stories in the feature/{feature_uuid} page.

<img width="600" alt="image" src="https://github.com/stakwork/sphinx-tribes-frontend/assets/54907697/966d8ca3-7139-40e2-aef9-718de5fb971a">

<br/><br/>

This is the new design for User Stories

![image](https://github.com/stakwork/sphinx-tribes-frontend/assets/54907697/c6fd143f-edaa-4e6f-abf3-07fb9d5438fd)

The Figma design is here: https://www.figma.com/design/1aL3lgG5Rpkti4b0j42fwf/Bounties---FINAL-DESIGNS?m=dev&node-id=11944-10786&t=C22nqJLlx5fjugf0-1

### Design

1- Move 'User Story' section on src/people/widgetViews/WorkspaceFeature.tsx to below the 'Feature Brief' section.

2- Apply UI changes to the list of User Stories
- Apply background color and border to section
- Apply background color and border to list items
- Apply font changes to User Story items
- Move 'more_vert' icon to the top left corner of the list item
- Add material design icon 'drag_handle'  to the left and center vertically
- Move create new user story to bottom
- Apply UI changes to Create User Story field
- Apply UI changes to Create User Story button

3- Add Elastic UI Drag and drop functionality. Specifically Custom Drag Handle
- Here are the details https://eui.elastic.co/#/display/drag-and-drop#custom-drag-handle

Here is a video showing the functionality 
https://www.loom.com/share/40c6437fc46d47e7af50d91f02c59797?sid=0c27feb3-3dee-4f5f-9e95-b754aa86d296

4- Update Priority
- On the 'end drag' event ('onDragEnd'), you must update the user stories that have changed priority. 
- You can do that by calling the endpoint:
POST /features/story 
`body: {
  uuid: {userstory_uuid},
  priority: {userstory_priority}
}`

### Acceptance Criteria
- [ ] I've tested on Chrome
- [ ] I have created several user stories on a feature and tested update of the priorities using drag and drop
- [ ] I've tested changing user stories by drag and drop in more than one Feature
- [ ] I've submitted a screenshot or recording in my pr
- [ ] I can submit a pr within 8 hours of taking the bounty

Here is an [example unit test](https://github.com/stakwork/sphinx-tribes/blob/master/frontend/app/src/helpers/__test__/helpers.spec.ts)

Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

**Comment by Ekep-Obasi** [comment]
A

**Comment by AbdulWahab3181** [comment]
a
