### ISSUE TITLE
Change edit context menu in Workspace and Feature fields

### ISSUE THREAD

**Issue by fvalentiner** [stakwork/sphinx-tribes-frontend#559]
### Context

Bounty: https://community.sphinx.chat/bounty/2036

We need to standardize the edit menus on the /workspace/{workspace_uuid} and the feature/{feature_uuid}

/workspace/{workspace_uuid} fields with context edit menu
- Mission
- Tactics and objectives
- Schematic
- Repositories

/feature/{workspace_uuid} fields with context edit menu
- Feature Brief
- User Stories
- Requirements
- Architecture
- Phases

Some examples:

<img width="147" alt="image" src="https://github.com/stakwork/sphinx-tribes-frontend/assets/54907697/5bfff22a-a004-4d81-9718-eff79b703d15">
<img width="173" alt="image" src="https://github.com/stakwork/sphinx-tribes-frontend/assets/54907697/c15a31d1-f9ea-4a84-a745-7667d3196779">
<img width="112" alt="image" src="https://github.com/stakwork/sphinx-tribes-frontend/assets/54907697/ea95ec73-8e52-4427-8848-2b705c773d9a">
<img width="183" alt="image" src="https://github.com/stakwork/sphinx-tribes-frontend/assets/54907697/d63dd977-a5ab-4693-980e-1abd454d10bc">

### Design

The context menus for each of those fields should all use the Context Menu component of Elastic UI 

https://eui.elastic.co/#/navigation/context-menu

![image](https://github.com/stakwork/sphinx-tribes-frontend/assets/54907697/4f4d10fd-4c4b-4225-b9b9-ca96e134688f)

****
There is no need to create extra cypress tests for this issue
****

### Acceptance Criteria
- [ ] I've tested on Chrome
- [ ] I've changed the context menu in all 9 fields
- [ ] I've submitted a screenshot or recording in my pr showing all 9 occurrences of the edit context menu
- [ ] I've confirmed all current cypress tests are passing
- [ ] I can submit a pr within 8 hours of taking the bounty

**Comment by jordan-ae** [comment]
A

**Comment by AbdulWahab3181** [comment]
a

**Comment by aliraza556** [comment]
@fvalentiner assign me?

**Comment by MirzaHanan** [comment]
Hi @fvalentiner, Please assign me?

**Comment by MahtabBukhari** [comment]
@fvalentiner Could you please assign me?
