### ISSUE TITLE
Center profiles on people page

### ISSUE THREAD

**Issue by adeel-ahmad-sh** [stakwork/sphinx-tribes-frontend#56]
**Describe the bug**
There is excess margin on the right side of the people section. Additionally, all components in this section will look better if they were aligned in the center.

![Screenshot (37)](https://github.com/stakwork/sphinx-tribes-frontend/assets/122393878/a0cf2ba1-be9c-4f1a-8427-48ee1d5ba974)

**To Reproduce**
1. Go to 'https://community.sphinx.chat/p'
2. See error

**Expected behavior**
There might not be extra margin on right side and might be equal margin on both sides, and components which are representing people must be properly aligned.

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a screenshot in my PR
- [ ] Write a test which make sure that there margin on both right and left sides are equal

**Comment by adeel-ahmad-sh** [comment]
Please assign me this.

**Comment by ecurrencyhodler** [comment]
Here's a bounty for you: https://community.sphinx.chat/bounty/1303

**Comment by ecurrencyhodler** [comment]
Thanks for also including a test in the acceptance criteria!

**Comment by aliraza556** [comment]
Hi @ecurrencyhodler, @adeel-ahmad-sh,
Please fix the loading icon on the people page (https://community.sphinx.chat/p). Here is a [demo link](https://www.loom.com/share/1d249d6ca19740cab42931831cac235b) for reference.

**Comment by ecurrencyhodler** [comment]
Coder turtle is going to submit an issue for this.
