### ISSUE TITLE
[Bug] Cannot assign Workplace to Bounty

### ISSUE THREAD

**Issue by fvalentiner** [stakwork/sphinx-tribes-frontend#563]
**Describe the bug**
Issue creating a bounty to a new Workspace.

https://www.loom.com/share/4883535a8be34525a9063ca6af36494c?sid=25db5e17-0dcf-48f0-af10-5279c56fa14f

**To Reproduce**
1. Go to your profile
2. Create a new Workspace
3. Go to Bounties list
4. Create a Bounty for the new workspace
5. Verify that the bounty does not have the workspace assigned

**Expected behavior**
The new bounty should have the workspace assigned

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a screenshot or video in my PR
- [ ] I can submit a PR within 10 hours of taking the bounty

**Comment by MahtabBukhari** [comment]
f

**Comment by aliraza556** [comment]
@fvalentiner

**Comment by Ekep-Obasi** [comment]
@fvalentiner Please assign me

**Comment by AbdulWahab3181** [comment]
@fvalentiner a
