### ISSUE TITLE
Persist Bounties Filters Selection.

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes-frontend#564]
**Describe the bug**

Currently, after filters are selected on the bounties page if a user leaves the page and returns, the filter is cleared and returned to the default filter `Open`, the user has to select the filters again which is bad for UX.

https://www.loom.com/share/f96f5824d48146b0acef870e91a3d34a

**To Reproduce**

1. Go to `https://community.sphinx.chat/bounties`
2. Click on the filters Icon and select the `Assigned` and `Paid` filters.
3. Navigate to `https://community.sphinx.chat/p`
4. Return to  `https://community.sphinx.chat/bounties`
5. And the filter will be cleared.

**Expected behavior**

We want to persist the filters so that when a user returns to the bounties page they can continue from where they stopped without having to reselect the filters

### Acceptance Criteria

- [ ] I have tested on Chrome desktop
- [ ] I have posted a screenshot or video in my PR
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 2 days of taking the bounty

Here is an [example unit test](https://github.com/stakwork/sphinx-tribes/blob/master/frontend/app/src/helpers/__test__/helpers.spec.ts)
Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

**Comment by ManyRios** [comment]
Hey  @aliraza556 is this available?

**Comment by aliraza556** [comment]
@ManyRios,
Yes
