### ISSUE TITLE
Admin Panel Mapping 

### ISSUE THREAD

**Issue by gouravmpk** [stakwork/sphinx-tribes-frontend#57]
**Describe the bug**
A clear and concise description of what the bug is. Include a screenshot or recording if you can.
![image](https://github.com/stakwork/sphinx-tribes-frontend/assets/20900042/af369b14-1e17-4081-8f03-26d87633a3dd)

**To Reproduce**
1. Go to 'Admin Panel'
4. See issue

**Expected behavior**
Names/userName should be shown instead of uuid/pubkey

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a screenshot or video in my PR

**Comment by ecurrencyhodler** [comment]
Hmm we must've had a reversion. You addressed this before in https://github.com/stakwork/sphinx-tribes/pull/1371

**Comment by gouravmpk** [comment]
Yes I was just adding org name but I found these were missing too so added them again and changed the styling of button

**Comment by ecurrencyhodler** [comment]
Thanks for reporting. Let me take a look as to what happened.

**Comment by gouravmpk** [comment]
Test are passing in local

**Comment by ecurrencyhodler** [comment]
I think maybe somehow this wasn't included when we split the front/backend. I'll need to sync with the team.
