### ISSUE TITLE
Add Button "Refine Description" button to the freelance Job Request Form Step 3

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes-frontend#582]
## Context
The Freelance Job Request Form's Step 3 currently lacks the ability to automatically generate refined descriptions based on user input. We need to add a "Refine Description" button that will later connect to a workflow for generating structured GitHub-ready descriptions.

## Design

Screenshot shows the new "Refine Description" button positioned below the description text area. 

![image](https://github.com/user-attachments/assets/cf9b628f-94c2-403a-ba09-203f31e8de5f)

The button should:
- Be styled using our existing UI components
- On selection the button should trigger a pop up stating "this functionality is coming soon" 
- Include hover states consistent with our UI
- Be positioned alongside the existing form elements
- The drop down box should allow selection of 1 of three ticket types (bug, feature, test) and must be selected if the refine button is pressed.

## Assignment Criteria
Before requesting assignment:
- [ ] Migrate to the new Sphinx V2 application for clear communications
- [ ] Connect with Pete on Sphinx Community (https://community.sphinx.chat/p/cs7n8c2tu2rivj8gup0g)

## Acceptance Criteria
- [ ] I've tested on Chrome
- [ ] I've submitted a screenshot or recording in my PR
- [ ] Add new "Refine Description" button component to Step 3 of the Freelance Job Request form
- [ ] Style button according to existing UI guidelines
- [ ] Ensure a simple pop up is displayed on click. 
- [ ] Add dropdown component for issue templates (bug, feature, test)
- [ ] Add unit tests for the new button component
- [ ] Add component tests for the updated form view
- [ ] Ensure typescript types are properly defined
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 2 days of taking the bounty

## Technical Notes
- Project: sphinx-tribes-frontend
- Language: TypeScript
- Phase 1 Scope: UI implementation only (button will trigger feedback pop up)

**Comment by Ekep-Obasi** [comment]
A

**Comment by Shoaibdev7** [comment]
@humansinstitute Please assign me

**Comment by aliraza556** [comment]
Could you kindly assign me to @tomsmith8?
