### ISSUE TITLE
Fix  semicolon type error in people page

### ISSUE THREAD

**Issue by Fog3211** [stakwork/sphinx-tribes-frontend#59]
**Describe the bug**
There is an extra semicolon in people page 
![image](https://github.com/stakwork/sphinx-tribes-frontend/assets/23151576/eca47dd1-49f2-491a-9402-068849e28898)

**To Reproduce**
open sphinx people page, like [this](https://people.sphinx.chat/p/021ae436bcd40ca21396e59be8cdb5a707ceacdb35c1d2c5f23be7584cab29c40b/organizations)

**Expected behavior**
A semicolon should not be shown here

**Desktop (please complete the following information):**
 - Browser Chrome 120

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a screenshot or video in my PR

**Comment by ecurrencyhodler** [comment]
Wow that's really annoying. Good find. Here's a 25k bounty for it if you want it @Fog3211 https://community.sphinx.chat/bounty/1300

**Comment by MahtabBukhari** [comment]
@ecurrencyhodler could you assign me?

**Comment by Fog3211** [comment]
@ecurrencyhodler thanks , i will fix it 😀
