### ISSUE TITLE
Add "Generate Stories" Button and Modal to Feature View

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes-frontend#594]
## Context
The Hive Process Automation system currently lacks an automated story generation capability that would streamline the product management workflow. Product managers need to manually create user stories, which is time-consuming and can lead to inconsistent quality.

This ticket implements the UI components for the story generation feature, specifically adding a "Generate" button and associated modal dialog. This is part of the larger Hive User Story Automation initiative that will eventually connect to Stakwork Workflows for AI-assisted story generation.

The immediate implementation will include the UI components with a "coming soon" message, laying the groundwork for the full automation feature in subsequent phases.

### Button Implementation
- Add "Generate" button to the right of existing "Create" button in the user stories section
- Button styling:
  - Use existing UI component library styles
  - Primary button variant
  - Label text: "Generate"
  - Position: Right-aligned, next to "Create" button
  - Standard hover and active states

### Form Updates
- Reduce width of existing user story input form
- Reposition "Create" button to the left of the new "Generate" button
- Maintain existing form functionality

### Modal Implementation
- Route: `/feature/feature-id/stories/`
- Modal content:
  - Title: "Story Generation"
  - Message: "Coming Soon"
  - Cancel button: Returns to feature view
  - Backdrop: Clickable to dismiss
  - Centered on screen
  - Standard modal animations

[Image Placeholder]

UI updates - See sketch
![image](https://github.com/user-attachments/assets/66360c1a-304d-444e-8489-f3b16308fe3b)

Wireframe for Pop Up
![image](https://github.com/user-attachments/assets/a86a296e-27f7-46ff-8321-ba3d85e4877f)

## Assignment Criteria
Before requesting assignment:
- Ensure you have access to the sphinx-tribes-frontend repository
- Migrate to Sphinx V2 application
- Connect with Pete on Sphinx Community (https://community.sphinx.chat/p/cs7n8c2tu2rivj8gup0g)
- Familiarity with React and TypeScript required
- Understanding of React Router and modal implementations

## Acceptance Criteria
Frontend Implementation:
- [ ] Add "Generate" button to user stories section
  - [ ] Correct styling matching existing UI components
  - [ ] Proper positioning next to "Create" button
  - [ ] Hover and active states implemented
- [ ] Adjust user story input form width
- [ ] Reposition "Create" button to left of Generate button
- [ ] Implement modal component at `/feature/feature-id/stories/`
  - [ ] "Coming Soon" message displayed
  - [ ] Cancel button returns to feature view
  - [ ] Modal dismissible via backdrop click
  - [ ] Proper routing implementation

**Comment by aliraza556** [comment]
m

**Comment by saithsab877** [comment]
@humansinstitute assign me?

**Comment by MahtabBukhari** [comment]
@humansinstitute Could you please assign me?

**Comment by humansinstitute** [comment]
> @humansinstitute, Please assign me?

Added and assigned boutny on Stakwork. Reach out on Sphinx for more info.

**Comment by saithsab877** [comment]
> @saithsab877 / @MahtabBukhari - can you connect with me on Sphinx V2.
> 
> I just need to make sure I can discuss via V2. Lots more tickets and bounties coming - this helps assignments if I know you're set up and connected.

@humansinstitute, Ok.

**Comment by aliraza556** [comment]
Hi @humansinstitute, please check the message on Sphinx.
