### ISSUE TITLE
Workflows: Hive - Flex Audio to Data

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes-frontend#598]
## Objective:
A workflow to review transcriptions, audio monologues, meetings and extract useful structured data. 

### Background:
Hive will integrate Stakwork Workflows and automation into the Hive Development Process. This will reduce workload on Product Managers by streamlining creative tasks and automating the drafting of product artefacts and audit tasks.

This workflow will allow us to feed meeting recordings, monologues, phone calls or youtube videos into a workflow that will allow us to extract meaningful examples of product data e.g. mission, objectives, approach, requirements dependant on the specific data points we ask to be captured. 

A workflow stub is available at: https://jobs.stakwork.com/admin/workflows/35839/edit

#### Approach:
There are 3 main actions. 
- Transcribe / capture the audio as text vis existing Stakflow WFs
- Chunk an review the text to log data point and highlights of longer audio
- Review full highlights nad data points for summary data

#### Workflow Steps:

[Details in MIRO Wireframe Flow](https://miro.com/app/board/uXjVLLASyw8=/?moveToWidget=3458764605567293456&cot=10)

![image](https://github.com/user-attachments/assets/5b6d6838-d4dd-4ba9-9ed3-193795942638)

### Acceptance and Testing
- [ ] Build on https://jobs.stakwork.com/admin/workflows/35839/edit
- [ ] Please ensure that all steps in the workflow must be automated without manual intervention for the given test data.
- [ ] The output must adhere to the specified JSON formats and structures.
- [ ] Confirm JSON is received at: https://webhook.site/#!/view/0f5d5a20-3648-4625-ab90-9722b6731b7e 
- [ ] Confirm web hook can be overrode by setting in vars.webhook_url

#### Test Data

PW to upload:

- [x] Webhook URL for testing: https://webhook.site/0f5d5a20-3648-4625-ab90-9722b6731b7e
- [ ] Audio file to extract data - YT link
- [ ] Public audio file
- [ ] vars object

**Comment by Vayras** [comment]
Hey! @humansinstitute I'm vayras a long term contributor returning after a break let me know if I can work on this Thanks

**Comment by humansinstitute** [comment]
Posted in Wrong repo
