### ISSUE TITLE
onLoad of Modal pull data object for workflow on load of /feature/feature-id/stories/

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes-frontend#599]
## Context
The Hive Process Automation system currently lacks an automated story generation capability that would streamline the product management workflow. Product managers need to manually create user stories, which is time-consuming and can lead to inconsistent quality.

This ticket will load data for posting to stakflow for user story generation. 

Follow on from completion of modal here: https://github.com/stakwork/sphinx-tribes-frontend/issues/594

## Design

Three parts:

1) Retrieve required data on modal load
2) Create object ready to POST to stakwork
3) Display object in modal for testing / verification

### 1) Retrieve required data on modal load
On load of the modal acquire the following information from the endpoints on the Sphinx Back End (ask for more details if requied).

In Feature Routes:
- r.Get("/{uuid}", featureHandlers.GetFeatureByUuid) - retrieve $featureName, $featureBrief

In Workspace Routes: 
- r.Post("/mission", workspaceHandlers.UpdateWorkspace) -  retrieve $mission
- r.Post("/tactics", workspaceHandlers.UpdateWorkspace) - retrieve $tactics
- r.Post("/tactics", workspaceHandlers.UpdateWorkspace) - retrieve $tactics

### 2) Create object ready to POST to stakwork

WE need to produce an object in the following format. 
```
{ "postData" :
     {
                    "productBrief": "Product: Hive Automation Process. \nProduct Brief: \n* Mission: Build the software delivery methodology and supporting tooling for the AI age. \n* Objectives: \n* AI assisted workflows for all PM tasks \n* Generation of consistent and clean, deliverables tickets \n* Auto generation of Code and Test Coverage drafts for completion by developers. \n* Delivery of functional code from a crowd of developers \n* Self assignment through 'skin in the game' staking for developers \n* Full developer tooling and environment provision for 0 time to start coding.",
                    "featureName": "User Story Automation",
                    "description": "Hive Process integrates Stakwork Workflows and LLM based automation into the Hive Development Process. This will reduce workload on Product Managers by streamlining creative tasks and automating the drafting of product artefacts and audit tasks.\n In this feature we will automate the production of User Stories and Requirements from a Product Brief and Feature Brief.\n This will leverage a Stakwork workflow which will take the following steps: 1. Load the product context and specific feature context. 2. Generate a series of user stories in the workflow as a JSON object. 3. Iterate through the user stories and score them for relevance against the product and feature context. 4. Filter out low relevance scores 5. Return the information to a form in the Hive Process for human review and acceptance.",
                    "examples": [ ],
                    "webhook_url": "https://webhook.site/8adf917d-d292-47ce-88e8-3994f63bfcce",
                    "featureUUID": "csldm4knuku6oosk3rng"
                }
 }
```

Literal of the Product Brief:
```
productBrief = `Product: ${name}. Product Brief:\n Mission: ${mission}.\n\n Objectives: ${tactics}`
```

Feature Name = $featureName
description = $featureDescription
examples = [ ] (will be an empty array for now that will be populated with examples later)

### 3) Display object in modal for testing / verification

Please display $postData object in the modal for verification and testing of this change.  (this will be removed in next phase)

## Assignment Criteria
Before requesting assignment:
- Ensure you have access to the sphinx-tribes-frontend repository
- Migrate to Sphinx V2 application
- Connect with Pete on Sphinx Community (https://community.sphinx.chat/p/cs7n8c2tu2rivj8gup0g)
- Familiarity with React and TypeScript required
- Understanding of React Router and modal implementations

## Acceptance Criteria
Frontend Implementation:
- [ ] On load correct data is returned for this feature and related workspace
- [ ] Correct data is displayed in the modal for verification
- [ ] Modal retains features from previous ticket https://github.com/stakwork/sphinx-tribes-frontend/issues/594

**Comment by aliraza556** [comment]
H

**Comment by saithsab877** [comment]
,

**Comment by MahtabBukhari** [comment]
f
