### ISSUE TITLE
Fix the issue on the organization's bounties page where the background of an open bounty disappears on hover

### ISSUE THREAD

**Issue by MahtabBukhari** [stakwork/sphinx-tribes-frontend#60]
**Describe the bug**
On the organization's bounties page where the background of an open bounty vanishes upon hovering.
https://www.loom.com/share/28ed4c5138034d7181ed5a6f0ab90049?sid=c75a0a30-0d7e-4bf9-b928-3a8cff6faac5

**To Reproduce**
1. Go to 'bounties page' https://community.sphinx.chat/bounties
2. Click on ' organization link name'
3. Hover on open bounties https://community.sphinx.chat/org/bounties/cmg6oqitu2rnslkcjbqg
4. You will See that on hovering the open bounties on organization page backgroud will disappear

**Expected behavior**
The background should not disappear; instead, it should display as white with a shaded border, similar to the bounty page.

**Desktop (please complete the following information):**
 - Browser [chrome]

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a screenshot or video in my PR

**Comment by MahtabBukhari** [comment]
@ecurrencyhodler could you see this one and assign me?

**Comment by ecurrencyhodler** [comment]
Let me chat with design about this. Thanks for reporting it. When we turn it into a bounty it will be yours.
