### ISSUE TITLE
Initiate workflow on page load (send POST request to stakwork)

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes-frontend#600]
Blocked until complete of https://github.com/stakwork/sphinx-tribes-frontend/issues/599

## Context
The Hive Process Automation system currently lacks an automated story generation capability that would streamline the product management workflow. Product managers need to manually create user stories, which is time-consuming and can lead to inconsistent quality.

This ticket will POST data to the Stakwork Workflow for User Story generation. 

Follow on from completion of:
1. The modal: https://github.com/stakwork/sphinx-tribes-frontend/issues/594
2. The data retrieval: https://github.com/stakwork/sphinx-tribes-frontend/issues/599

## Design

Take the data object postData from the previous ticket and make a request to the Sphinx Tribes End poInt -specified here: https://github.com/stakwork/sphinx-tribes/issues/1917 which should be accessible at community.sphinx.chat/features/stories/send

Where formdata = 

```
{
   "productBrief": "Product: Hive Automation Process. \nProduct Brief: \n* Mission: Build the software delivery methodology and supporting tooling for the AI age. \n* Objectives: \n* AI assisted workflows for all PM tasks \n* Generation of consistent and clean, deliverables tickets \n* Auto generation of Code and Test Coverage drafts for completion by developers. \n* Delivery of functional code from a crowd of developers \n* Self assignment through 'skin in the game' staking for developers \n* Full developer tooling and environment provision for 0 time to start coding.",
                    "featureName": "User Story Automation",
                    "description": "Hive Process integrates Stakwork Workflows and LLM based automation into the Hive Development Process. This will reduce workload on Product Managers by streamlining creative tasks and automating the drafting of product artefacts and audit tasks.\n In this feature we will automate the production of User Stories and Requirements from a Product Brief and Feature Brief.\n This will leverage a Stakwork workflow which will take the following steps: 1. Load the product context and specific feature context. 2. Generate a series of user stories in the workflow as a JSON object. 3. Iterate through the user stories and score them for relevance against the product and feature context. 4. Filter out low relevance scores 5. Return the information to a form in the Hive Process for human review and acceptance.",
                    "examples": [ ],
                    "featureUUID": "bcbc7b98-7ad3-48ce-b339-897723346c13"
                    }
```

Literal of the Product Brief:
```
productBrief = `Product: ${name}. Product Brief:\n Mission: ${mission}.\n\n Objectives: ${tactics}`
```

Feature Name = $featureName
description = $featureDescription
examples = [ ] (will be an empty array for now that will be populated with examples later)

### 3) When you POST The Data 
Display a success or fail response in the modal window.

## Assignment Criteria
Before requesting assignment:
- Ensure you have access to the sphinx-tribes-frontend repository
- Migrate to Sphinx V2 application
- Connect with Pete on Sphinx Community (https://community.sphinx.chat/p/cs7n8c2tu2rivj8gup0g)
- Familiarity with React and TypeScript required
- Understanding of React Router and modal implementations

## Acceptance Criteria
Frontend Implementation:
- [ ] On load correct data is returned for this feature and related workspace
- [ ] Correct data is displayed in the modal for verification
- [ ] Modal retains features from previous ticket https://github.com/stakwork/sphinx-tribes-frontend/issues/594

**Comment by jordan-ae** [comment]
Please assign me

**Comment by MuhammadUmer44** [comment]
N

**Comment by MahtabBukhari** [comment]
s

**Comment by aliraza556** [comment]
@humansinstitute, Please assign me?
