### ISSUE TITLE
Update the stakwork bearer token as an environment variable

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes-frontend#608]
@elraphty - Discuss with me via Sphinx. 

Add an environemnt variable for the stakwork - workflow bearer token.

Please set environemtn variable name = "SWWFKEY" e.g.

`SWWFKEY="aaaaahhhhhnnnnooooo"`

**Comment by aliraza556** [comment]
M

**Comment by MuhammadUmer44** [comment]
M
