### ISSUE TITLE
Streamline User Flow - "Reveal Connection Codes"

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes-frontend#609]
## Context
Streamline the user onboarding flow by removing redundant steps in the "Get Sphinx" journey, specifically eliminating the repeated step where users must confirm they want to get Sphinx after already selecting that option.

### Current Behavior
- Main page presents two options: "Sign In" and "Get Sphinx"
- Clicking "Get Sphinx" shows a modal with Step 1 (repeat of choice) and Step 2 (app download/connection code)
- Step 1 is redundant as the user has already made this choice

### Desired Behavior

- Clicking "Get Sphinx" should directly open the modal to Step 2
- Step 1 should be completely removed from the workflow
- The "I have sphinx" option should continue to redirect to the sign-in modal

Step 1: 
![Image](https://github.com/user-attachments/assets/3369da77-1242-4e4b-871a-25547521532b)

Step 2: 
![Image](https://github.com/user-attachments/assets/fc2a9acc-ae79-4625-9e7f-4d1d7491871d)

### Modal Component Changes:

- [ ] Modify modal initialization to start directly at Step 2
   - Remove step counter/state if only used for this flow
   - Modify entry point to render Step 2 content directly
- [ ] Remove Step 1 modal content and related state
- [ ] Preserve "I have sphinx" redirect functionality to the log in modal

## Assessment criteria

- [ ] Record loom video of the change  and attached to pull request or ticket on close.  
- [ ] Clicking "Get Sphinx" on the main page immediately shows the Step 2 modal
- [ ] No step 1 is visible
- [ ] All existing functionality in Step 2 remains unchanged:
   - App download option works
   - Connection code reveal works
   - "I have sphinx" redirect works
- [ ] Modal Responds Correctly on:
   - [ ] Android
   - [ ] iPhone
   - [ ] Desktop browsers

**Comment by saithsab877** [comment]
M

**Comment by Vayras** [comment]
@humansinstitute can you assign this to me? Thanks

**Comment by saithsab877** [comment]
Hi @humansinstitute, please confirm this point:
In Step #2, remove the Back and Sign In buttons and add an 'I have Sphinx' button instead.

![image](https://github.com/user-attachments/assets/6c2c2c4e-7a5e-4ec0-b1e6-b98e769dbcd8)

**Comment by saithsab877** [comment]
@humansinstitute, is this the desired behavior for Step #2? Am I correct?

![image](https://github.com/user-attachments/assets/ec1f7b17-412e-45f1-b011-30a4fcdc00e0)

**Comment by humansinstitute** [comment]
I would suggest just remove the back link and keep "Sign In" as a grey text link but center aligned now we've removed back.

**Comment by saithsab877** [comment]
> * "I have sphinx" redirect works
> *

@humansinstitute, Ok mean `I have Sphinx` not show any step

![image](https://github.com/user-attachments/assets/15549d73-42f9-4bd6-8eac-bf3035410ccd)

**Comment by saithsab877** [comment]
Hi @humansinstitute, Also remove this Step - 3

![image](https://github.com/user-attachments/assets/18075d44-d3e7-42dd-a4c8-f1e70d4fea53)

**Desired Behavior:**

When the user clicks the `Sign In` button, this modal opens directly.

![image](https://github.com/user-attachments/assets/9829cd79-a16b-4713-a426-a38c9d6d49db)

**Comment by humansinstitute** [comment]
Yes that right that 3rd step also if redendant and should be removed after you click sign in you shouhld go directly to the sign in modal

**Comment by saithsab877** [comment]
> Yes that right that 3rd step also if redendant and should be removed after you click sign in you shouhld go directly to the sign in modal

@humansinstitute, Sure.

**Comment by humansinstitute** [comment]
@saithsab877 - do you have a OR on this one?
