### ISSUE TITLE
Bug Payments

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes-frontend#612]
Key send error on response when trying to send payments.

![image](https://github.com/user-attachments/assets/cf55fdb4-6367-4018-8a07-99f57a58cb6e)

![image](https://github.com/user-attachments/assets/178bba19-a358-42b4-90e6-25c3477d6af3)

![image](https://github.com/user-attachments/assets/f10d539d-d47e-4db8-8f8f-7ee257f39ef3)

Happens on two different payments.

**Comment by aliraza556** [comment]
.

**Comment by MuhammadUmer44** [comment]
@humansinstitute assign me
