### ISSUE TITLE
Bug: New Private Bounties - on accept shows last public bounty

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes-frontend#614]
Reported by Tom S. 

Create a bounty, fill out details. Don't publicly broadcast and assign privately. 
When you exit out of the process - the user is shown the preview of the last public bounty that was on the site.

**Comment by jordan-ae** [comment]
Can help out

**Comment by MuhammadUmer44** [comment]
@humansinstitute Please assign me

**Comment by aliraza556** [comment]
@humansinstitute Please assign me?

**Comment by humansinstitute** [comment]
@aliraza556 - we're seeing this here as well on [616](https://github.com/stakwork/sphinx-tribes-frontend/issues/616)
