### ISSUE TITLE
Bug - Github Link is "doubled up" (Quick)

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes-frontend#620]
When clicking through to a github issue from the bounties site, it goes to a "double up" of the URL and doesn't load. 

e.g. the actual link would be `https://github.com/githubissue` instead it goes to `https://github.com/githubissuehttps://github.com/githubissue`

See video
When https://github.com/user-attachments/assets/50d371ce-e643-4a0e-868a-0045c915658f

### Assignment
- Simple fix first come first serve
- Ensure you have a V2 Sphinx account for comms and payment.

**Comment by Ekep-Obasi** [comment]
Please assign me

**Comment by aliraza556** [comment]
m

**Comment by humansinstitute** [comment]
Sorry Ekep was first on that one. Should be a quick fix.

**Comment by humansinstitute** [comment]
No problem will close out and resolve bounty.
