### ISSUE TITLE
Filtering by `pending` showing `Paid` bounties

### ISSUE THREAD

**Issue by tomsmith8** [stakwork/sphinx-tribes-frontend#625]
**Task**

Filtering by `pending` showing `Paid` bounties

<img width="1241" alt="image" src="https://github.com/user-attachments/assets/2a28e08e-1f98-4f78-b334-f1311e61d74a">

**Comment by MahtabBukhari** [comment]
t

**Comment by Vayras** [comment]
Hey! @tomsmith8 can you assign me to this

**Comment by aliraza556** [comment]
@tomsmith8, I have already created issue https://github.com/stakwork/sphinx-tribes-frontend/issues/586

**Comment by aliraza556** [comment]
@tomsmith8, @humansinstitute Please assign me?

**Comment by Vayras** [comment]
Thanks @humansinstitute can you send me link to the newer app version or like the one that works 

Neither the one from playstore ot test flight is connecting to a node

**Comment by humansinstitute** [comment]
Instructions to get Sphinx Chat V2 on iOS and Mac:

1. Install TestFlight app on your Mac or iOS device from AppStore

2. Follow this link and the instructions there to join the public group: https://testflight.apple.com/join/p721ALD9

3. Go back to TestFlight app and “Sphinx Chat V2” will be available to be installed (make sure you select the right platform tab on the top: macOS/iOS)

Instructions for Android:
Download via play store - https://play.google.com/store/apps/details?id=chat.sphinx.v2

**Comment by Vayras** [comment]
@humansinstitute thank you 🚀

**Comment by Vayras** [comment]
@humansinstitute upon pasting the old key I'm seeing this, can you please help me get back onboarded 
![Screenshot 2024-11-08 at 5 45 23 PM](https://github.com/user-attachments/assets/9480fce2-8a01-4598-bb97-4ade6bcebe8f)

**Comment by tomsmith8** [comment]
@Vayras email me at tomsmith@stakwork.com and i'll send you an invite code (it'll be a new account)

**Comment by Vayras** [comment]
@tomsmith8 sent you an email, Thanks

**Comment by Vayras** [comment]
@tomsmith8 thanks for onboarding me, I'm Vayras V2 on sphinx now

cc:@humansinstitute

**Comment by humansinstitute** [comment]
@Vayras assigned on bounties to your v2

**Comment by humansinstitute** [comment]
@Vayras can you sign up for a follow up here: https://github.com/stakwork/sphinx-tribes-frontend/issues/636
