### ISSUE TITLE
Update Sphinx LInks with Correct V2 pubkey encoding to add people form registry

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes-frontend#635]
Correct the encoding to V2 pubkeys in the boutnies front end. 

- Select user with Pub Key V2 e.g. "[Pete](https://community.sphinx.chat/p/cs7n8c2tu2rivj8gup0g/)"
- Click through on QR code for connection details

![image](https://github.com/user-attachments/assets/40e6026b-7f21-401f-840e-6822e5c0b81d)

1. Clicking open in sphinx will correctly open the user in sphinx app -> works correctly
2. Scan QR with Phone -> works correctly
3. Copy and pasting the pebkey and adding via sphinx -> doesn't work
4. Copy and pasting the pubkey into a chat in sphinx -> generates a connect button -> clicking this doesn't work

This is due to the data in the pub key being displayed for copying being incorrect formated. 

```
- V1 Pubkey (General) ->    <part1>:<part2>:<part3>     // Filter Out [V1 format - will be removed]
- V2 Pubkey (Bounties) ->  <part1>:<part2>_<part3>    // This is how the Pubkey is displayed 
- V2 Pubkey (Sphinx) ->     <part1>_<part2>_<part3>   // Allow [correct V2 format]
```

We need to ensure that the correct encoding is used in displaying and copying of this pubkey.

```
let part1 = <part1>
let part2 = <part2>
let part13 = <part3>
pubkey = `${part1}_${part2}_${part3}`
```

**Comment by humansinstitute** [comment]
@saithsab877 - follow up task to https://github.com/stakwork/sphinx-tribes/issues/1944

**Comment by saithsab877** [comment]
@humansinstitute Please assign me

**Comment by saithsab877** [comment]
> @saithsab877 - follow up task to https://github.com/stakwork/sphinx-tribes/issues/1944 

Sure
