### ISSUE TITLE
User Story Submission - UI Response Tidy

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes-frontend#648]
This user story form shows the JSON data received to assist in debugging. This should be made more human friuendly now the feature is deployed. 

![Image](https://github.com/user-attachments/assets/6a9f9b76-91bb-48cf-a489-0c1c823998d5)

This form should be updated to allow a cleaner display of the data, showing the success or failure of the workflow submission with the following messages. 

E.g. UI:

![Image](https://github.com/user-attachments/assets/9e72c8de-d0b9-44cc-b493-8b8fc199e4f4)

- On success -> Workflow submitted please check back in 5 minutes and refresh the feature screen.
- On fail -> Workflow failed: Please contact Hive Product Manager
- Display a close button which exits modal with no further action not (cancel / send)

## Assignment Criteria

Moving Forwards 
- [ ] Assignment will only be made by contact through Sphinx V2
- [ ] Find Bounty in Bounties site (in Bounties workspace) and connect with correct bounty link in message
- [ ] Ensure familiarity with UI design in Sphinx Tribes Frontend

## Assessment Criteria
- [ ] Form correctly shows success / fail message
- [ ] Form now only displays close button

**Comment by aliraza556** [comment]
@humansinstitute please assign me

**Comment by MahtabBukhari** [comment]
f

**Comment by saithsab877** [comment]
@humansinstitute assign me

**Comment by humansinstitute** [comment]
@aliraza556 @MahtabBukhari @saithsab877 - see assignment notes
