### ISSUE TITLE
Allow editing of features name

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes-frontend#650]
Currently on a feature once created it's name cannot be edited or it cannot be deleted. 

The functionality exists in the code to edit. 

- This will utilise the route `r.Post("/", featureHandlers.CreateOrEditFeatures)`
- and handler code in https://github.com/stakwork/sphinx-tribes/blob/master/handlers/features.go#L42

In order to add the edit feature setup a editing button on the feature page and provide the following functionality.

![Image](https://github.com/user-attachments/assets/1134180b-e235-43b1-a562-2f2dd6077ee1)

This will include the following changes: 

1. add edit menu on feature page
2. On click display an "edit" action in the pop up 
3. Reload page with editable name text box and buttons cancel, update
4. On cancel reload original name
5. On update post required data to the route `r.Post("/", featureHandlers.CreateOrEditFeatures)`

## Assignment Criteria

Moving Forwards 
- [ ] Assignment will only be made by contact through Sphinx V2
- [ ] Find Bounty in Bounties site (in Bounties workspace) and connect with correct bounty link in message
- [ ] Ensure familiarity with UI design in Sphinx Tribes Frontend

## Assessment Criteria
- [ ] Form correctly updates the name on reload after update is clicked
- [ ] Form correctly reverts to the previous name on cancel
- [ ] Follow the same flow for other page edit functions in this view

**Comment by saithsab877** [comment]
@humansinstitute assign me?

**Comment by Vayras** [comment]
@humansinstitute can I work on this?
