### ISSUE TITLE
Update Feature Brief form to generate a workflow request

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes-frontend#651]
## Context
The Hive Process Automation will add the production of Feature Briefs from Audio recordings. This will allow PMs to create an audio recording and use this to generate product information. 

In Phase 1 this will focus on creating a feature brief from an audio description. 

## Design

![image](https://github.com/user-attachments/assets/87c71433-3dfa-4e01-9b3e-0d011f17dc98)

#### Button Implementation
- Add "Audio Generation" button to the right of Feature Brief
- Button styling:
  - Use existing UI component library styles
  - Primary button variant
  - Label text: "Audio Generation"
  - Position: Right-aligned, vertical aligned with 'Feature Brief' Label.

#### Modal Implementation
- Modal content:
  - Title: "Enter Audio Recording URL"
  - Cancel button: Returns to feature view with no action
  - Form: single text field, editable for a public URL for a AudioDataWorkflow. 
  - Submit button: Display success fail action. 
  - Backdrop: Clickable to dismiss
  - Centered on screen
  - Standard modal animations

### POST Data on Submit

1. Generate Data 
```
{ 
    "postData" :
    {
        "audioLink": "CAPTURE FROM FORM",
        "featureUUID": "FROM PREVIOUS PAGE",
        "source": "featureBrief",
        "examples":["Hive Process integrates Stakwork Workflows and LLM based automation into the Hive Development Process. This will reduce workload on Product Managers by streamlining creative tasks and automating the drafting of product artefacts and audit tasks. \nIn this feature we will automate the production of User Stories and Requirements from a Product Brief and Feature Brief. \nThis will leverage a Stakwork workflow which will take the following steps:\n1. Load the product context and specific feature context. \n2. Generate a series of user stories in the workflow as a JSON object. \n3. Iterate through the user stories and score them for relevance against the product and feature context. \n4. Filter out low relevance scores\n5. Return the information to a form in the Hive Process for human review and acceptance."]
    }
}

```
2. Post to Sphinx Back End at `/features/brief/send'
3. On Success Show Model Success State / On fail Show fail state.

## Assignment Criteria
Before requesting assignment:
- Ensure you have access to the sphinx-tribes-frontend repository
- Migrate to Sphinx V2 application
- Connect with Pete on Sphinx Community (https://community.sphinx.chat/p/cs7n8c2tu2rivj8gup0g)
- Familiarity with React and TypeScript required
- Understanding of React Router and modal implementations

## Acceptance Criteria
Frontend Implementation:
- [ ] Meets UI Design
- [ ] Correct styling matching existing UI components
- [ ] Implement modal flow
- [ ] Calls End Point at `/features/brief/send'

**Comment by saithsab877** [comment]
H

**Comment by aliraza556** [comment]
@humansinstitute assign me

**Comment by Vayras** [comment]
@humansinstitute can you assign me to this
