### ISSUE TITLE
Phase Planner Page accessed from Feature > Phase.

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes-frontend#658]
## Context

Implement a new Phase Planner view allowing Product Managers to create and edit multiple work tickets within a phase. 

## Task
1. Create route `/feature/{UUID}/phase/{UUID}/planner`
2. Display Feature and Phase names from API endpoints
3. Create test case to load view and check Feature adn Phase name.

## Outcome
A simple Phase Planner page accessed at community.sphinx.chat/feature/{UUID}/phase/{UUID}/planner that displays the Feature Name and Phase Name.

### UI Layout
- See Image below
- Ensure current styles are followed.

![image](https://github.com/user-attachments/assets/b565edde-67e1-4fa9-ad73-c5b785658425)

The page will be populated as follows from Tribes endpoints: 
- Feature Name: `r.Get("/{uuid}", featureHandlers.GetFeatureByUuid)`
- Phase Name: `r.Get("/{feature_uuid}/phase/{phase_uuid}", featureHandlers.GetFeaturePhaseByUUID)`

Acceptance Criteria

- [ ] Route /feature/{UUID}/phase/{UUID}/planner can be accessed and displays page.
- [ ] Feature and Phase names display correctly

**Comment by jordan-ae** [comment]
I can help

**Comment by aliraza556** [comment]
@humansinstitute Please assign me

**Comment by Vayras** [comment]
@humansinstitute can you please assign me to this

**Comment by aliraza556** [comment]
Hi @humansinstitute,

My work is complete. Please merge this PR: https://github.com/stakwork/sphinx-tribes-frontend/pull/661. Once it is merged, I will create my own PR. If I create it now, I might face conflicts after this PR is merged.

So, please merge this PR.

My Work Demo:

https://www.loom.com/share/b6b2ce533a95422b80db0f8bf1995c2f
