### ISSUE TITLE
Hide Organization's Post Bounty Bounty When User's Don't Access

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes-frontend#66]
### Context

The post bounty button in an organization page shouldn't be visible if a user is not logged in, or the user does not have a manage bounty role for that organization.

Loom Video 

https://www.loom.com/share/ad5174ff776e4e808124da9d10934f4e

### Acceptance Criteria
- [ ] I've tested on Chrome
- [ ] I've submitted a screenshot or recording in my pr
- [ ] I've created a unit test that checks for the display of the post-bounty button 

Here is an [example unit test](https://github.com/stakwork/sphinx-tribes/blob/master/frontend/app/src/helpers/__test__/helpers.spec.ts)

Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

**Comment by ChetanKarwa** [comment]
@elraphty I would like to pick this one
@ecurrencyhodler

**Comment by aliraza556** [comment]
Hi @elraphty @ecurrencyhodler Please assign me.

**Comment by ChetanKarwa** [comment]
I think the better way to solve this is to add this here.
<img width="1223" alt="image" src="https://github.com/stakwork/sphinx-tribes-frontend/assets/46815976/6b909851-0b25-4401-8a6e-9610114000e2">

**Comment by ecurrencyhodler** [comment]
@aliraza556 this is yours! I'll create a 200k bounty for it.

**Comment by aliraza556** [comment]
> @aliraza556 this is yours! I'll create a 200k bounty for it.

Thanks

**Comment by aliraza556** [comment]
Hi @elraphty @ecurrencyhodler,
 Could you please review this PR #102
