### ISSUE TITLE
Update 'ticket editor' component - on page load / refresh display db.ticket.description as content in box

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes-frontend#674]
Update ticket editor component. If it is loaded with a ticket UUID existing. e.g. on a page refresh it will fetch the relevant ticket details from endpoint /bounty/ticket/UUID

Using  "read" in request structure.

```
// Request structure
type TicketRequest struct {
    Action string       `json:"action"`  // "read"|"update"|"delete"
    Ticket types.Ticket `json:"ticket"`
}
```

**Comment by MuhammadUmer44** [comment]
@humansinstitute Please assign me

**Comment by aliraza556** [comment]
@humansinstitute Please assign me

**Comment by humansinstitute** [comment]
@aliraza556 this is the last piece of the puzzle to add in and get merged for testing.
