### ISSUE TITLE
[BUG] Front - Back End Routing Conflict

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes-frontend#677]
A number of routes on the back end tribes server were specified as /bounty/ticket/*

This caused issues as this route is hardcoded in the proxy server for the front end. 

The backend, endpoint will be updated to /bounties/ticket/* we will need to make several changes to the front end to ensure functionality works moving forwards. 

- [ ] On Load of ticket editor component - call /bounties/ticket/ticketUUID
- [ ] On Click of `Update` button in `ticketEditor` component - call `/bounties/ticket/ticketUUID`
- [ ] On Click of `Ticket Builder` button in `ticketEditor` component - call `/bounties/ticket/review/send`

Please ensure all CORS types are correct for the endpoints, routes you are calling.

**Comment by MahtabBukhari** [comment]
@tobi-bams @humansinstitute  AT frontend side while testing locally getting 500 error with POST request now




![image](https://github.com/user-attachments/assets/1e74518d-8e7b-4f0b-a8e6-e6a182f073e5)

![image](https://github.com/user-attachments/assets/51730418-5294-4326-9ac6-eba11b84ceee)

**Comment by MahtabBukhari** [comment]
with GET method request does not make and with PUT method the request giving 405 error

**Comment by MahtabBukhari** [comment]
@humansinstitute @tobi-bams while testing from postman this endpoint working fine on backend side

![image](https://github.com/user-attachments/assets/f31b902b-15e8-4f66-b28b-8e1ff72eeff1)

**Comment by tobi-bams** [comment]
> @humansinstitute @tobi-bams while testing from postman this endpoint working fine on backend side
> 
> ![image](https://private-user-images.githubusercontent.com/98140673/391336087-f31b902b-15e8-4f66-b28b-8e1ff72eeff1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwOTI4NTcsIm5iZiI6MTczMzA5MjU1NywicGF0aCI6Ii85ODE0MDY3My8zOTEzMzYwODctZjMxYjkwMmItMTVlOC00ZjY2LWIyOGItOGUxZmY3MmVlZmYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAxVDIyMzU1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4MTA1OTNiMTk0M2Q1MDMzMGQxMzk3ZDdmMGUzZTQzZDA3MGQ3YmJiYmJkYzI4NjM1OTgzZjIwN2JiZWZjN2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qiwo2W08w4wgppp4E_3ObhkmFMnPFYkWywAkbB9wbgY)

Yea, it's expected to work actually. You might be using a more recent database on your machine.
