### ISSUE TITLE
JS crash when trying to edit an old bounty

### ISSUE THREAD

**Issue by Evanfeenstra** [stakwork/sphinx-tribes-frontend#68]
**Describe the bug**
JS crash when opening an old bounty. Some data must be missing. JS should never run `.map` or similar functions on an array that might be `undefined`.

<img width="667" alt="Screenshot 2024-01-29 at 8 41 44 AM" src="https://github.com/stakwork/sphinx-tribes-frontend/assets/7184040/8eb35796-993d-493a-80ed-a1b208c2f699">

**Comment by VividhPandey003** [comment]
Oh this is an issue I've created earlier - https://github.com/stakwork/sphinx-tribes/issues/1365

**Comment by ChetanKarwa** [comment]
@ecurrencyhodler Assign this to me please

**Comment by Evanfeenstra** [comment]
In my case its due to the "type" of the bounty being `wanted_coding_task` when actually that is not a valid "type"

<img width="646" alt="Screenshot 2024-01-29 at 8 47 59 AM" src="https://github.com/stakwork/sphinx-tribes-frontend/assets/7184040/ab590b7e-fffd-4fa4-9af0-982a7224cc10">
<img width="735" alt="Screenshot 2024-01-29 at 8 48 07 AM" src="https://github.com/stakwork/sphinx-tribes-frontend/assets/7184040/8b24f32a-5498-46d2-bc70-16b1ff1b66aa">

**Comment by VividhPandey003** [comment]
Wait actually its the same issue. Uum could you maybe check if these bounties are visible to you:


https://people.sphinx.chat/bounty/75 , https://people.sphinx.chat/bounty/252

**Comment by Evanfeenstra** [comment]
i fixed my error with a DB query

**Comment by VividhPandey003** [comment]
> i fixed my error with a DB query

Oh Okay. Thanks for the information

**Comment by ecurrencyhodler** [comment]
@VividhPandey003 I do see the bounties. I think I'm going to do a partial payout for your work and close your PR unless your PR fixes something else. Sorry about the confusion and thanks for your work. 

This was something we ended fixing as part of a larger issue.

**Comment by VividhPandey003** [comment]
@ecurrencyhodler Hey no issues. This platform is not just about earning bounties for me. I'd love to make meaningful contributions and since the issue now seems fine i guess we could close it.

**Comment by VividhPandey003** [comment]
Thanks a lot @ecurrencyhodler. 

@Evanfeenstra I am new to Js/Ts. I'd really love to know how you derived this conclusion. 

When I saw the issue I thought that the issue is that I just need to tackle undefined cases thus I updated the code by using alternatives for map.

You had recently discovered the bug and seemed to fix it in no time. I would want such debugging skills. Would you mind sharing how you fixed it?
