### ISSUE TITLE
[BUG] Front End change - update page to call new endpoint

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes-frontend#683]
- [ ] Front End change - update page to call new endpoint

Linked to back end changes on: https://github.com/stakwork/sphinx-tribes/issues/2026

Planner Page attempts to GET ticket details at: /feature/featureUUID/phase/phaseUUID
Update the Call endpoint to GET /bounties/tickets/feature/uuid/phase/uuid/

**Comment by aliraza556** [comment]
.

**Comment by humansinstitute** [comment]
I just realised I made a mistake in this ticket. 

The code we changed here was actually used to get Phase Details and returned the phase name, so the end point it was using was in fact correct and didn't need to be changed. 

Are you able to add a PR to revert this change?

**Comment by humansinstitute** [comment]
Update line 3585 to 
`const r: any = await fetch(`${TribesURL}/features/${feature_uuid}/phase/${phase_uuid}`,`
