### ISSUE TITLE
On Click of `Ticket Builder` trigger pop up that communicates success or failure for POST to `/bounties/ticket/review/send`

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes-frontend#689]
On click of `Ticker Builder` button 
Trigger a pop response to the user indicate successful submission or failure, based on POST reponse.
Sucess message = "Success, I'll rewrite your ticket now!"
Fail message = "Sorry, there appears to be a problem"

Currently there is no response to clicking the button, leaving the user at a loss for whether anything has happened.

![Image](https://github.com/user-attachments/assets/c752186f-c57d-4291-8eee-f7fb0f4946bb)

**Comment by saithsab877** [comment]
G

**Comment by humansinstitute** [comment]
@saithsab877 go for it,
