### ISSUE TITLE
Log the websocket session ID to the console

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes-frontend#693]
On logging in to Sphinx Tribes users are provided a unique websocket connection between Front end and Tribes.
This change would simply log the current session ID to the console on load of the phase planner page. 
Log: `Websocket Session ID: ${sessionID}`

**Comment by aliraza556** [comment]
,

**Comment by MahtabBukhari** [comment]
@humansinstitute assign me

**Comment by saithsab877** [comment]
@humansinstitute I can help?

**Comment by humansinstitute** [comment]
@aliraza556 any luck?

**Comment by aliraza556** [comment]
Hi @humansinstitute, I try but i get error:

![image](https://github.com/user-attachments/assets/36f75122-0b8f-4665-981a-236ead7767b9)
