### ISSUE TITLE
On Click of `Update` button trigger a pop up that communicates success or failure for POST to `/bounties/ticket/uuid`

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes-frontend#694]
Similar implementation to https://github.com/stakwork/sphinx-tribes-frontend/issues/689

On click of `Update` button 

Trigger a pop response to the user indicate successful submission or failure, based on POST reponse.

Success message ->
- Title: Hive
- Message: "Updates Saved!"

Success message ->
- Title: Hive
- Message: "We had an issue, try again!"

Currently there is no response to clicking the button, leaving the user at a loss for whether anything has happened.

![Image](https://github.com/user-attachments/assets/c752186f-c57d-4291-8eee-f7fb0f4946bb)

**Comment by saithsab877** [comment]
,

**Comment by humansinstitute** [comment]
@saithsab877 Can you have a quick look at this. Checking out the testing I can see that if i make a second update to the editor box and click the link then I no longer receive the toast feedback.

The feedback should persist on each click of `update` or `ticket builder`

**Comment by saithsab877** [comment]
> @saithsab877 Can you have a quick look at this. Checking out the testing I can see that if i make a second update to the editor box and click the link then I no longer receive the toast feedback.
> 
> The feedback should persist on each click of `update` or `ticket builder`

@humansinstitute, I will check and fix it right now
