### ISSUE TITLE
Implement TicketMessage Interface for WebSocket Communication in Front End

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes-frontend#695]
# Ticket Name: Implement TicketMessage Interface for WebSocket Communication

## Context
- **Problem**: The current system lacks an interface for processing and passing messages through a WebSocket connection in the front end for ticket updates. when processing workflows.
- **Need**: Introducing a structured `TicketMessage` interface will standardise message handling and ensure consistent communication.
- **Background**: The system currently uses WebSocket connections for real-time data updates, but lacks a message format for passing ticket updates from forn end to backend.

## Task
1. Create a new TypeScript interface named `TicketMessage`.
2. Define the properties:
   - `broadcastType`: Specifies if the message is sent directly or to the entire pool.
   - `sourceSessionID`: Identifies the user session for direct messages.
   - `message`: Contains the content to be transmitted.
   - `action`: Determines if the operation is to process or simply pass the message.
   - `ticketDetails`: Includes information related to the ticket, supporting multiple input types.
3. Integrate the `TicketMessage` interface into the existing WebSocket communication logic.

## Outcome
- A new `TicketMessage` interface is available allowing for structured and efficient message handling via WebSocket.

## Example Code
```typescript
export interface TicketMessage {
  broadcastType: 'pool' | 'direct';   // Send direct or to whole pool
  sourceSessionID: string;               // User session source session ID for direct message
  message: string;                            // Message to be transmitted
  action: 'process' | 'message';       // Action to be performed
  ticketDetails: Ticket                       // The existing Ticket Type Interface to contain ticket details.
}

// Example usage
const exampleMessage: TicketMessage = {
  broadcastType: 'direct',
  sourceSessionID: 'abc123',
  message: 'Update ticket details',
  action: 'process',
  ticketDetails: { /* Ticket object */ }
};
```

## Acceptance Criteria
- [ ] The `TicketMessage` interface is correctly implemented in TypeScript.

**Comment by MuhammadUmer44** [comment]
.

**Comment by MahtabBukhari** [comment]
s

**Comment by Vayras** [comment]
@humansinstitute please assign me

**Comment by humansinstitute** [comment]
For assignment - confirm you are free to work on this and complete within the next 2 hours.

**Comment by MuhammadUmer44** [comment]
Sure
