### ISSUE TITLE
Save tickets by phase in the store

### ISSUE THREAD

**Issue by tobi-bams** [stakwork/sphinx-tribes-frontend#701]
#### **Objective**
We want to ensure that tickets are stored in the global store to allow updates dynamically and efficiently.

#### **Proposed Solution**
In the [main.ts](https://github.com/stakwork/sphinx-tribes-frontend/blob/master/src/store/main.ts) file, create a new property, perhaps called `phaseTickets`, in the global store.

#### **Structure of `phaseTickets`**
The `phaseTickets` property should be an object where each key represents a `phase_uuid`, and the value is an array of ticket objects. Each ticket object should contain the following fields that are in this [Interface](https://github.com/stakwork/sphinx-tribes-frontend/blob/master/src/people/widgetViews/PhasePlannerView.tsx#L32):
- `uuid` (string): The unique identifier of the ticket.
- `name` (string): The name of the ticket.
- `description` (string): A description of the ticket.

**Example Structure:**
```typescript
{
  "phase_uuid_1": [
    {
      "uuid": "uuid_1",
      "name": "Ticket Name 1",
      "description": "Ticket Description 1"
    },
    {
      "uuid": "uuid_2",
      "name": "Ticket Name 2",
      "description": "Ticket Description 2"
    }
  ],
  "phase_uuid_2": [
    {
      "uuid": "uuid_3",
      "name": "Ticket Name 3",
      "description": "Ticket Description 3"
    }
  ]
}
```

#### **Workflow**
1. **Storing Tickets**:  
   When fetching tickets by `phase_uuid` and `feature_uuid`, store the resulting tickets in the `phaseTickets` object under the corresponding `phase_uuid` key.

2. **Rendering Tickets**:  
   Modify the tickets rendering logic to retrieve tickets directly from the global store (`phaseTickets`).

#### **Expected Benefits**
- Centralized ticket management, making it easier to access and update tickets across the application.
- Reduced dependency on repeated API calls by caching tickets in the global store.
- Improved performance and user experience, as tickets can be accessed directly from the store.

**Comment by saithsab877** [comment]
,

**Comment by MuhammadUmer44** [comment]
k

**Comment by MahtabBukhari** [comment]
@humansinstitute assign me?

**Comment by humansinstitute** [comment]
Thanks Tobi - have built this into the wider design. Will close this one off for now to avoid confusion and update the designs.
