### ISSUE TITLE
Update Socket on Event to handle incoming message and post to console

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes-frontend#707]
In File: https://github.com/stakwork/sphinx-tribes-frontend/blob/master/src/people/widgetViews/PhasePlannerView.tsx#L60

We need an onmessage event that can receive feedback from Tribes front end through our open websocket conenction and will write the output to the console. 

## Design

Input Message of Type "ticket_message"
```
{
    broadcastType: "direct",
    sourceSessionID: ""123409829ijfdhgio,
    message: "Here is a success message",
    action: "message",
    ticketDetails: { 
        featureUUID: "chjkdhu893u0qu82908394j",
        phaseUUID: "chjkdhu893u0qu09890832",
        ticketUUID: "11111-22222-33333-44444-555555",
        ticketDescription: "I'm a new ticket description"
    }
    
}
```

Update the current `onmessage` To provide the following
- Where message is of type interface Ticket Message
- Extract data
* log message, object

Current Code

```
 socket.onmessage = (event: MessageEvent) => {
      const res = JSON.parse(event.data);
      if (res.msg === SOCKET_MSG.user_connect) {
        const sessionId = res.body;
        console.log(`Websocket Session ID: ${sessionId}`);
      }
    };
```

Example Code

```
interface TicketMessage {
  message: string;
  // Add other properties your TicketMessage interface might have
}

socket.onmessage = (event: MessageEvent) => {
  try {
    const message = JSON.parse(event.data) as TicketMessage;
    console.log(message.message);
    console.log("message object", message);
  } catch (error) {
    console.error("Error parsing message:", error);
  }
};
```

**Comment by jordan-ae** [comment]
B

**Comment by humansinstitute** [comment]
Join and post in this Sphinx Tribe for assignments:

sphinx.chat://?action=tribeV2&pubkey=0306abbf1523b90303a0b65ca3d4e1359f5079348dc4ee33625d030613875b9f47&host=tribes.v2.sphinx.chat

No Github requests / tags will be monitored.

**Comment by MahtabBukhari** [comment]
@humansinstitute assign

**Comment by Shoaibdev7** [comment]
@humansinstitute please assign me

**Comment by jordan-ae** [comment]
> Join and post in this Sphinx Tribe for assignments:

@humansinstitute i have joined

**Comment by Shoaibdev7** [comment]
@humansinstitute https://community.sphinx.chat/p/csfokk2tu2rulqj5lff0/assigned/2877/5

**Comment by Shoaibdev7** [comment]
@humansinstitute https://community.sphinx.chat/p/csfokk2tu2rulqj5lff0/assigned/2877/6
