### ISSUE TITLE
Ensure the ticket editor component correctly pulls tickets details from the `PhaseTicketStore`

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes-frontend#716]
Review ticketstore implementation in: https://github.com/stakwork/sphinx-tribes-frontend/pull/705

Ensure that:

1. The `ticket editor` component is correctly implemented to pull tickets from the store
2. The GetTicketsByPhase call on phase planner load is pulling tickets from the store. 
3. Run a local test to manually show updates to the Ticket Store updating a `ticket editor` component on the Phase Planenr Page without a manual refresh

## Assessment Criteria

- [ ] Loom recording of local test to manually show updates to the Ticket Store updating a `ticket editor` component on the Phase Planenr Page without a manual refresh

**Comment by aliraza556** [comment]
@humansinstitute Please assign me?
