### ISSUE TITLE
[BUG] - TicketUUID is undefined in call for update

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes-frontend#720]
@MahtabBukhari  - I wonder if this is an issue with the UUID as a string leading to undefined in the call? 

![Image](https://github.com/user-attachments/assets/16865fe6-86bf-4759-85c5-d3346c174a72)

Response: {"error":"Failed to get ticket: failed to get ticket: ERROR: invalid input syntax for type uuid: \"undefined\" (SQLSTATE 22P02)"}

```
Request URL:
https://people-test.sphinx.chat/bounties/ticket/undefined
Request Method:
GET
Status Code:
500 Internal Server Error
Remote Address:
35.174.148.15:443
Referrer Policy:
strict-origin-when-cross-origin
```

**Comment by MuhammadUmer44** [comment]
.

**Comment by MahtabBukhari** [comment]
@humansinstitute assign?
