### ISSUE TITLE
UI - Allow drag to extend text box on `ticket editor` component

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes-frontend#726]
In ticket editor component add a drag to expand UI Element to allow a greater area to edit the ticket description. 

![Image](https://github.com/user-attachments/assets/89a3832a-d8a0-411e-8ff0-8f06f1ca616d)

**Comment by jordan-ae** [comment]
Please assign me

**Comment by humansinstitute** [comment]
Assigned on Hive Bounties Sphinx group

sphinx.chat://?action=tribeV2&pubkey=0306abbf1523b90303a0b65ca3d4e1359f5079348dc4ee33625d030613875b9f47&host=tribes.v2.sphinx.chat

**Comment by MahtabBukhari** [comment]
@humansinstitute assign?
