### ISSUE TITLE
Review and update routes for Tribes, Bots and Default on Community.sphinx.chat

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes-frontend#732]
Tobi I would ike to remove the routes for Tirbes, Bots etc from community.sphinx.chat given previous conversations I assume these are somewhat hardcoded in the proxy. 

Ideal outcome would be:

- community.sphinx.chat/ -> Resolves to community.sphinx.chat/bounties
- community.sphinx.chat/t-> Resolves to community.sphinx.chat/bounties
- community.sphinx.chat/b-> Resolves to community.sphinx.chat/bounties

/admin and /bounty - continue to funciton

## Acceptance Criteria

- [ ] updated on community.sphinx.chat
- [ ] updated on people-test.sphinx.chat

**Comment by MahtabBukhari** [comment]
f

**Comment by humansinstitute** [comment]
@tobi-bams as discussed: 

- [ ] Update of test cases to resolve
- [ ] Check /bots endpoint (see below) 

One to check would be the route for /bots this wasn't in the navigation routes, but returns test data

![Image](https://github.com/user-attachments/assets/c2b9e8ee-c180-4515-949c-d94177768b40)

Also on prod:

![Image](https://github.com/user-attachments/assets/32737131-6861-416d-9afa-e797ab16342e)
