### ISSUE TITLE
Update V2 App links on Modal

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes-frontend#733]
When a user is not logged in the "Get Sphinx" Button pops up this modal.

<img width="1452" alt="image" src="https://github.com/user-attachments/assets/d39c0bd9-50e3-4aac-8621-39a6128493c8">

The links to android and iOS apps for sphinx need updating to V2.

- Android Link: https://play.google.com/store/apps/details?id=chat.sphinx.v2&hl=en_US
- iPhone Link: https://testflight.apple.com/join/p721ALD9

**Comment by jordan-ae** [comment]
I can help

**Comment by MahtabBukhari** [comment]
d
