### ISSUE TITLE
Get Sphinx Button INcorrectly links to buy.sphinx.chat when logged in

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes-frontend#734]
When a user is logged in the "Get Sphinx" Button links to buy.sphinx.chat (a non responsive site) instead of popping up this modal.

<img width="1452" alt="image" src="https://github.com/user-attachments/assets/d39c0bd9-50e3-4aac-8621-39a6128493c8">

Update the behaivour to always display the modal even if logged in.

**Comment by AhsanFarooqDev** [comment]
d

**Comment by humansinstitute** [comment]
Go for it :)
