### ISSUE TITLE
Fix modal to display "add bot" modal and make Bots Page forms responsive on both mobile and desktop platforms

### ISSUE THREAD

**Issue by aliraza556** [stakwork/sphinx-tribes-frontend#74]
**Describe the bug**

**1- For Both Mobile and Desktop:**
- On the Bots Page, the forms are unresponsive on both mobile and desktop platforms.

**2- For Mobile:**
- On the mobile side, the navigation bar dropdown does not hide when the screen is touched.
-  `My Bots` does not display properly in the mobile view.

**Bug Demo Link:**  [Demo](https://www.loom.com/share/508cd5bef557471b8baec2ab76ad7c53)

**To Reproduce**
1. Go to `Bots` https://community.sphinx.chat/b
2. Click on `Add a Bot`
3. Observe that the forms are unresponsive on both mobile and desktop platforms.

**Expected behavior**
When visiting the Bots Page at `https://community.sphinx.chat/b` and clicking on `Add a Bot` the following should occur:
1- The forms should be responsive and function correctly on both mobile and desktop platforms.

**For mobile:**
- The navigation bar dropdown should hide when the screen is touched.
- The 'My Bots' section should display properly in the mobile view.

**Desktop (please complete the following information):**
 - Browser [e.g. chrome]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhoneXR]

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a video in my PR for both mobile and desktop
- [ ] I've created a test that asserts the add bot button displays the add bot modal

**Comment by aliraza556** [comment]
Hey @ecurrencyhodler, could you please take a look at this and assign it to me?

**Comment by ecurrencyhodler** [comment]
Hey Ali! Okay so there is an "add bot" creation modal. Can you replace the edit bounty modal with that one? And can you also address the responsiveness? I can create a bounty for this.

**Comment by ecurrencyhodler** [comment]
posted: https://community.sphinx.chat/bounty/1330

**Comment by aliraza556** [comment]
Hi @ecurrencyhodler,
Please give me `edit bounty modal` file path if possible. 
I think this path `src/people/main/bountyModal/BountyModal.tsx`

**Comment by ecurrencyhodler** [comment]
Here it is: https://github.com/stakwork/sphinx-tribes-frontend/blob/8582e0c518f8d2d14f389d1528c47eb75eebf2d5/src/components/form/bounty/index.tsx

**Comment by ecurrencyhodler** [comment]
@aliraza556 do you have an update on this issue?

**Comment by Vayras** [comment]
@ecurrencyhodler I wish to contribute towards this, can I take this one?

**Comment by ecurrencyhodler** [comment]
Let's leave this open for a different hunter.

**Comment by Vayras** [comment]
@Vayras Sure

**Comment by ManyRios** [comment]
🙋

**Comment by Ekep-Obasi** [comment]
@ecurrencyhodler Can I have this?

**Comment by vishnu552** [comment]
@ecurrencyhodler can you assign me?

**Comment by ecurrencyhodler** [comment]
Hey @Knight0p6 are you on sphinx chat? Also how did you hear about our project?

**Comment by ecurrencyhodler** [comment]
Can you sign in here so I can assign the bounty to you? https://community.sphinx.chat/bounties

**Comment by ecurrencyhodler** [comment]
Bounty is yours! https://community.sphinx.chat/bounty/1330
