### ISSUE TITLE
Add a `featured_bounty` store to hold urls of featured bounties to be displayed on Front Page

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes-frontend#741]
Create a new store object to hold a list of featured bounties. 

This object will allow us to display details of specific bounties at the top of a list of bounties.

The Store will be used to refresh this component. 
The Store should be lablled: `bountyStore`

The store should hold:

{
bountyURL: "",
seqeunce: int
}

![image](https://github.com/user-attachments/assets/36ac24f7-d46c-47ff-886c-afc607a2adcd)

First pass we will only add a single featured bounty, but moving forwards we will have multiple bounties which will affect the front end display.

**Comment by aliraza556** [comment]
D

**Comment by MahtabBukhari** [comment]
@humansinstitute assign

**Comment by AhsanFarooqDev** [comment]
@humansinstitute can I help?
