### ISSUE TITLE
Add a featured Component to the bounties list page

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes-frontend#743]
Related to https://github.com/stakwork/sphinx-tribes-frontend/issues/741

1. Add a component to the `/bounties` view that will display a single bounty by ID
2. Follow existing bounty display with addition of a border in hex `#F7931A`
3. Get the URL for a featured bounty from the `bountyStore`
4. Parse the URL for bounty ID details.
5. Render the featured bounty at the top of the current bounties

![image](https://github.com/user-attachments/assets/6603f085-e5d7-4335-a9d5-a157038c241d)

**Comment by aliraza556** [comment]
U
