### ISSUE TITLE
Featured Bounties should only be a single featured bounty

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes-frontend#757]
https://github.com/stakwork/sphinx-tribes-frontend/issues/742

This modal is to assign and manage only a single featured bounty in this phase.

Actual 
- on first load with no bounties this should load with an empty URL
- On save the featured bounty url should be saved to the store. 
- When this modal is loaded after a featured bounty is stored it should load that URL in the modal
- This will allow editing of the URL, but not addition of new featured Urls
- I should be able to remove a featured bounty with a delete button

This will result in there only being a single featured bounty - which is correct for phase 1, the functionality.

Currently we end up with multiple featured boutnies and now way to edit. 

![Screenshot 2024-12-12 at 4 59 57 pm](https://github.com/user-attachments/assets/81a29933-e140-46e9-9d48-908da871a0c4)

We can never edit as the form never retrieves the url

![Screenshot 2024-12-12 at 4 59 10 pm](https://github.com/user-attachments/assets/802c7a66-c989-4af5-a372-0ddcb8642d43)

**Comment by saithsab877** [comment]
l

**Comment by sophieturner0** [comment]
@humansinstitute Please assign me?

**Comment by MahtabBukhari** [comment]
@humansinstitute assign

**Comment by Shoaibdev7** [comment]
@humansinstitute I can help?

**Comment by aliraza556** [comment]
@humansinstitute Please assign me?
