### ISSUE TITLE
On receipt of message {action: "update_link"} add link to ticket update

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes-frontend#759]
On receipt of websocket message update the stakwork workflow link in the ticket editor component implemented here: https://github.com/stakwork/sphinx-tribes-frontend/pull/756

The websocket message of interest is the swrun object. 

```
{
    "type": 0,
    "broadcastType": "direct",
    "sourceSessionID": "6XDPS7M3F452SO2JD6IK3K4BFHK37UHAGPSMD7AP",
    "message": "https://jobs.stakwork.com/admin/projects/75463623",
    "action": "swrun",
    "ticketDetails": {
        "featureUUID": "",
        "phaseUUID": "",
        "ticketUUID": "",
        "ticketDescription": ""
    }
}
```

We will want to:
- add a function to socket on message 
- if action = swrun
- parse the message for the stakwork ID and (remove https://jobs.stakwork.com/admin/projects/ from message) 
- generate the correct link in the ticket editor.

**Comment by MahtabBukhari** [comment]
@humansinstitute please assign me
