### ISSUE TITLE
Create a Hive Chat View with components that display history and chat

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes-frontend#760]
## Context 

Create a view to provide AI chat functionality inside Hive. 

- The chat box is something I can type into that is adjustable in height as I type it expands. 
- The Chat history will show the alternating history of the chat messages drawn from a typscript store (https://github.com/stakwork/sphinx-tribes-frontend/issues/744) that allows to instant refresh in the window as new messages are added. 

When we start the page we will start a websocket connection, we will pass the ID of this websocket client along with the chat message when we click 'send' on the chat. 

On receipt of a websocket back from the back end indicating receipt of a new chat history page. Then refresh the store to update the chat history.

## Design

- Route for this view: `/workspace/<workspaceUUID>/hivechat/<chatID>`
- ensure we utilise chat store methods in:  https://github.com/stakwork/sphinx-tribes-frontend/issues/744 to send messages, retrieve chat history etc
- The chat message will need to include the UUID from the URL in POST e.g. (there will be a further change here in the store to accomodate for this)

e.g. message for post a new chat message: 

`await chatHistoryStore.sendMessage(chatId, message, [], websocketSessionId, workspaceUUID);`

interface ChatMessage {
  chatId: string;
  message: string;
  role: 'user' ;
  timestamp: Date;
  contextTags?: [];
  status: 'sent';
  source: 'user';
  workspaceUUID: "from url";
}

Note this will require an update to the chatMessage interface to add in `workspaceUUID: string`

![Image](https://github.com/user-attachments/assets/9292ba0a-6f03-490e-9dbe-cb77cec451c6)

### Implementation Example

```
import React, { useCallback, useEffect, useState, useRef } from 'react';
import { observer } from 'mobx-react-lite';
import { useParams } from 'react-router-dom';
import { ChatMessage } from 'store/interface';
import { useStores } from 'store';
import { createSocketInstance } from 'config/socket';
import styled from '@emotion/styled';

interface ChatViewParams {
  chatId: string;
}

const ChatContainer = styled.div`
  display: flex;
  flex-direction: column;
  height: 100vh;
  padding: 20px;
`;

const ChatHistory = styled.div`
  flex-grow: 1;
  overflow-y: auto;
  margin-bottom: 20px;
  padding: 10px;
`;

const MessageBubble = styled.div<{ isAssistant: boolean }>`
  max-width: 70%;
  margin: 10px;
  padding: 15px;
  border-radius: 10px;
  background-color: ${props => props.isAssistant ? '#4A90E2' : '#2ECC71'};
  color: white;
  align-self: ${props => props.isAssistant ? 'flex-start' : 'flex-end'};
  word-wrap: break-word;
`;

const ChatInputContainer = styled.div`
  display: flex;
  gap: 10px;
  padding: 10px;
  background: white;
  border-top: 1px solid #eee;
`;

const ChatTextArea = styled.textarea`
  flex-grow: 1;
  padding: 10px;
  border: 1px solid #ddd;
  border-radius: 5px;
  resize: none;
  min-height: 50px;
  max-height: 200px;
  font-family: inherit;
`;

const SendButton = styled.button`
  padding: 10px 20px;
  background-color: #4A90E2;
  color: white;
  border: none;
  border-radius: 5px;
  cursor: pointer;
  align-self: flex-end;

  &:disabled {
    background-color: #cccccc;
    cursor: not-allowed;
  }
`;

const ChatView: React.FC = observer(() => {
  const { chatId } = useParams<ChatViewParams>();
  const [message, setMessage] = useState('');
  const [websocketSessionId, setWebsocketSessionId] = useState('');
  const [isSending, setIsSending] = useState(false);
  const { chatHistoryStore } = useStores();
  const chatHistoryRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const socket = createSocketInstance();

    socket.onopen = () => {
      console.log('Socket connected in Chat View');
    };

    socket.onmessage = async (event: MessageEvent) => {
      try {
        const data = JSON.parse(event.data);
        console.log('Websocket message:', data);
        
        if (data.type === 'session_id') {
          setWebsocketSessionId(data.sessionId);
          return;
        }

        if (data.type === 'chat_update') {
          await chatHistoryStore.loadChatHistory(chatId);
        }
      } catch (error) {
        console.error('Error processing websocket message:', error);
      }
    };

    socket.onclose = () => {
      console.log('Socket disconnected in Chat View');
    };

    return () => {
      if (socket.readyState === WebSocket.OPEN) {
        socket.close();
      }
    };
  }, [chatId, chatHistoryStore]);

  useEffect(() => {
    chatHistoryStore.loadChatHistory(chatId);
  }, [chatId, chatHistoryStore]);

  useEffect(() => {
    if (chatHistoryRef.current) {
      chatHistoryRef.current.scrollTop = chatHistoryRef.current.scrollHeight;
    }
  }, [chatHistoryStore.getChatMessages(chatId)]);

  const handleMessageChange = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
    setMessage(e.target.value);
    e.target.style.height = 'auto';
    e.target.style.height = `${Math.min(e.target.scrollHeight, 200)}px`;
  };

  const handleSendMessage = async () => {
    if (!message.trim() || isSending) return;

    setIsSending(true);
    try {
      await chatHistoryStore.sendMessage(chatId, message, [], websocketSessionId);
      setMessage('');
    } catch (error) {
      console.error('Error sending message:', error);
    } finally {
      setIsSending(false);
    }
  };

  const handleKeyPress = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      handleSendMessage();
    }
  };

  const messages = chatHistoryStore.getChatMessages(chatId);

  return (
    <ChatContainer>
      <ChatHistory ref={chatHistoryRef}>
        {messages.map((msg: ChatMessage) => (
          <MessageBubble
            key={msg.id}
            isAssistant={msg.role === 'assistant'}
          >
            {msg.message}
          </MessageBubble>
        ))}
      </ChatHistory>
      <ChatInputContainer>
        <ChatTextArea
          value={message}
          onChange={handleMessageChange}
          onKeyPress={handleKeyPress}
          placeholder="Type your message..."
          disabled={isSending}
        />
        <SendButton
          onClick={handleSendMessage}
          disabled={!message.trim() || isSending}
        >
          Send
        </SendButton>
      </ChatInputContainer>
    </ChatContainer>
  );
});

export default ChatView;
```

Design: 

Message Display & History
- Messages should be displayed in a scrollable container
- Each message should be in a bubble with distinct styling for user (green) and assistant (blue) messages
- User messages should be right-aligned, assistant messages left-aligned
- Chat history should automatically load when viewing a conversation
- Chat should automatically scroll to the latest message when new messages arrive

Message Input
- Input should be an auto-expanding textarea with a minimum and maximum height (50px-200px)
- Input should be sticky at the bottom of the page
- Support Enter to send message and Shift+Enter for new line
- Input should disable while a message is being sent 
- Clear input field after successful message send
- Empty messages should not be sendable

WebSocket Integration
- Establish WebSocket connection when component mounts
- Handle WebSocket session ID reception and storage
- Process real-time chat updates through WebSocket messages
- Properly close WebSocket connection on component unmount
- Implement error handling for WebSocket operations

UI/UX Requirements
- Component should take full viewport height
- Input area should be fixed at bottom with message history scrolling above
- Include a Send button that disables during message transmission
- Provide visual feedback during message sending
- Ensure responsive design that works across different screen sizes

State Management
- Integrate with MobX store for chat history management
- Maintain sending state to prevent duplicate submissions
- Handle loading states appropriately
- Implement error handling for message sending operations

## Accceptance Criteria

- [ ]  Set up basic component structure 
- [ ]  implement and verify web socket connectivity
- [ ] Message send via store works correctly
- [ ]  Meet proscribed UI design
- [ ]  Handle loading & error states

**Comment by humansinstitute** [comment]
@MuhammadUmer44 - had to make two clarificatiosn here: 

- Route for this view: `/workspace/workspaceUUID/hivechat`
- ensure we utilise chat store methods in:  https://github.com/stakwork/sphinx-tribes-frontend/issues/744 to send messages, retrieve chat history etc
- The chat message will need to include the UUID from the URL in POST e.g. (there will be a further change here in the store to accomodate for this)

e.g. message for post a new chat message: 

`await chatHistoryStore.sendMessage(chatId, message, [], websocketSessionId, workspaceUUID);`

interface ChatMessage {
  chatId: string;
  message: string;
  role: 'user' ;
  timestamp: Date;
  contextTags?: [];
  status: 'sent';
  source: 'user';
  workspaceUUID: "from url";
}

**Comment by MuhammadUmer44** [comment]
@humansinstitute I check and fix it
