### ISSUE TITLE
Update the ticket_message interface with {action: "run-link"}

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes-frontend#761]
https://github.com/stakwork/sphinx-tribes-frontend/issues/695

Update the ticket interface to allow:   
```
action: 'process' | 'message' | run-link;       // Action to be performed
```

**Comment by MuhammadUmer44** [comment]
@humansinstitute, please release the payment for the task: https://community.sphinx.chat/p/csfohrqtu2rulqj5lfe0/assigned/2896/16.
