### ISSUE TITLE
Update TicketEditor to Include Author and TicketGroup in Payloads

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes-frontend#767]
## Context
With the introduction of ticket versioning and authorship tracking, we need to update the TicketEditor component to properly include author and ticketGroup information in update and builder payloads.

## Current Behavior
Current payload construction in TicketEditor:
```typescript
const ticketPayload = {
  metadata: {
    source: 'websocket',
    id: websocketSessionId
  },
  ticket: {
    ...ticketData,
    name,
    description,
    status: 'DRAFT' as TicketStatus,
    version: ticketData.version + 1
  }
};
```

### 1. Update handleUpdate() Function
```typescript
const handleUpdate = async () => {
  try {
    const ticketPayload = {
      metadata: {
        source: 'websocket',
        id: websocketSessionId
      },
      ticket: {
        ...ticketData,
        name,
        description,
        status: 'DRAFT' as TicketStatus,
        version: ticketData.version + 1,
        author: 'HUMAN' as Author,
        author_id: userId, // Need to get from current user context
        ticket_group: ticketData.ticket_group || ticketData.uuid // Use existing group or create new
      }
    };
    // Rest of update logic
  } catch (error) {
    console.error('Error updating ticket:', error);
    addUpdateErrorToast();
  }
};
```

### 2. Update handleTicketBuilder() Function
```typescript
const handleTicketBuilder = async () => {
  try {
    const ticketPayload = {
      metadata: {
        source: 'websocket',
        id: websocketSessionId
      },
      ticket: {
        ...ticketData,
        name,
        description,
        status: 'DRAFT' as TicketStatus,
        author: 'AGENT' as Author,
        author_id: 'TICKET_BUILDER',
        ticket_group: ticketData.ticket_group || ticketData.uuid
      }
    };
    // Rest of builder logic
  } catch (error) {
    console.error('Error in ticket builder:', error);
    addErrorToast();
  }
};
```

## Technical Requirements
1. Access to current user context for author_id
2. Proper handling of ticket_group field (use existing or create new)
3. Correct author type assignment ('HUMAN' for updates, 'AGENT' for ticket builder)

## Files to Modify
- TicketEditor.tsx

## Acceptance Criteria
- [ ] Manual updates include:
    - [ ] author: 'HUMAN'
    - [ ] author_id: current user's ID
    - [ ] ticket_group: maintained across versions
- [ ] Ticket Builder updates include:
    - [ ] author: 'AGENT'
    - [ ] author_id: 'TICKET_BUILDER'
    - [ ] ticket_group: maintained across versions
- [ ] Existing functionality remains intact
- [ ] Proper error handling maintained
- [ ] Toast notifications work correctly

**Comment by saithsab877** [comment]
k

**Comment by MahtabBukhari** [comment]
@humansinstitute assign me I am doing work here

**Comment by humansinstitute** [comment]
@saithsab877 - we're having some testing issues with staging today so will close out bounty now and come back later and tag if there are bugs.
