### ISSUE TITLE
Increase the width of the display bounty modal

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes-frontend#774]
- Currently the modal at `bounty/<bountyid>` is fixed width and can be hard to read for code heavy or longer bounties. 
- The current width should be a minimum width it displays at. 
- The width should be able to expand up to 75% of the screen size in which the modal is displayed. 
- The total max width should be 2.5x the current minimum size. 

![image](https://github.com/user-attachments/assets/b927b458-e638-4d41-898a-ffe532ec99f2)

## Acceptance Criteria

- [ ] Minimum width and mobile view on smaller windows is retained
- [ ] Maximum width of 250% of the fixed minimum value when viewing on large wide screens
- [ ] Width otherwise expands at 75% the total size of the window

**Comment by MahtabBukhari** [comment]
@humansinstitute please assign

**Comment by humansinstitute** [comment]
> @humansinstitute please assign

Assigned - Sphinx is currently down but bounty here: https://community.sphinx.chat/bounty/2984

**Comment by humansinstitute** [comment]
@MahtabBukhari - for clarity, can we expand the contents of the column with the bounty description into this space, not the right hand column. 

![image](https://github.com/user-attachments/assets/00b9dae3-29ba-4b0f-ae8e-d3ed49a94eee)

**Comment by MahtabBukhari** [comment]
@humansinstitute sure that's right way
