### ISSUE TITLE
Navigation Breaks when closing modal in profile page

### ISSUE THREAD

**Issue by ChetanKarwa** [stakwork/sphinx-tribes-frontend#78]
**Describe the bug**
When we close the add new ticket modal in Profile section the navigation breaks.

https://www.loom.com/share/c9cd3070c37642a19216cd77fda23396

**To Reproduce**
1. Go to 'Your Profile'
2. Click on 'Bounties'
3. click to 'Click on add new ticket'
4. Close the modal
5. See the error

**Expected behavior**
Modal should close and user should stay on the same profile page

**Desktop (please complete the following information):**
 - Browser: chrome

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a screenshot or video in my PR
- [ ] I have written a test to assert that no unnecessary navigation takes place

**Comment by ChetanKarwa** [comment]
Please assign this to me
@ecurrencyhodler

**Comment by ecurrencyhodler** [comment]
Here's a 100k bounty for you: https://community.sphinx.chat/bounty/1316

**Comment by aliraza556** [comment]
@ecurrencyhodler he works fine:
https://www.loom.com/share/bc5fc65767d642aa9e651ff2937b03b6

**Comment by ecurrencyhodler** [comment]
I'm getting some weird redirects. I think it's tied specifically to the "new button" bounty.
https://github.com/ElementsProject/lightning/assets/32662508/94d2ba22-409f-44ed-88c5-a501c0594741
