### ISSUE TITLE
Update the Front End Websocket processing on Phase Planner to integrate Ticket Builder Refresh

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes-frontend#781]
For ticket builder after changing at backend side we also need changes at frontend too at websocket process

Frontend changes related to processing the websocket update event from backend to be deployed in: https://github.com/stakwork/sphinx-tribes/issues/2195

**Comment by humansinstitute** [comment]
@MahtabBukhari - issue for the front end updates as discussed.

**Comment by MahtabBukhari** [comment]
@humansinstitute assign
