### ISSUE TITLE
Enable Github like image Paste in Ticket Editor Component

### ISSUE THREAD

**Issue by tobi-bams** [stakwork/sphinx-tribes-frontend#789]
### Context  
We want to enable pasting images directly into the ticket component.  

### Design  
1. The ticket component should include a **Preview** button to display the description as **markdown**.  
2. When in **edit mode**, use the `TicketTextArea` component.  
3. When in **preview mode**, use the `renderMarkdown` function found in this [file](https://github.com/stakwork/sphinx-tribes-frontend/blob/master/src/people/utils/RenderMarkdown.tsx#L7).  
4. In the `TicketTextArea` component, listen for the `onPaste` event and handle it as follows:  
    - Check whether the pasted content is an image or plain text.  
    - If it's **text**, allow the default behavior of appending the text to the description.  
    - If it's an **image**, immediately append a placeholder in the description using the format:  
      ```  
      ![Uploading unique-uuid-filename…]()  
      ```  
      - Ensure that each placeholder has a unique identifier (e.g., a UUID) to handle multiple simultaneous uploads.  
    - Upload the image through the `public_pic` endpoint (which stores it in the Meme Server). For reference, see a sample upload [here](https://github.com/stakwork/sphinx-tribes-frontend/blob/8fbb1514abe968b0d65b5fe2c564cd08f544a9ff/src/components/form/inputs/GalleryInput.tsx#L72).  
    - **v.** If the upload is successful, replace the placeholder with the final markdown:  
      ```  
      ![image](image_url_from_response)  
      ```  
    - **vi.** If the upload fails, update the placeholder to indicate failure:  
      ```  
      ![Failed to upload unique-uuid-filename…]()  
      ```

**Comment by jordan-ae** [comment]
I'm available

**Comment by jordan-ae** [comment]
I'm available

**Comment by MahtabBukhari** [comment]
@tobi-bams @humansinstitute assign

**Comment by aliraza556** [comment]
Hi @humansinstitute, @tobi-bams, Please assign me?

**Comment by humansinstitute** [comment]
@jordan-ae 

[BUG] - please update a new PR to switch edit and preview labels on the button in the ticket editor. 

E.g. this should say "Preview" as this will load the preview.

![Image](https://github.com/user-attachments/assets/6a878ea2-9c7e-4f8a-9d4d-4babf7d6d1a5)

E.g. this should say "edit" as this will exit preview and allow edits.

![Image](https://github.com/user-attachments/assets/c7ce15d2-d936-4e56-905d-69565de0dd57)

**Comment by jordan-ae** [comment]
@humansinstitute I've opened a PR to fix this. I added a switcher component. There's a demo on the PR. Hope it matches the UX we are aiming for

**Comment by humansinstitute** [comment]
Looks good. just merged
