### ISSUE TITLE
Profile Page: CSS broken in Claim Badge Modal

### ISSUE THREAD

**Issue by ChetanKarwa** [stakwork/sphinx-tribes-frontend#79]
**Describe the bug**
CSS broken in Claim Badge Modal:
- Overlapping title with input box
- Inputbox is not clickable
- The title isn't visible

<img width="437" alt="image" src="https://github.com/stakwork/sphinx-tribes-frontend/assets/46815976/d950cecf-30ad-4789-bad7-660b30230ba0">

**To Reproduce**
1. Go to 'Profile Page'
2. Click on 'Badges'
3. Click on 'OFF-Chain' under any badge

**Expected behavior**
- Should not overlap
- Inputbox Should be clickable 
- Title should be on darker color spectrum for proper visiblity

**Desktop (please complete the following information):**
 - Browser: Chrome

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a video in my PR

**Comment by ecurrencyhodler** [comment]
I added a test to the issue. This will be 50k.
