### ISSUE TITLE
PeopleList: Calendar for selecting date is faded.

### ISSUE THREAD

**Issue by ChetanKarwa** [stakwork/sphinx-tribes-frontend#80]
**Describe the bug**
The calendar in the send tip flow for a person is faded
<img width="704" alt="image" src="https://github.com/stakwork/sphinx-tribes-frontend/assets/46815976/cc7a7149-aaee-4a95-9f0a-716dd20965c8">

**Expected behavior**
It should not be faded

**Desktop (please complete the following information):**
 - Browser: chrome

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a video in my PR
- [ ] I have created a test that the calendar table is visible when I click on it

**Comment by ChetanKarwa** [comment]
@ecurrencyhodler Please assign this to me

**Comment by ecurrencyhodler** [comment]
https://community.sphinx.chat/bounty/1320

**Comment by MahtabBukhari** [comment]
Hi @ChetanKarwa , Have you found this modal in this project files if yes could you tell me where it is ?
![image](https://github.com/stakwork/sphinx-tribes-frontend/assets/98140673/5bd7c8b9-f8ff-498f-8955-2579a81d1630)

**Comment by ecurrencyhodler** [comment]
@ChetanKarwa do you have an update on this issue?

**Comment by ecurrencyhodler** [comment]
This repo where this code lives is private so I'm going to have to cancel this bounty. Sorry.
