### ISSUE TITLE
Bots Page 404 error when refresh

### ISSUE THREAD

**Issue by Fog3211** [stakwork/sphinx-tribes-frontend#81]
**Describe the bug**
bots page will 404 error when refresh browser

**To Reproduce**
open  [https://community.sphinx.chat/b](https://community.sphinx.chat/b) directly.
or
1、open homepage [https://community.sphinx.chat](https://community.sphinx.chat/) 
2、 switch to bots page 
3、 refresh browser

https://github.com/stakwork/sphinx-tribes-frontend/assets/23151576/ed120231-0531-4a10-b2b7-3560b9d54c8b

**Expected behavior**
When refreshing the browser, the bot page should not display a 404 error.

**Desktop (please complete the following information):**
 - Browser Chrome120

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a screenshot or video in my PR

**Comment by ecurrencyhodler** [comment]
Good find. I'll turn this into a 50k bounty for you. Is there a potential test you could include for the fix such as asserting that the page reloads when refreshing?

**Comment by ecurrencyhodler** [comment]
Also fog, I see there are two sphinx profiles for you. Can you delete the one you're not using so I don't accidentally assign the wrong account for the boutny?

**Comment by Fog3211** [comment]
> Good find. I'll turn this into a 50k bounty for you. Is there a potential test you could include for the fix such as asserting that the page reloads when refreshing?

sure, i will fix  and test it

**Comment by Fog3211** [comment]
> Also fog, I see there are two sphinx profiles for you. Can you delete the one you're not using so I don't accidentally assign the wrong account for the boutny?

The [old account](https://community.sphinx.chat/p/0368c4fce96ddb3e3cefe477c9e1b418e467a97441afe4a98c8420815ef0203060/organizations) is no longer in use because I forgot to save the key when logging out (and now I can't log in). 
Can you please delete it from the backend for me? 
I've made some markings on my [new account](https://community.sphinx.chat/p/029af7d69844a86767cca8b9f790e005e6f9fd2614ed6fba645ce5bf0af9613543/organizations) and I hope they can be more prominent.  --> Fog3211(in use)

**Comment by Fog3211** [comment]
@ecurrencyhodler  i cannot send message to you 😭
![image](https://github.com/stakwork/sphinx-tribes-frontend/assets/23151576/8384dad1-f184-4dfe-bc3c-e5b785c0d594)

**Comment by Fog3211** [comment]
@ecurrencyhodler 

I have found that the issue is not within the code itself, but rather in the configuration of Traefik's routing rules. Therefore, I did not provide a unit test file.
