### ISSUE TITLE
Remove saving bounty url from history when viewing it from profile

### ISSUE THREAD

**Issue by Vayras** [stakwork/sphinx-tribes-frontend#87]
Issue:https://www.loom.com/share/f1277f7b94854e6fa2643cd851abeb71
cause of the issue: use of history.goBack() which only returns to the last known url 
possible fix: using routing to improve this functionality

**Comment by ecurrencyhodler** [comment]
Okay so let's keep saving the url. We think it's okay that it goes back to the "people" page when you click back. 

But what we don't want is to go back to the bounty like you have shown in the video. So we should remove bounties from being saved as a url in the history. Does that make sense to you?

**Comment by Vayras** [comment]
@ecurrencyhodler Sure, yeah that makes sense to me we can use state and routes to handle it more efficiently.

**Comment by ecurrencyhodler** [comment]
Bounty posted https://community.sphinx.chat/bounty/1329

**Comment by Vayras** [comment]
@ecurrencyhodler Thanks
