### ISSUE TITLE
Add restrictions to the "Edit Organization" UI

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes-frontend#9]
### Context
We are going to add character limits to org name and org description. Create a frontend check that checks the character limit of both. If a user tries to type 1 character above the limit, prevent them from doing so and turn the ui red. See the design below.

So if the limit is 20 characters and a user types 20 characters, there is no restriction. But if they try to type a 21st character, that triggers this restriction.

### Design
Here is the design in [figma](https://www.figma.com/file/1aL3lgG5Rpkti4b0j42fwf/Bounties---FINAL-DESIGNS?type=design&node-id=10360%3A6845&mode=design&t=YkGgbWPNm39dVUOw-1).  Use [dev mode](https://www.figma.com/dev-mode/) for exact requirements. Simply follow the design for the red box and text and numbers. Ignore the title "add new org" and "add org" button.
![Edit Organization](https://github.com/stakwork/sphinx-tribes-frontend/assets/32662508/adf2cd6e-13a1-43c6-9793-0179285e0a70)

### Acceptance Criteria
- [ ] I've tested on Chrome
- [ ] I've submitted a recording in my pr
- [ ] I've created mock data of 21 characters for org name and 121 characters for org description
- [ ] I've created a component tests that asserts if an input over the restriction is provided, they are restricted for both org name and org description

**Comment by vishnu552** [comment]
@ecurrencyhodler please , assign me this issue.

**Comment by vishnu552** [comment]
Hello @ecurrencyhodler,
I have created a pull request titled 'Disable Save Button.' I made the changes as you suggested. Now, when users type more characters than the specified limit, the save button becomes disabled.
