### ISSUE TITLE
Enable CSV export on prod

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes-frontend#91]
**Describe the bug**
CSV export of superadmin isn't working on prod but is on staging.

https://github.com/stakwork/sphinx-tribes-frontend/assets/32662508/99de3f4e-c15a-4f54-bb76-7122a2444b03

**Expected behavior**
I should be able to export csv from prod.

**Desktop (please complete the following information):**
 - Browser: Chrome

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a video in my PR including results of csv file

**Comment by MirzaHanan** [comment]
@ecurrencyhodler please assign me?

**Comment by elraphty** [comment]
@ecurrencyhodler It has been fixed, on production server deployment configurations, it will be updated once we update the production server.
