### ISSUE TITLE
Fix the issue where the SAT and payment countdown go below zero on the 'Send Tip' popup.

### ISSUE THREAD

**Issue by MahtabBukhari** [stakwork/sphinx-tribes-frontend#97]
**Describe the bug**
When we go to a people page, click on any individual profile, and then proceed to click on the 'Send Tip' button, the SAT and payment countdown drop below zero.

https://www.loom.com/share/f31994a3219447278a0bf680803b67e2?sid=89b34033-5c24-4096-865d-4808552fb848

**To Reproduce**
1. Go to 'People page'
2. Click on 'select any profile means people card'
3. Then click on 'Send Tip button'
4. set sat and payment zero manually 
5. click on below button to decrease the amount and watch the bug (-1,-2 and so on)

**Expected behavior**
Please fix the issue that the sat and payment countdown does not go below zero.

**Desktop (please complete the following information):**
 - Browser [chrome]

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a screenshot or video in my PR
- [ ] I have write a test that check when user click countdown below button then number does not go below to zero.

**Comment by MahtabBukhari** [comment]
@ecurrencyhodler could you look at this issue and assign to me?

**Comment by ecurrencyhodler** [comment]
Good find. We should limit it to go only as low as 0. Thanks for including a test as well. Here's a 100k bounty for you: https://community.sphinx.chat/bounty/1334

**Comment by MahtabBukhari** [comment]
Thank you 😊

**Comment by MahtabBukhari** [comment]
Hi @Evanfeenstra, I hope you are well. I see that you have implemented SendTip Modal to donate some one
I search it out from the whole project but I have not found it. I just found the static html but not the implementation of that work. could you help me to tell that where is its implementation?

# PersonPage.tsx:
I found just that static values 
![image](https://github.com/stakwork/sphinx-tribes-frontend/assets/98140673/d44b0c78-6fe9-4150-8227-fc2623f9c6bc)

and see that it is dangerously set to inner html like that 
![image](https://github.com/stakwork/sphinx-tribes-frontend/assets/98140673/f2ba6b39-42e7-4159-bbdc-d356314108a4)

I think its logic implementation is present on amazon based file
![image](https://github.com/stakwork/sphinx-tribes-frontend/assets/98140673/d231e144-af60-451b-af56-6ff8e482d7a8)

@ecurrencyhodler Could you please confirm this issue from someone , I have spent two day and try to find in every file and found just above implementation

**Comment by MahtabBukhari** [comment]
I think may be @ChetanKarwa also have facing this one because he have not worked on it yet. Please confrm that is I am right @ChetanKarwa ?

**Comment by ecurrencyhodler** [comment]
I missed this. I'll raise it this monday.

**Comment by MahtabBukhari** [comment]
> I missed this. I'll raise it this monday.

@ecurrencyhodler Ok then I have not any other task to do . Are you have any task for me then?

**Comment by ecurrencyhodler** [comment]
You can find open bounties here: https://community.sphinx.chat/bounties

**Comment by ecurrencyhodler** [comment]
Okay @MahtabBukhari this is in a private repo. So I'm going to cancel the bounty. Sorry.
