### ISSUE TITLE
Fix the bug in searching in search box of the people card.

### ISSUE THREAD

**Issue by MahtabBukhari** [stakwork/sphinx-tribes-frontend#99]
**Describe the bug**
Fix the bug in the search box of the people card. When searching for any name and then clicking '<-- back ', the search box clears in 
 people page but does not display all people cards.

https://www.loom.com/share/246d5135e48042c382f310ade268a025?sid=12e28d5e-0e3d-464c-ba31-30dafe162518

**To Reproduce**
1. Go to 'People page'
2. select any 'people card'
3. Search any name in search box and click on <-- back button link
4. See bug in People page search box clear but all people card not displaying

**Expected behavior**
 After searching a name, clicking back should display all people cards on People page with cleared search box

**Desktop (please complete the following information):**
 - Browser [chrome]

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a screenshot or video in my PR

**Comment by MahtabBukhari** [comment]
@ecurrencyhodler please also review this bug.

**Comment by ecurrencyhodler** [comment]
Thanks for submitting this issue but it was fixed in https://github.com/stakwork/sphinx-tribes-frontend/pull/18
